import Mathlib
import IndisputableMonolith.Constants
import IndisputableMonolith.Cost
import IndisputableMonolith.Cosmology.CosmicZHistory

/-!
# Cosmic Z Scale Law

This module tightens the last shape residue in the dark-energy plan.

`CosmicZHistory` proves that, under the BIT kernel,

`δw(z) = δw₀ · Z(z)/Z_today`.

So the dark-energy shape is exactly the normalized cosmic-Z history. The remaining question
is why that normalized history should be the scale factor `a(z)=1/(1+z)`.

This module records the sharp admissibility condition that forces it:

**Scale-affine ledger law.** Along the cosmic interval from the early zero-complexity
endpoint `a=0` to today `a=1`, equal scale-factor fractions carry equal recognition-ledger
fractions. Formally, the normalized Z-fraction preserves convex interpolation between the
two endpoints.

That condition is not a curve fit. It is the statement that no intermediate scale-factor
coordinate is selected by the ledger before a new physical input is supplied. Under that
law, the normalized Z-history is uniquely `Z/Z_today = a`, and the BIT kernel gives
`δw(z)=δw₀/(1+z)`.

Status: THEOREM conditional on the named scale-affine ledger admissibility law. Zero `sorry`,
zero new `axiom`.
-/

namespace IndisputableMonolith
namespace Cosmology
namespace CosmicZScaleLaw

open Constants
open Cost

noncomputable section

/-! ## §1. Scale-factor coordinate -/

/-- The cosmological scale factor as a function of redshift. -/
def scaleFactor (z : ℝ) : ℝ := 1 / (1 + z)

/-- The scale factor is `1` today. -/
theorem scaleFactor_today : scaleFactor 0 = 1 := by
  unfold scaleFactor
  norm_num

/-- For `z ≥ 0`, the scale factor is positive. -/
theorem scaleFactor_pos {z : ℝ} (hz : 0 ≤ z) : 0 < scaleFactor z := by
  unfold scaleFactor
  have h : (0 : ℝ) < 1 + z := by linarith
  positivity

/-- For `z ≥ 0`, the scale factor is at most `1`. -/
theorem scaleFactor_le_one {z : ℝ} (hz : 0 ≤ z) : scaleFactor z ≤ 1 := by
  unfold scaleFactor
  have h : (0 : ℝ) < 1 + z := by linarith
  rw [div_le_one h]
  linarith

/-! ## §2. The scale-affine ledger law -/

/-- A normalized cosmic-Z history is scale-affine if it preserves the interpolation from
the early zero-complexity endpoint `a=0` to today `a=1`.

The field `scale_affine_from_early_to_today` is the precise no-extra-coordinate condition:
the ledger is uniform in the scale-factor coordinate until a further physical structure is
introduced. -/
structure ScaleAffineZLaw where
  /-- Normalized Z-fraction as a function of scale factor `a`. -/
  Zfrac : ℝ → ℝ
  /-- Early endpoint: no accumulated cosmic Z at `a=0`. -/
  early_zero : Zfrac 0 = 0
  /-- Today endpoint: normalized accumulated cosmic Z is `1` at `a=1`. -/
  today_one : Zfrac 1 = 1
  /-- Ledger-uniform interpolation between the two endpoints. -/
  scale_affine_from_early_to_today :
    ∀ a : ℝ, Zfrac ((1 - a) * 0 + a * 1) = (1 - a) * Zfrac 0 + a * Zfrac 1

/-- The scale-affine ledger law uniquely forces the normalized Z-fraction to be the identity
map on scale factor. -/
theorem scaleAffine_forces_identity (law : ScaleAffineZLaw) (a : ℝ) :
    law.Zfrac a = a := by
  have h := law.scale_affine_from_early_to_today a
  simpa [law.early_zero, law.today_one] using h

/-- The canonical scale-affine law, included as the witness that the admissibility class is
inhabited. -/
def canonicalScaleAffineZLaw : ScaleAffineZLaw where
  Zfrac := fun a => a
  early_zero := rfl
  today_one := rfl
  scale_affine_from_early_to_today := by
    intro a
    ring

/-! ## §3. Redshift history forced by scale-affinity -/

/-- The cosmic-Z history generated by a scale-affine law. -/
def ZfromScaleLaw (Zt : ℝ) (law : ScaleAffineZLaw) (z : ℝ) : ℝ :=
  Zt * law.Zfrac (scaleFactor z)

/-- Scale-affinity forces the redshift history to be the linear-in-scale-factor history
`Z(z)=Z_today/(1+z)`. -/
theorem scaleAffine_forces_linearZ (Zt : ℝ) (law : ScaleAffineZLaw) (z : ℝ) :
    ZfromScaleLaw Zt law z = CosmicZHistory.linearZ Zt z := by
  unfold ZfromScaleLaw CosmicZHistory.linearZ scaleFactor
  rw [scaleAffine_forces_identity law]
  rw [mul_one_div]

/-- Therefore scale-affinity forces the canonical BIT deviation
`δw(z)=δw₀/(1+z)`. -/
theorem scaleAffine_forces_canonical_deviation (dw0 Zt : ℝ) (law : ScaleAffineZLaw)
    (z : ℝ) (hZt : Zt ≠ 0) (hz : (1 : ℝ) + z ≠ 0) :
    CosmicZHistory.bitDeviation dw0 Zt (ZfromScaleLaw Zt law) z = dw0 / (1 + z) := by
  have hfun : ZfromScaleLaw Zt law = CosmicZHistory.linearZ Zt := by
    funext x
    exact scaleAffine_forces_linearZ Zt law x
  rw [hfun]
  exact CosmicZHistory.linear_accumulation_forces_canonical_kernel dw0 Zt z hZt hz

/-- The induced equation of state is the canonical kernel
`w(z)=-1+δw₀/(1+z)`. -/
theorem scaleAffine_forces_canonical_kernel (dw0 Zt : ℝ) (law : ScaleAffineZLaw)
    (z : ℝ) (hZt : Zt ≠ 0) (hz : (1 : ℝ) + z ≠ 0) :
    CosmicZHistory.bitKernel dw0 Zt (ZfromScaleLaw Zt law) z = -1 + dw0 / (1 + z) := by
  have h := scaleAffine_forces_canonical_deviation dw0 Zt law z hZt hz
  unfold CosmicZHistory.bitDeviation at h
  linarith [h]

/-! ## §4. Certificate -/

/-- **COSMIC Z SCALE-LAW CERTIFICATE.** The named scale-affine ledger admissibility law
forces the normalized cosmic-Z history to be the scale factor and hence forces the canonical
dark-energy shape. -/
structure CosmicZScaleLawCert where
  identity_forced :
    ∀ (law : ScaleAffineZLaw) (a : ℝ), law.Zfrac a = a
  redshift_history_forced :
    ∀ (Zt : ℝ) (law : ScaleAffineZLaw) (z : ℝ),
      ZfromScaleLaw Zt law z = CosmicZHistory.linearZ Zt z
  canonical_deviation_forced :
    ∀ (dw0 Zt : ℝ) (law : ScaleAffineZLaw) (z : ℝ),
      Zt ≠ 0 → (1 : ℝ) + z ≠ 0 →
        CosmicZHistory.bitDeviation dw0 Zt (ZfromScaleLaw Zt law) z = dw0 / (1 + z)
  canonical_kernel_forced :
    ∀ (dw0 Zt : ℝ) (law : ScaleAffineZLaw) (z : ℝ),
      Zt ≠ 0 → (1 : ℝ) + z ≠ 0 →
        CosmicZHistory.bitKernel dw0 Zt (ZfromScaleLaw Zt law) z = -1 + dw0 / (1 + z)

/-- The scale-law certificate is inhabited. -/
def cosmicZScaleLawCert : CosmicZScaleLawCert where
  identity_forced := scaleAffine_forces_identity
  redshift_history_forced := scaleAffine_forces_linearZ
  canonical_deviation_forced := scaleAffine_forces_canonical_deviation
  canonical_kernel_forced := scaleAffine_forces_canonical_kernel

end

end CosmicZScaleLaw
end Cosmology
end IndisputableMonolith
