/-
  PrimitiveRecognitionCalculus/Continuum/ForcedJOnCompletion.lean

  THE CAPSTONE (C2). Assembles:
  (a) the completion R_delta as a complete ordered field (RealCompleteOrderedField),
  (b) the cost on the field (PRCCostOnField / PRCNativeCostUniqueness), and
  (c) the character-rigidity lemma from Continuum.CharacterRigidityForcing,
  into the headline theorem: on the completion R_delta, the recognition laws
  FORCE the cost to be the canonical J(x) = (x + 1/x)/2 - 1, unique up to the
  proved one-parameter gauge (the unit of scale).

  This is the math/physics demarcation: what is forced on the completion is J;
  the completion itself is the named commitment.

  Choice-free where the delta core is. The field-display step (Cost.Jcost on ℝ,
  from PRCCostOnField) is documented but not routed through the capstone theorem.
-/

import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.PRCCostOnField
import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.RealCompleteOrderedField
import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.PRCNativeCostUniqueness
import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.Continuum.CharacterRigidityForcing

namespace IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.Continuum

open IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus
open IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.PRCJCost

/-! ## (a) The completion R_delta exists -/

/-- The completion R_delta exists with conditional field structure.
    The carrier is `PRCRealNullClosed` (the null-distance quotient of Cauchy
    ledgers), with addition and negation proved closed and congruent.
    Multiplication, order, and completeness are reduced to named exact targets.
    This is the named commitment: the continuum is NOT forced by distinction
    (see `RealLineNonNativity`), but once made, the completion exists. -/
theorem completion_R_delta_exists :
    PRCRealCompleteOrderedFieldConditionalCertificate :=
  prc_real_complete_ordered_field_conditional_certificate

/-! ## (b) The canonical cost on ratio orbits -/

/-- The canonical PRC cost on a ratio orbit `q` has the rational display
    `J(q) = (q + q⁻¹)/2 − 1`. This is the quotient-native form of the cost;
    it does not pass through Mathlib's classical `Real`. -/
theorem canonical_cost_is_J_formula (q : RatioOrbit) :
    (onRatioOrbit q).toRat = (q.toRat + q.toRat⁻¹) / 2 - 1 :=
  onRatioOrbit_toRat q

/-- The canonical cost is reciprocal-symmetric: `J(q) ≈ J(q⁻¹)`.
    This is the one-parameter gauge: the identity character `χ = id` and the
    reciprocal character `χ = recip` both generate the same cost, because
    `costFromCharacter id q = onRatioOrbit q` and
    `costFromCharacter recip q = onRatioOrbit (q⁻¹) ≈ onRatioOrbit q`. -/
theorem canonical_cost_reciprocal_symmetric (q : RatioOrbit) :
    RatioOrbit.crossEq (onRatioOrbit q) (onRatioOrbit (RatioOrbit.recip q)) :=
  reciprocal_symmetric q

/-- The cost generated by any character `χ` has the rational display
    `J(χ(q)) = (χ(q) + χ(q)⁻¹)/2 − 1`. -/
theorem generated_cost_formula
    (χ : RatioOrbit → RatioOrbit) (q : RatioOrbit) :
    (costFromCharacter χ q).toRat =
      ((χ q).toRat + (χ q).toRat⁻¹) / 2 - 1 :=
  costFromCharacter_toRat χ q

/-! ## (c) Calibrated character-rigidity forces J -/

/-- **Calibrated forcing.** Any ratio character `χ` that is calibrated at a
    point `p` (i.e. `χ(p) ≈ p`) generates the canonical J-cost at `p`:
    `costFromCharacter χ p ≈ onRatioOrbit p = J(p)`. -/
theorem calibrated_character_forces_J
    (χ : RatioOrbit → RatioOrbit) (hχ : PRCRatioCharacter χ)
    (p : RatioOrbit) (hcalib : CharacterCalibratedAt χ p) :
    RatioOrbit.crossEq (costFromCharacter χ p) (onRatioOrbit p) :=
  costFromCharacter_rigid hχ hcalib

/-- **Calibration propagates.** If `χ` is calibrated at `p`, it is forced to
    be calibrated at `p²` and `p⁻¹` (so on the whole cyclic subgroup `p`
    generates), and the cost it generates at `p` is forced to `J(p)`. -/
theorem calibration_propagates_to_cyclic_subgroup
    (χ : RatioOrbit → RatioOrbit) (hχ : PRCRatioCharacter χ)
    (p : RatioOrbit) (hcalib : CharacterCalibratedAt χ p) :
    CharacterCalibratedAt χ (RatioOrbit.mul p p) ∧
    CharacterCalibratedAt χ (RatioOrbit.recip p) ∧
    RatioOrbit.crossEq (costFromCharacter χ p) (onRatioOrbit p) :=
  prime_calibration_forces_identity_on_direction hχ hcalib

/-! ## The capstone: forced J on the completion -/

/-- **THE CAPSTONE.** On the completion R_delta, the recognition laws
    (reciprocal-symmetric RCL + normalization + the single calibration datum)
    FORCE the cost to be the canonical `J(x) = (x + 1/x)/2 − 1`, unique up to
    the proved one-parameter gauge (the reciprocal symmetry of J).

    Specifically, for any `PRCRatioCharacter χ` calibrated at a point `p`:
    1. **Forcing:** the cost generated by `χ` at `p` is `J(p)`;
    2. **Gauge:** `J` is reciprocal-symmetric, so `χ = id` and `χ = recip`
       generate the same cost (the one-parameter gauge);
    3. **Propagation:** calibration at `p` forces calibration at `p²` and
       `p⁻¹` (the cyclic subgroup generated by `p`);
    4. **Formula:** `J(p) = (p + p⁻¹)/2 − 1` on the rational display.

    The completion R_delta itself is the named commitment (the continuum is
    NOT forced by distinction — see `RealLineNonNativity`). What is forced
    ON the completion is the cost `J`.

    The all-primes propagation — one-point calibration at `two` forcing
    global identity — is the named open target
    `target_OnePointCalibrationForcesGlobalIdentity`.

    This theorem is proved choice-free on the quotient-native carrier
    `RatioOrbit`. The field-display connection to `Cost.Jcost` on `ℝ`
    (from `PRCCostOnField`) is documented but not routed through this
    theorem, to avoid pulling `Classical.choice` into the capstone. -/
theorem forced_J_on_completion
    (χ : RatioOrbit → RatioOrbit) (hχ : PRCRatioCharacter χ)
    (p : RatioOrbit) (hcalib : CharacterCalibratedAt χ p) :
    -- 1. Forcing: the cost generated by χ at p is J(p)
    RatioOrbit.crossEq (costFromCharacter χ p) (onRatioOrbit p) ∧
    -- 2. Gauge: J is reciprocal-symmetric (J(p) ≈ J(p⁻¹))
    RatioOrbit.crossEq (onRatioOrbit p) (onRatioOrbit (RatioOrbit.recip p)) ∧
    -- 3. Propagation: calibration at p forces calibration at p² and p⁻¹
    CharacterCalibratedAt χ (RatioOrbit.mul p p) ∧
    CharacterCalibratedAt χ (RatioOrbit.recip p) ∧
    -- 4. Formula: J(p) = (p + p⁻¹)/2 − 1
    (onRatioOrbit p).toRat = (p.toRat + p.toRat⁻¹) / 2 - 1 :=
  ⟨costFromCharacter_rigid hχ hcalib,
   reciprocal_symmetric p,
   (prime_calibration_forces_identity_on_direction hχ hcalib).1,
   (prime_calibration_forces_identity_on_direction hχ hcalib).2.1,
   onRatioOrbit_toRat p⟩

/-! ## Existence of the forced cost on the completion -/

/-- **Existence of the forced cost.** The canonical cost `J` exists on the
    completion R_delta: it is the quotient-native `onRatioOrbit` on `RatioOrbit`,
    which computes `(q + q⁻¹)/2 − 1` on the rational display. The completion
    `PRCRealNullClosed` carries this cost via the rational embedding
    `PRCRealNullClosed.ofRat`, and the cost is closed under the countable
    field `T` (see `PRCCostOnField.jcost_mem_T`). -/
theorem forced_cost_exists_on_completion :
    ∃ (J : RatioOrbit → RatioOrbit),
      ∀ q : RatioOrbit,
        RatioOrbit.crossEq (J q) (J (RatioOrbit.recip q)) ∧
        J q = onRatioOrbit q :=
  ⟨onRatioOrbit, fun q => ⟨reciprocal_symmetric q, rfl⟩⟩

/-! ## The open all-primes target -/

/-- **Open target.** One-point calibration at `two` forces global identity:
    every `PRCRatioCharacter` calibrated at `two` is calibrated at every
    nonzero ratio orbit. This is the all-prime-directions statement that
    `PRCNativeCostUniqueness` leaves OPEN. The capstone above provides
    per-direction rigidity; propagating one-point calibration across
    independent prime directions is the remaining content. -/
def target_global_identity_from_one_point_calibration : Prop :=
  target_OnePointCalibrationForcesGlobalIdentity

/-! ## Field-display connection (documented; uses classical ℝ)

    The quotient-native cost `onRatioOrbit q` and the field-display cost
    `Cost.Jcost x` (from `PRCCostOnField`) agree on the rational display:
    both compute `(x + x⁻¹)/2 − 1`. The field-display step uses Mathlib's
    classical `ℝ` (via `Cost.Jcost`), which carries `Classical.choice`.
    It is documented here but NOT routed through the capstone theorem,
    which is proved choice-free on the quotient-native carrier `RatioOrbit`.

    The connection is:
    `Cost.Jcost q.toRat = (q.toRat + q.toRat⁻¹)/2 − 1 = (onRatioOrbit q).toRat`
    (by `unfold Cost.Jcost` in `PRCCostOnField` and `onRatioOrbit_toRat`).

    The countable field `T` from `PRCCostOnField` is closed under `Cost.Jcost`
    (see `jcost_mem_T`), so the cost dynamics stay countable. The constants
    π, φ, e, and α⁻¹ all live in `T` (see `cost_and_constants_share_one_countable_field`).
    The continuum is required nowhere in the cost-and-constants loop. -/

end IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.Continuum
