import Mathlib
import IndisputableMonolith.Cost

/-!
# The Universal Cost Spectrum

This module abstracts the prime cost spectrum framework from
`IndisputableMonolith.NumberTheory.PrimeCostSpectrum` and
`...PrimeCostSpectrumPoly` to a single abstract setting parameterized
by any "norm-equipped prime structure".

A `PrimeNormStructure P` consists of a type `P` (the "primes") together
with a real-valued norm `‖p‖ > 1` on each prime.  Both classical primes
in `ℕ` (with `‖p‖ = p`) and monic irreducibles in `Fq[T]` (with
`‖P‖ = q^deg P`) are instances.

For any such structure, we define the universal cost arithmetic function

  `c(f) := Σ_p f(p) · J(‖p‖)`

on finitely-supported functions `f : P →₀ ℕ` (representing elements of
the multiplicative monoid generated by `P`).  We prove the universal
elementary properties: `c(0) = 0`, `c(f + g) = c(f) + c(g)`, `c(f) ≥ 0`,
and `c(f) > 0` for `f ≠ 0`.

This module supports the Cost-Reciprocity synthesis paper, which argues
that all cost-spectrum constructions across the Selberg class of
L-functions are instances of this single abstract framework.

## Main definitions

* `PrimeNormStructure P`     : the typeclass of "primes with norm > 1".
* `primeJcost p`              : `J(‖p‖)`, the cost of an abstract prime.
* `universalCost f`           : the cost spectrum value on a Finsupp.

## Main theorems (all 0 sorry, 0 non-standard axioms)

* `primeJcost_pos`            : `0 < primeJcost p` for any `p`.
* `universalCost_zero`        : `c(0) = 0`.
* `universalCost_single`      : `c(single p k) = k · J(‖p‖)`.
* `universalCost_add`         : `c(f + g) = c(f) + c(g)`.
* `universalCost_nonneg`      : `0 ≤ c(f)`.
* `universalCost_pos`         : `f ≠ 0 → 0 < c(f)`.
* `universal_cost_certificate`: bundled certificate.

## Instances

* `Nat.Primes.instPrimeNormStructure` : integer primes, `‖p‖ = p`.

The function-field instance is parameterized by the field `F` and is
provided as a `def` rather than an `instance` (since it depends on `F`).

## Lean status: 0 sorry
-/

namespace IndisputableMonolith
namespace NumberTheory
namespace UniversalCostSpectrum

open Cost

noncomputable section

/-! ## The abstract structure -/

/-- A type `P` is a `PrimeNormStructure` if it carries a real-valued
    norm `‖·‖ > 1` on each element.  This abstracts away from the
    specific arithmetic structure (integer primes, monic irreducible
    polynomials, prime ideals in number fields, etc.). -/
class PrimeNormStructure (P : Type*) where
  norm : P → ℝ
  norm_gt_one : ∀ p : P, 1 < norm p

variable {P : Type*} [PrimeNormStructure P]

/-- The cost of an abstract prime: `J(‖p‖)`. -/
def primeJcost (p : P) : ℝ := Jcost (PrimeNormStructure.norm p)

/-- The cost of any prime is strictly positive. -/
theorem primeJcost_pos (p : P) : 0 < primeJcost p := by
  unfold primeJcost
  apply Jcost_pos_of_ne_one
  · linarith [PrimeNormStructure.norm_gt_one p]
  · linarith [PrimeNormStructure.norm_gt_one p]

theorem primeJcost_nonneg (p : P) : 0 ≤ primeJcost p :=
  le_of_lt (primeJcost_pos p)

/-! ## The universal cost spectrum value -/

variable [DecidableEq P]

/-- The universal cost spectrum value on `f : P →₀ ℕ`.

    Interpreting `f` as the multiplicity vector of an element of the
    multiplicative monoid generated by `P`, this is the cost-weighted
    sum `Σ_p f(p) · J(‖p‖)`. -/
def universalCost (f : P →₀ ℕ) : ℝ :=
  f.sum (fun p k => (k : ℝ) * primeJcost p)

@[simp] theorem universalCost_zero : universalCost (0 : P →₀ ℕ) = 0 := by
  simp [universalCost]

theorem universalCost_single (p : P) (k : ℕ) :
    universalCost (Finsupp.single p k) = (k : ℝ) * primeJcost p := by
  unfold universalCost
  simp [Finsupp.sum_single_index]

@[simp] theorem universalCost_single_one (p : P) :
    universalCost (Finsupp.single p 1) = primeJcost p := by
  rw [universalCost_single]
  ring

theorem universalCost_add (f g : P →₀ ℕ) :
    universalCost (f + g) = universalCost f + universalCost g := by
  unfold universalCost
  rw [Finsupp.sum_add_index']
  · intro p; simp
  · intro p i j; push_cast; ring

theorem universalCost_nonneg (f : P →₀ ℕ) : 0 ≤ universalCost f := by
  apply Finsupp.sum_nonneg
  intro p _
  apply mul_nonneg
  · exact_mod_cast Nat.zero_le _
  · exact primeJcost_nonneg p

theorem universalCost_pos {f : P →₀ ℕ} (hf : f ≠ 0) : 0 < universalCost f := by
  obtain ⟨p, hp_mem⟩ := Finsupp.support_nonempty_iff.mpr hf
  have hk_pos : 0 < f p := by
    have := Finsupp.mem_support_iff.mp hp_mem
    exact Nat.pos_of_ne_zero this
  have hJ_pos : 0 < primeJcost p := primeJcost_pos p
  have hsummand_pos : 0 < (f p : ℝ) * primeJcost p := by
    have hk_real : (0 : ℝ) < (f p : ℝ) := by exact_mod_cast hk_pos
    exact mul_pos hk_real hJ_pos
  unfold universalCost
  rw [Finsupp.sum, ← Finset.sum_erase_add _ _ hp_mem]
  apply add_pos_of_nonneg_of_pos
  · apply Finset.sum_nonneg
    intro q _
    apply mul_nonneg
    · exact_mod_cast Nat.zero_le _
    · exact primeJcost_nonneg q
  · exact hsummand_pos

/-! ## Power and multiplicative structure -/

/-- The cost of a power `n · single p 1`: `c(n · single p 1) = n · J(‖p‖)`.
    More generally, scaling a single-prime Finsupp scales the cost. -/
theorem universalCost_smul_single (n : ℕ) (p : P) :
    universalCost (n • Finsupp.single p 1) = (n : ℝ) * primeJcost p := by
  rw [show n • Finsupp.single p (1 : ℕ) = Finsupp.single p n by
        ext q; by_cases hpq : q = p
        · subst hpq; simp
        · simp [Finsupp.single_apply, hpq]]
  exact universalCost_single p n

/-! ## Universal certificate -/

/-- Master certificate: the elementary properties of the universal
    cost spectrum. -/
theorem universal_cost_certificate :
    -- (1) Every prime cost is strictly positive.
    (∀ (p : P), 0 < primeJcost p) ∧
    -- (2) Cost is zero at the trivial Finsupp (the unit element).
    (universalCost (0 : P →₀ ℕ) = 0) ∧
    -- (3) Cost is additive.
    (∀ (f g : P →₀ ℕ),
      universalCost (f + g) = universalCost f + universalCost g) ∧
    -- (4) Cost on a singleton: c(single p k) = k · J(‖p‖).
    (∀ (p : P) (k : ℕ),
      universalCost (Finsupp.single p k) = (k : ℝ) * primeJcost p) ∧
    -- (5) Cost is nonneg.
    (∀ (f : P →₀ ℕ), 0 ≤ universalCost f) ∧
    -- (6) Cost is strictly positive on non-trivial Finsupps.
    (∀ {f : P →₀ ℕ}, f ≠ 0 → 0 < universalCost f) :=
  ⟨primeJcost_pos,
   universalCost_zero,
   universalCost_add,
   universalCost_single,
   universalCost_nonneg,
   @universalCost_pos P _ _⟩

/-! ## Instance: Integer primes -/

instance natPrimesInstance : PrimeNormStructure Nat.Primes where
  norm := fun p => (p.val : ℝ)
  norm_gt_one := fun p => by exact_mod_cast p.prop.one_lt

example (p : Nat.Primes) : 0 < primeJcost p := primeJcost_pos p

/-! ## Function-field instance (parameterized) -/

/-- The function-field prime norm structure: monic irreducible polynomials
    in `F[X]` with norm `q^deg P` where `q = Fintype.card F`.  Parameterized
    by the field `F` (so it cannot be a global instance). -/
def funcFieldNormStructure (F : Type*) [Field F] [Fintype F]
    [DecidableEq F] (h2 : 2 ≤ Fintype.card F) :
    PrimeNormStructure {P : Polynomial F // P.Monic ∧ Irreducible P} where
  norm := fun P => (Fintype.card F : ℝ) ^ P.val.natDegree
  norm_gt_one := fun P => by
    have hP_irr : Irreducible P.val := P.prop.2
    have hP_ne : P.val ≠ 0 := hP_irr.ne_zero
    have hP_deg : 0 < P.val.natDegree := by
      rw [Nat.pos_iff_ne_zero]
      intro h_zero
      obtain ⟨c, hc⟩ := Polynomial.natDegree_eq_zero.mp h_zero
      have hc_ne : c ≠ 0 := by
        intro h_c_zero
        apply hP_ne
        rw [← hc, h_c_zero]; simp
      have hP_unit : IsUnit P.val := by
        rw [← hc]
        exact Polynomial.isUnit_C.mpr (isUnit_iff_ne_zero.mpr hc_ne)
      exact hP_irr.not_isUnit hP_unit
    have hq_real : (1 : ℝ) < (Fintype.card F : ℝ) := by exact_mod_cast h2
    exact one_lt_pow₀ hq_real (Nat.pos_iff_ne_zero.mp hP_deg)

end

end UniversalCostSpectrum
end NumberTheory
end IndisputableMonolith
