import IndisputableMonolith.Constants

/-!
# IndisputableMonolith (umbrella)

Lightweight root. The library is built via `globs` in the lakefile, so
`lake build IndisputableMonolith` compiles every shipped module as its own
target. Import specific modules, not this umbrella.
Regenerated by reality/scripts/sync_shape_of_logic.py — do not hand-edit.
-/
