import IndisputableMonolith.Foundation.UniversalForcing.MusicRealization

/-!
  NarrativeRealization.lean

  Lightweight narrative realization: the carrier is the beat count generated by
  an inciting event. This formalizes the structural claim that narrative order
  carries the same forced Peano object.
-/

namespace IndisputableMonolith
namespace Foundation
namespace UniversalForcing
namespace NarrativeRealization

open ArithmeticFromLogic
open Invariance.Universal

abbrev NarrativeBeat := Nat

def narrativeCost (a b : NarrativeBeat) : Nat :=
  if a = b then 0 else 1

@[simp] theorem narrativeCost_self (a : NarrativeBeat) : narrativeCost a a = 0 := by
  simp [narrativeCost]

theorem narrativeCost_symm (a b : NarrativeBeat) : narrativeCost a b = narrativeCost b a := by
  by_cases h : a = b
  · subst h; simp [narrativeCost]
  · have h' : b ≠ a := by intro hb; exact h hb.symm
    simp [narrativeCost, h, h']

def narrativeInterpret (n : LogicNat) : NarrativeBeat :=
  LogicNat.toNat n

/-- Narrative realization as beat-count comparison. -/
def narrativeRealization : LogicRealization where
  Carrier := NarrativeBeat
  Cost := Nat
  zeroCost := inferInstance
  compare := narrativeCost
  zero := 0
  step := Nat.succ
  Orbit := LogicNat
  orbitZero := LogicNat.zero
  orbitStep := LogicNat.succ
  interpret := narrativeInterpret
  interpret_zero := by rfl
  interpret_step := by
    intro n
    show LogicNat.toNat (LogicNat.succ n) = Nat.succ (LogicNat.toNat n)
    rfl
  orbit_no_confusion := by intro n h; exact LogicNat.zero_ne_succ n h
  orbit_step_injective := LogicNat.succ_injective
  orbit_induction := by
    intro P h0 hs n
    exact LogicNat.induction (motive := P) h0 hs n
  orbitEquivLogicNat := Equiv.refl LogicNat
  orbitEquiv_zero := rfl
  orbitEquiv_step := by intro n; rfl
  identity := narrativeCost_self
  nonContradiction := narrativeCost_symm
  excludedMiddle := True
  composition := True
  actionInvariant := True
  nontrivial := by
    refine ⟨1, ?_⟩
    simp [narrativeCost]

noncomputable def narrative_arith_equiv_nat :
    (arithmeticOf narrativeRealization).peano.carrier ≃ LogicNat :=
  narrativeRealization.orbitEquivLogicNat

end NarrativeRealization
end UniversalForcing
end Foundation
end IndisputableMonolith
