import Mathlib
import IndisputableMonolith.Foundation.RecognitionOperator
import IndisputableMonolith.Foundation.SchrodingerDerivation
import IndisputableMonolith.Foundation.ComplexStructureForcing

/-!
# Gravity IV: Ledger Superposition (Theorem 1) and Cost-Gradient Functoriality (Theorem 2)

This module supplies the formal anchors for two of the four load-bearing
theorems of the paper *Gravity from Recognition IV: The Quantum Channel*:

* **T1 (Ledger Superposition).**
  The recognition state space `Signal8` is a complex Hilbert carrier;
  the one-tick recognition update `cyclic_shift` is `ℂ`-linear and
  preserves the canonical `inner8` inner product. Therefore coherent
  superpositions of definite ledger configurations are physical states
  and are preserved by the recognition update.

* **T2 (Cost-Gradient Functoriality Under Superposition).**
  Any classical map `g : DensityConfig → GravityConfig` extends uniquely
  to a `ℂ`-linear operator on the free `ℂ`-modules generated by the
  basis sets, by the universal property of free linear extension. The
  physical content is the identification: in any extension of the
  linear ledger update from matter alone to matter-plus-gravitational-channel,
  the cost-gradient response must be the unique linear extension, not a
  nonlinear classical readout. The mathematical theorem is unconditional;
  the physical interpretation is tagged MODEL.

All proofs reuse `Foundation.SchrodingerDerivation`,
`Foundation.RecognitionOperator`, and `Foundation.ComplexStructureForcing`
without introducing new RS-internal axioms.
-/

namespace IndisputableMonolith
namespace Gravity
namespace LedgerSuperposition

open IndisputableMonolith.Spectral

noncomputable section

/-- Local abbreviation: the eight-tick analytic signal carrier
`Fin 8 → ℂ`, identified with the canonical
`Foundation.ComplexStructureForcing.Signal8`. -/
abbrev Signal8 : Type :=
  IndisputableMonolith.Foundation.ComplexStructureForcing.Signal8

/-- Local abbreviation: the canonical Hermitian inner product on
`Signal8`. -/
abbrev inner8 (f g : Signal8) : ℂ :=
  IndisputableMonolith.Foundation.ComplexStructureForcing.inner8 f g

/-! ## Theorem 1: Ledger Superposition -/

/-- **T1.i (Linearity).** The recognition update is `ℂ`-linear: it maps
linear combinations of ledger configurations to the corresponding linear
combinations of evolved configurations. This is
`SchrodingerDerivation.schrodinger_linear` repackaged in the ledger
superposition language. -/
theorem ledger_superposition_preserved
    (ψ φ : Signal8) (a b : ℂ) :
    cyclic_shift (a • ψ + b • φ) =
      a • cyclic_shift ψ + b • cyclic_shift φ :=
  IndisputableMonolith.Foundation.SchrodingerDerivation.schrodinger_linear ψ φ a b

/-- **T1.i (Finite-sum form).** For a finite family of definite ledger
configurations `L : ι → Signal8` and amplitudes `c : ι → ℂ` indexed by a
finite set, the recognition update commutes with the finite linear
combination. This is the explicit superposition principle for ledger
configurations: `R̂ Σ c_α |L_α⟩ = Σ c_α R̂ |L_α⟩`. -/
theorem ledger_superposition_finite_sum
    {ι : Type*} (s : Finset ι) (c : ι → ℂ) (L : ι → Signal8) :
    cyclic_shift (∑ α ∈ s, c α • L α) =
      ∑ α ∈ s, c α • cyclic_shift (L α) := by
  classical
  induction s using Finset.induction_on with
  | empty =>
      ext t
      simp [cyclic_shift]
  | @insert α s hα ih =>
      have hsum :
          (∑ β ∈ insert α s, c β • L β)
            = c α • L α + ∑ β ∈ s, c β • L β := by
        simp [Finset.sum_insert hα]
      rw [hsum,
          IndisputableMonolith.Foundation.SchrodingerDerivation.cyclic_shift_add,
          IndisputableMonolith.Foundation.SchrodingerDerivation.cyclic_shift_smul,
          ih]
      simp [Finset.sum_insert hα]

/-- **T1.iii (Inner-product preservation).** The recognition update
preserves the canonical `inner8` Hermitian inner product. The proof is
direct from the definitions of `inner8` and `cyclic_shift`: the cyclic
shift permutes the eight summands without changing the value of the
sum. -/
theorem recognition_update_inner_preserved (f g : Signal8) :
    inner8 (cyclic_shift f) (cyclic_shift g) = inner8 f g := by
  show IndisputableMonolith.Foundation.ComplexStructureForcing.inner8
      (cyclic_shift f) (cyclic_shift g)
      = IndisputableMonolith.Foundation.ComplexStructureForcing.inner8 f g
  unfold IndisputableMonolith.Foundation.ComplexStructureForcing.inner8 cyclic_shift
  rw [Fin.sum_univ_eight, Fin.sum_univ_eight]
  simp
  ring

/-- **T1.iii (Norm preservation).** As a corollary of inner-product
preservation, the recognition update preserves the `inner8`-norm
squared. -/
theorem recognition_update_norm_preserved (f : Signal8) :
    inner8 (cyclic_shift f) (cyclic_shift f) = inner8 f f :=
  recognition_update_inner_preserved f f

/-- **T1 master.** A complete witness that the recognition update is a
`ℂ`-linear, inner-product-preserving operator on the ledger Hilbert
carrier. This is the formal content of "ledger superpositions are
physical and are preserved by recognition evolution." -/
structure LedgerSuperpositionTheorem where
  /-- (i) Linearity on pairs. -/
  linearity :
    ∀ (ψ φ : Signal8) (a b : ℂ),
      cyclic_shift (a • ψ + b • φ) =
        a • cyclic_shift ψ + b • cyclic_shift φ
  /-- (i) Linearity on finite sums. -/
  linearity_sum :
    ∀ {ι : Type} (s : Finset ι) (c : ι → ℂ) (L : ι → Signal8),
      cyclic_shift (∑ α ∈ s, c α • L α) =
        ∑ α ∈ s, c α • cyclic_shift (L α)
  /-- (iii) Inner-product preservation. -/
  inner_preserved :
    ∀ f g : Signal8,
      inner8 (cyclic_shift f) (cyclic_shift g) = inner8 f g
  /-- (iii) Norm preservation. -/
  norm_preserved :
    ∀ f : Signal8, inner8 (cyclic_shift f) (cyclic_shift f) = inner8 f f

/-- The canonical inhabitant of `LedgerSuperpositionTheorem`. -/
def ledgerSuperpositionTheorem : LedgerSuperpositionTheorem where
  linearity := ledger_superposition_preserved
  linearity_sum := fun s c L => ledger_superposition_finite_sum s c L
  inner_preserved := recognition_update_inner_preserved
  norm_preserved := recognition_update_norm_preserved

theorem ledgerSuperpositionTheorem_inhabited :
    Nonempty LedgerSuperpositionTheorem :=
  ⟨ledgerSuperpositionTheorem⟩

/-! ## Theorem 2: Cost-Gradient Functoriality Under Superposition

The mathematical content is the universal property of free `ℂ`-modules:
any function on a basis extends uniquely to a `ℂ`-linear map on the free
`ℂ`-module generated by that basis. We package this as a generic
`linear_extension` theorem, applicable to any `DensityConfig → GravityConfig`
classical mass-density-to-cost-gradient map.

The physical interpretation that this linear extension *is* the
gravitational response operator on the ledger Hilbert span is a modeling
step (tagged MODEL in the paper); the mathematical extension is
unconditional.
-/

/-- The cost-gradient map seen as a function on definite ledger
configurations indexed by `ι` (mass densities), valued in
`Signal8`-spans indexed by `κ` (gravity configurations). In the BMV
two-mass two-branch setup, `ι = κ = Fin 4` indexing the four definite
branch states {LL, LR, RL, RR}. -/
abbrev DensityConfig (ι : Type*) := ι
abbrev GravityConfig (κ : Type*) := κ

/-- Free `ℂ`-module on a finite basis, used for the BMV two-qubit setup.
We identify `ι →₀ ℂ` with the finite `ℂ`-linear span of basis vectors
`{|α⟩ : α ∈ ι}`. -/
abbrev FreeC (ι : Type*) [DecidableEq ι] := ι →₀ ℂ

/-- **T2 (universal property of free linear extension).** Given any
classical map `g : ι → (κ →₀ ℂ)` from definite densities to definite
gravity configurations (or `ℂ`-combinations thereof), there exists a
canonical `ℂ`-linear map `ĝ : (ι →₀ ℂ) →ₗ[ℂ] (κ →₀ ℂ)` extending `g` in
the sense that `ĝ |α⟩ = g α` for every basis element `α : ι`. -/
def costGradientLinearExtension {ι κ : Type*} [DecidableEq ι]
    (g : ι → (κ →₀ ℂ)) : (ι →₀ ℂ) →ₗ[ℂ] (κ →₀ ℂ) :=
  Finsupp.lift (κ →₀ ℂ) ℂ ι g

/-- **T2 (basis identity).** The linear extension agrees with the
classical map on basis elements. -/
theorem costGradient_linear_basis {ι κ : Type*} [DecidableEq ι]
    (g : ι → (κ →₀ ℂ)) (α : ι) :
    costGradientLinearExtension g (Finsupp.single α (1 : ℂ)) = g α := by
  simp [costGradientLinearExtension]

/-- **T2 (linearity, addition).** The cost-gradient extension respects
addition; this is automatic because the extension is a `LinearMap`, but
the statement is recorded explicitly for use in T3. -/
theorem costGradient_linear_add {ι κ : Type*} [DecidableEq ι]
    (g : ι → (κ →₀ ℂ)) (x y : ι →₀ ℂ) :
    costGradientLinearExtension g (x + y) =
      costGradientLinearExtension g x + costGradientLinearExtension g y :=
  (costGradientLinearExtension g).map_add x y

/-- **T2 (linearity, scalar multiplication).** -/
theorem costGradient_linear_smul {ι κ : Type*} [DecidableEq ι]
    (g : ι → (κ →₀ ℂ)) (a : ℂ) (x : ι →₀ ℂ) :
    costGradientLinearExtension g (a • x) =
      a • costGradientLinearExtension g x :=
  (costGradientLinearExtension g).map_smul a x

/-- **T2 (uniqueness).** Any two `ℂ`-linear maps that agree on the
finsupp basis agree everywhere. This is the uniqueness half of the
universal property. -/
theorem costGradient_linear_unique {ι κ : Type*} [DecidableEq ι]
    (f₁ f₂ : (ι →₀ ℂ) →ₗ[ℂ] (κ →₀ ℂ))
    (h : ∀ α : ι, f₁ (Finsupp.single α (1 : ℂ)) = f₂ (Finsupp.single α (1 : ℂ))) :
    f₁ = f₂ := by
  apply Finsupp.lhom_ext'
  intro α
  apply LinearMap.ext
  intro c
  have h1 : Finsupp.single α c = c • Finsupp.single α (1 : ℂ) := by
    ext β
    by_cases hβ : β = α <;> simp [hβ]
  have hα := h α
  have step :
      f₁ (Finsupp.single α c) = f₂ (Finsupp.single α c) := by
    rw [h1, f₁.map_smul, f₂.map_smul, hα]
  show (f₁.comp (Finsupp.lsingle (R := ℂ) α)) c
        = (f₂.comp (Finsupp.lsingle (R := ℂ) α)) c
  simp [Finsupp.lsingle, step]

/-- **T2 master witness.** The complete content of cost-gradient
functoriality under superposition: existence (the explicit linear
extension), agreement on basis, and uniqueness. -/
structure CostGradientFunctoriality (ι κ : Type) [DecidableEq ι] where
  /-- Existence: the linear extension itself. -/
  extend : (ι → (κ →₀ ℂ)) → ((ι →₀ ℂ) →ₗ[ℂ] (κ →₀ ℂ))
  /-- Basis agreement: extension agrees with classical map on basis. -/
  basis_agreement :
    ∀ (g : ι → (κ →₀ ℂ)) (α : ι),
      extend g (Finsupp.single α (1 : ℂ)) = g α
  /-- Uniqueness on basis. -/
  unique_on_basis :
    ∀ (f₁ f₂ : (ι →₀ ℂ) →ₗ[ℂ] (κ →₀ ℂ)),
      (∀ α : ι, f₁ (Finsupp.single α (1 : ℂ)) = f₂ (Finsupp.single α (1 : ℂ))) →
        f₁ = f₂

/-- The canonical inhabitant of `CostGradientFunctoriality`. -/
def costGradientFunctoriality (ι κ : Type) [DecidableEq ι] :
    CostGradientFunctoriality ι κ where
  extend := costGradientLinearExtension
  basis_agreement := costGradient_linear_basis
  unique_on_basis := costGradient_linear_unique

theorem costGradientFunctoriality_inhabited (ι κ : Type) [DecidableEq ι] :
    Nonempty (CostGradientFunctoriality ι κ) :=
  ⟨costGradientFunctoriality ι κ⟩

end

end LedgerSuperposition
end Gravity
end IndisputableMonolith
