import IndisputableMonolith.Gravity.DiscreteVacuumEinstein

/-!
# Restricted Incidence Recovery

The unrestricted recovery predicate in `DiscreteVacuumEinstein` asks vertex
probes to recover an arbitrary edge-deficit vector.  That is too strong for
bulk 3D lattices, where there are generally more edge variables than vertex
probes.

This module states and proves the mathematically valid version: recovery and
separation on an explicitly declared geometric deficit subspace.
-/

namespace IndisputableMonolith
namespace Gravity
namespace RestrictedIncidenceRecovery

open Geometry.ReggeTriangulation3D
open Geometry.ReggeHessian3D
open Geometry.Triangulation3DConsistency
open Geometry.ReggeActionConcrete
open Geometry.ReggeActionSmoothness
open Geometry.ReggeActionFirstVariation
open DiscreteVacuumEinstein

noncomputable section

abbrev DeficitSubspace (K : Triangulation3D) := (Fin K.nE → ℝ) → Prop

def RestrictedIncidenceDeficitSeparating
    (K : Triangulation3D) (S : DeficitSubspace K) : Prop :=
  ∀ δ : Fin K.nE → ℝ,
    S δ →
    (∀ η : VertexPotential K,
      ∑ e : Fin K.nE, δ e * directionalLengthCoefficient K η e = 0) →
    δ = 0

def RestrictedIncidenceDeficitRecovering
    (K : Triangulation3D) (S : DeficitSubspace K) : Prop :=
  ∃ recover : Fin K.nE → Fin K.nV → ℝ,
    ∀ δ : Fin K.nE → ℝ, S δ →
      ∀ e : Fin K.nE,
        δ e =
          ∑ i : Fin K.nV,
            recover e i *
              (∑ e' : Fin K.nE,
                δ e' * directionalLengthCoefficient K
                  (fun j : Fin K.nV => if j = i then (1 : ℝ) else 0) e')

theorem restrictedIncidenceDeficitSeparating_of_recovering
    (K : Triangulation3D) (S : DeficitSubspace K)
    (hRecover : RestrictedIncidenceDeficitRecovering K S) :
    RestrictedIncidenceDeficitSeparating K S := by
  rcases hRecover with ⟨recover, hrecover⟩
  intro δ hS hpair
  funext e
  rw [hrecover δ hS e]
  apply Finset.sum_eq_zero
  intro i _
  rw [hpair (fun j : Fin K.nV => if j = i then (1 : ℝ) else 0)]
  ring

/-- The subspace generated by a chosen recovery matrix: by definition, its
elements are exactly those recovered from vertex-basis probes by that matrix. -/
def RecoverableDeficitSubspace
    (K : Triangulation3D) (recover : Fin K.nE → Fin K.nV → ℝ) :
    DeficitSubspace K :=
  fun δ =>
    ∀ e : Fin K.nE,
      δ e =
        ∑ i : Fin K.nV,
          recover e i *
            (∑ e' : Fin K.nE,
              δ e' * directionalLengthCoefficient K
                (fun j : Fin K.nV => if j = i then (1 : ℝ) else 0) e')

theorem restrictedRecovering_recoverableSubspace
    (K : Triangulation3D) (recover : Fin K.nE → Fin K.nV → ℝ) :
    RestrictedIncidenceDeficitRecovering K
      (RecoverableDeficitSubspace K recover) := by
  refine ⟨recover, ?_⟩
  intro δ hS e
  exact hS e

theorem restrictedSeparating_recoverableSubspace
    (K : Triangulation3D) (recover : Fin K.nE → Fin K.nV → ℝ) :
    RestrictedIncidenceDeficitSeparating K
      (RecoverableDeficitSubspace K recover) :=
  restrictedIncidenceDeficitSeparating_of_recovering K
    (RecoverableDeficitSubspace K recover)
    (restrictedRecovering_recoverableSubspace K recover)

/-- The geometric deficit subspace generated by conformal vertex-potential
edge-length directions.  This is the natural image of the incidence operator
`η ↦ directionalLengthCoefficient K η`. -/
def DirectionalLengthImageSubspace (K : Triangulation3D) : DeficitSubspace K :=
  fun δ => ∃ η : VertexPotential K,
    ∀ e : Fin K.nE, δ e = directionalLengthCoefficient K η e

theorem directionalLengthImageSubspace_separating
    (K : Triangulation3D) :
    RestrictedIncidenceDeficitSeparating K
      (DirectionalLengthImageSubspace K) := by
  intro δ hS hpair
  rcases hS with ⟨η, hη⟩
  have hsum :
      (∑ e : Fin K.nE,
        directionalLengthCoefficient K η e *
          directionalLengthCoefficient K η e) = 0 := by
    simpa [hη] using hpair η
  have hzero_all :
      ∀ e ∈ (Finset.univ : Finset (Fin K.nE)),
        directionalLengthCoefficient K η e *
          directionalLengthCoefficient K η e = 0 := by
    have hnonneg :
        ∀ x ∈ (Finset.univ : Finset (Fin K.nE)),
          0 ≤ directionalLengthCoefficient K η x *
            directionalLengthCoefficient K η x := by
      intro x _
      exact mul_self_nonneg _
    exact (Finset.sum_eq_zero_iff_of_nonneg hnonneg).mp hsum
  funext e
  have hsq := hzero_all e (Finset.mem_univ e)
  have hcoeff : directionalLengthCoefficient K η e = 0 := by
    exact mul_self_eq_zero.mp hsq
  change δ e = 0
  rw [hη e, hcoeff]

/-- Reverse vacuum implication restricted to a declared geometric deficit
subspace.  The actual deficit vector must be shown to belong to the subspace. -/
theorem zero_deficit_of_critical_of_restrictedVariationFormula
    (K : Triangulation3D) (hK : IncidenceConsistent K)
    (S : DeficitSubspace K)
    (hDeficitInS : S (fun e : Fin K.nE => deficitAngle K (zeroPotential K) e))
    (hFormula : ReggeFirstVariationFormula K hK)
    (hSep : RestrictedIncidenceDeficitSeparating K S)
    (hCrit : CriticalAtFlat K hK) :
    ZeroDeficitAtFlat K := by
  unfold CriticalAtFlat ReggeActionCriticalAtZero at hCrit
  unfold ZeroDeficitAtFlat
  have hdelta :
      (fun e : Fin K.nE => deficitAngle K (zeroPotential K) e) = 0 := by
    apply hSep
    · exact hDeficitInS
    · intro η
      have happly := congrArg (fun L : VertexPotential K →L[ℝ] ℝ => L η) hCrit
      have hzero :
          (fderiv ℝ (reggeAction K hK) (zeroPotential K)) η = 0 := by
        simpa using happly
      have hformula := hFormula.variation_formula η
      rw [hformula] at hzero
      simpa using hzero
  intro e
  exact congrFun hdelta e

def discreteVacuumEinsteinInput_of_restrictedRecovery
    (K : Triangulation3D) (hK : IncidenceConsistent K)
    (h_flat : FlatConfiguration K hK)
    (hFirst : ReggeActionFirstVariationInput K hK h_flat)
    (S : DeficitSubspace K)
    (hDeficitInS : S (fun e : Fin K.nE => deficitAngle K (zeroPotential K) e))
    (hFormula : ReggeFirstVariationFormula K hK)
    (hSep : RestrictedIncidenceDeficitSeparating K S) :
    DiscreteVacuumEinsteinInput K hK h_flat where
  critical_iff_zero_deficit := by
    constructor
    · intro hCrit
      exact zero_deficit_of_critical_of_restrictedVariationFormula
        K hK S hDeficitInS hFormula hSep hCrit
    · intro _hZero
      exact hFirst.firstVariation_zero

end

end RestrictedIncidenceRecovery
end Gravity
end IndisputableMonolith
