import Mathlib

/-!
# Triple-core oracle: Bernstein factor lemmas (GENERATED — do not edit)

Generated by `scripts/erdos132/_gen_triple_oracle.py`.  One `facNE_k`
lemma per distinct univariate RHS factor appearing in the 1654 triple-core
ideal-membership certificates: a Bernstein positivity witness
`s·f(x) = x^p (1-x)^q Σ γᵢ x^i (1-x)^(d-i)` with all `γᵢ > 0` proves
`f(x) ≠ 0` on `0 < x < 1` by an explicit `mul_pos`/`add_pos`/`pow_pos`
chain.  No `nlinarith`, no `polyrith`.
-/

namespace Erdos132.TripleOracle

theorem facNE_0 (x : ℝ) (h0 : 0 < x) (h1 : x < 1) :
    (2) * x ^ 2 + (-2) * x + (1) ≠ (0:ℝ) := by
  have hx : (0:ℝ) < 1 - x := by linarith
  have hsum : (0:ℝ) < (1) * x ^ 0 * (1 - x) ^ 3 + (1) * x ^ 1 * (1 - x) ^ 2 + (1) * x ^ 2 * (1 - x) ^ 1 + (1) * x ^ 3 * (1 - x) ^ 0 :=
    (add_pos (add_pos (add_pos (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 0)) (pow_pos hx 3)) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 1)) (pow_pos hx 2))) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 2)) (pow_pos hx 1))) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 3)) (pow_pos hx 0)))
  have hpos : (0:ℝ) < x ^ 0 * (1 - x) ^ 0 * ((1) * x ^ 0 * (1 - x) ^ 3 + (1) * x ^ 1 * (1 - x) ^ 2 + (1) * x ^ 2 * (1 - x) ^ 1 + (1) * x ^ 3 * (1 - x) ^ 0) :=
    mul_pos (mul_pos (pow_pos h0 0) (pow_pos hx 0)) hsum
  intro hz
  have hzero : x ^ 0 * (1 - x) ^ 0 * ((1) * x ^ 0 * (1 - x) ^ 3 + (1) * x ^ 1 * (1 - x) ^ 2 + (1) * x ^ 2 * (1 - x) ^ 1 + (1) * x ^ 3 * (1 - x) ^ 0) = 0 := by linear_combination (1) * hz
  exact absurd hzero (ne_of_gt hpos)

theorem facNE_1 (x : ℝ) (h0 : 0 < x) (h1 : x < 1) :
    (2) * x + (1) ≠ (0:ℝ) := by
  have hx : (0:ℝ) < 1 - x := by linarith
  have hsum : (0:ℝ) < (1) * x ^ 0 * (1 - x) ^ 1 + (3) * x ^ 1 * (1 - x) ^ 0 :=
    (add_pos (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 0)) (pow_pos hx 1)) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (3)) (pow_pos h0 1)) (pow_pos hx 0)))
  have hpos : (0:ℝ) < x ^ 0 * (1 - x) ^ 0 * ((1) * x ^ 0 * (1 - x) ^ 1 + (3) * x ^ 1 * (1 - x) ^ 0) :=
    mul_pos (mul_pos (pow_pos h0 0) (pow_pos hx 0)) hsum
  intro hz
  have hzero : x ^ 0 * (1 - x) ^ 0 * ((1) * x ^ 0 * (1 - x) ^ 1 + (3) * x ^ 1 * (1 - x) ^ 0) = 0 := by linear_combination (1) * hz
  exact absurd hzero (ne_of_gt hpos)

theorem facNE_2 (x : ℝ) (h0 : 0 < x) (h1 : x < 1) :
    (1) * x ^ 2 + (-3) * x + (-1) ≠ (0:ℝ) := by
  have hx : (0:ℝ) < 1 - x := by linarith
  have hsum : (0:ℝ) < (1) * x ^ 0 * (1 - x) ^ 2 + (5) * x ^ 1 * (1 - x) ^ 1 + (3) * x ^ 2 * (1 - x) ^ 0 :=
    (add_pos (add_pos (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 0)) (pow_pos hx 2)) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (5)) (pow_pos h0 1)) (pow_pos hx 1))) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (3)) (pow_pos h0 2)) (pow_pos hx 0)))
  have hpos : (0:ℝ) < x ^ 0 * (1 - x) ^ 0 * ((1) * x ^ 0 * (1 - x) ^ 2 + (5) * x ^ 1 * (1 - x) ^ 1 + (3) * x ^ 2 * (1 - x) ^ 0) :=
    mul_pos (mul_pos (pow_pos h0 0) (pow_pos hx 0)) hsum
  intro hz
  have hzero : x ^ 0 * (1 - x) ^ 0 * ((1) * x ^ 0 * (1 - x) ^ 2 + (5) * x ^ 1 * (1 - x) ^ 1 + (3) * x ^ 2 * (1 - x) ^ 0) = 0 := by linear_combination (-1) * hz
  exact absurd hzero (ne_of_gt hpos)

theorem facNE_3 (x : ℝ) (h0 : 0 < x) (h1 : x < 1) :
    (1) * x ^ 2 + (-5) * x + (5) ≠ (0:ℝ) := by
  have hx : (0:ℝ) < 1 - x := by linarith
  have hsum : (0:ℝ) < (5) * x ^ 0 * (1 - x) ^ 2 + (5) * x ^ 1 * (1 - x) ^ 1 + (1) * x ^ 2 * (1 - x) ^ 0 :=
    (add_pos (add_pos (mul_pos (mul_pos (by norm_num : (0:ℝ) < (5)) (pow_pos h0 0)) (pow_pos hx 2)) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (5)) (pow_pos h0 1)) (pow_pos hx 1))) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 2)) (pow_pos hx 0)))
  have hpos : (0:ℝ) < x ^ 0 * (1 - x) ^ 0 * ((5) * x ^ 0 * (1 - x) ^ 2 + (5) * x ^ 1 * (1 - x) ^ 1 + (1) * x ^ 2 * (1 - x) ^ 0) :=
    mul_pos (mul_pos (pow_pos h0 0) (pow_pos hx 0)) hsum
  intro hz
  have hzero : x ^ 0 * (1 - x) ^ 0 * ((5) * x ^ 0 * (1 - x) ^ 2 + (5) * x ^ 1 * (1 - x) ^ 1 + (1) * x ^ 2 * (1 - x) ^ 0) = 0 := by linear_combination (1) * hz
  exact absurd hzero (ne_of_gt hpos)

theorem facNE_4 (x : ℝ) (h0 : 0 < x) (h1 : x < 1) :
    (1) * x ^ 2 + (-1) * x + (1) ≠ (0:ℝ) := by
  have hx : (0:ℝ) < 1 - x := by linarith
  have hsum : (0:ℝ) < (1) * x ^ 0 * (1 - x) ^ 2 + (1) * x ^ 1 * (1 - x) ^ 1 + (1) * x ^ 2 * (1 - x) ^ 0 :=
    (add_pos (add_pos (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 0)) (pow_pos hx 2)) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 1)) (pow_pos hx 1))) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 2)) (pow_pos hx 0)))
  have hpos : (0:ℝ) < x ^ 0 * (1 - x) ^ 0 * ((1) * x ^ 0 * (1 - x) ^ 2 + (1) * x ^ 1 * (1 - x) ^ 1 + (1) * x ^ 2 * (1 - x) ^ 0) :=
    mul_pos (mul_pos (pow_pos h0 0) (pow_pos hx 0)) hsum
  intro hz
  have hzero : x ^ 0 * (1 - x) ^ 0 * ((1) * x ^ 0 * (1 - x) ^ 2 + (1) * x ^ 1 * (1 - x) ^ 1 + (1) * x ^ 2 * (1 - x) ^ 0) = 0 := by linear_combination (1) * hz
  exact absurd hzero (ne_of_gt hpos)

theorem facNE_5 (x : ℝ) (h0 : 0 < x) (h1 : x < 1) :
    (1) * x + (-1) ≠ (0:ℝ) := by
  have hx : (0:ℝ) < 1 - x := by linarith
  have hsum : (0:ℝ) < (1) * x ^ 0 * (1 - x) ^ 0 :=
    (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 0)) (pow_pos hx 0))
  have hpos : (0:ℝ) < x ^ 0 * (1 - x) ^ 1 * ((1) * x ^ 0 * (1 - x) ^ 0) :=
    mul_pos (mul_pos (pow_pos h0 0) (pow_pos hx 1)) hsum
  intro hz
  have hzero : x ^ 0 * (1 - x) ^ 1 * ((1) * x ^ 0 * (1 - x) ^ 0) = 0 := by linear_combination (-1) * hz
  exact absurd hzero (ne_of_gt hpos)

theorem facNE_6 (x : ℝ) (h0 : 0 < x) (h1 : x < 1) :
    (1) * x + (-2) ≠ (0:ℝ) := by
  have hx : (0:ℝ) < 1 - x := by linarith
  have hsum : (0:ℝ) < (2) * x ^ 0 * (1 - x) ^ 1 + (1) * x ^ 1 * (1 - x) ^ 0 :=
    (add_pos (mul_pos (mul_pos (by norm_num : (0:ℝ) < (2)) (pow_pos h0 0)) (pow_pos hx 1)) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 1)) (pow_pos hx 0)))
  have hpos : (0:ℝ) < x ^ 0 * (1 - x) ^ 0 * ((2) * x ^ 0 * (1 - x) ^ 1 + (1) * x ^ 1 * (1 - x) ^ 0) :=
    mul_pos (mul_pos (pow_pos h0 0) (pow_pos hx 0)) hsum
  intro hz
  have hzero : x ^ 0 * (1 - x) ^ 0 * ((2) * x ^ 0 * (1 - x) ^ 1 + (1) * x ^ 1 * (1 - x) ^ 0) = 0 := by linear_combination (-1) * hz
  exact absurd hzero (ne_of_gt hpos)

theorem facNE_7 (x : ℝ) (h0 : 0 < x) (h1 : x < 1) :
    (1) * x + (-3) ≠ (0:ℝ) := by
  have hx : (0:ℝ) < 1 - x := by linarith
  have hsum : (0:ℝ) < (3) * x ^ 0 * (1 - x) ^ 1 + (2) * x ^ 1 * (1 - x) ^ 0 :=
    (add_pos (mul_pos (mul_pos (by norm_num : (0:ℝ) < (3)) (pow_pos h0 0)) (pow_pos hx 1)) (mul_pos (mul_pos (by norm_num : (0:ℝ) < (2)) (pow_pos h0 1)) (pow_pos hx 0)))
  have hpos : (0:ℝ) < x ^ 0 * (1 - x) ^ 0 * ((3) * x ^ 0 * (1 - x) ^ 1 + (2) * x ^ 1 * (1 - x) ^ 0) :=
    mul_pos (mul_pos (pow_pos h0 0) (pow_pos hx 0)) hsum
  intro hz
  have hzero : x ^ 0 * (1 - x) ^ 0 * ((3) * x ^ 0 * (1 - x) ^ 1 + (2) * x ^ 1 * (1 - x) ^ 0) = 0 := by linear_combination (-1) * hz
  exact absurd hzero (ne_of_gt hpos)

theorem facNE_8 (x : ℝ) (h0 : 0 < x) (h1 : x < 1) :
    (1) * x ≠ (0:ℝ) := by
  have hx : (0:ℝ) < 1 - x := by linarith
  have hsum : (0:ℝ) < (1) * x ^ 0 * (1 - x) ^ 0 :=
    (mul_pos (mul_pos (by norm_num : (0:ℝ) < (1)) (pow_pos h0 0)) (pow_pos hx 0))
  have hpos : (0:ℝ) < x ^ 1 * (1 - x) ^ 0 * ((1) * x ^ 0 * (1 - x) ^ 0) :=
    mul_pos (mul_pos (pow_pos h0 1) (pow_pos hx 0)) hsum
  intro hz
  have hzero : x ^ 1 * (1 - x) ^ 0 * ((1) * x ^ 0 * (1 - x) ^ 0) = 0 := by linear_combination (1) * hz
  exact absurd hzero (ne_of_gt hpos)

/-! ## Coefficient-sensitivity negative control

A factor with an interior root is genuinely NOT certifiable by this
machinery: `x - 1/2` vanishes at `x = 1/2`, so a `facNE`-style lemma for
it would be FALSE.  The factor lemmas depend on root-freeness on (0,1),
not on a vacuous pattern. -/
example : ∃ x : ℝ, 0 < x ∧ x < 1 ∧ x - 1/2 = 0 :=
  ⟨1/2, by norm_num, by norm_num, by norm_num⟩

-- Axiom audit: every lemma must be exactly [propext, Classical.choice, Quot.sound].
#print axioms facNE_0
#print axioms facNE_1
#print axioms facNE_2
#print axioms facNE_3
#print axioms facNE_4
#print axioms facNE_5
#print axioms facNE_6
#print axioms facNE_7
#print axioms facNE_8

end Erdos132.TripleOracle
