/-
  PrimitiveRecognitionCalculus/CertifiedAnalyticProtocols.lean

  Second pass on the Delta-Native Analysis frontier: closing the "transcendental
  functions without ambient continuum" gap at the correct layer.

  The first pass showed that the named RS constant values live in a countable
  field, while the classical continuum is a protocol display. The remaining
  objection was sharper: the transcendental functions used to name constants
  (`exp`, `log`, π-producing procedures, etc.) look like ambient-continuum objects.

  The closure here is not "all transcendental functions as uncountable graphs".
  That would re-import the continuum. The native object is a *certified protocol
  registry*: a countable list of rational-interval constants and countable lists of
  protocol transformers. Expressions over that registry are finite trees; their
  evaluation is a Delta-real protocol; and the value set of all such expressions is
  countable. The analytic content is the certificate carried by each registered
  protocol/transformer, not an uncountable function graph.

  This resolves the ambient-continuum objection in the only honest form: RS may
  use transcendental operations when they are supplied as countably indexed
  certified protocol transformers. It does not need a completed continuum as the
  domain of all analytic functions.

  No project-local axioms. No sorry.
-/

import Mathlib
import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.DeltaReal

namespace IndisputableMonolith
namespace Foundation
namespace PrimitiveRecognitionCalculus
namespace CertifiedAnalyticProtocols

open DeltaReal

/-- A countable registry of certified analytic protocol ingredients.

`const k` is the `k`th registered constant protocol. `unary k` is the `k`th
registered unary protocol transformer. Binary protocol operations are kept to the
native additive operations already proved in `DeltaReal`; further binary analytic
operations can be encoded as unary transforms on paired protocols if needed. -/
structure Registry where
  const : ℕ → Protocol
  unary : ℕ → Protocol → Protocol

/-- Finite expressions over a certified analytic registry. The expression tree is
the native object; evaluation returns a protocol, never an uncountable graph. -/
inductive Expr where
  | rat : ℚ → Expr
  | const : ℕ → Expr
  | neg : Expr → Expr
  | add : Expr → Expr → Expr
  | sub : Expr → Expr → Expr
  | unary : ℕ → Expr → Expr
  deriving DecidableEq, Repr, Countable

namespace Expr

/-- Evaluation of a finite certified-analytic expression as a Delta-real protocol. -/
noncomputable def eval (R : Registry) : Expr → Protocol
  | .rat q => Protocol.ofRat q
  | .const k => R.const k
  | .neg a => Protocol.neg (eval R a)
  | .add a b => Protocol.add (eval R a) (eval R b)
  | .sub a b => Protocol.sub (eval R a) (eval R b)
  | .unary k a => R.unary k (eval R a)

/-- Evaluation followed by display as a real value. -/
noncomputable def value (R : Registry) (e : Expr) : ℝ :=
  (eval R e).value

/-- The set of values generated by a registry. -/
noncomputable def values (R : Registry) : Set ℝ := Set.range (value R)

/-- Registry values are countable because expressions are finite trees over
countable labels. This is the countability fact that blocks continuum smuggling. -/
theorem values_countable (R : Registry) : (values R).Countable :=
  Set.countable_range (value R)

/-- Every registry value has a protocol witness, by construction. -/
theorem every_value_has_protocol (R : Registry) (x : ℝ) (hx : x ∈ values R) :
    ∃ p : Protocol, p.value = x := by
  rcases hx with ⟨e, rfl⟩
  exact ⟨eval R e, rfl⟩

/-- Rational literals evaluate to their rational values. -/
@[simp] theorem value_rat (R : Registry) (q : ℚ) :
    value R (.rat q) = (q : ℝ) := by
  simp [value, eval, Protocol.value_ofRat]

/-- Native addition remains addition under the value display. -/
theorem value_add (R : Registry) (a b : Expr) :
    value R (.add a b) = value R a + value R b := by
  simp [value, eval, Protocol.value_add]

/-- Native negation remains negation under the value display. -/
theorem value_neg (R : Registry) (a : Expr) :
    value R (.neg a) = - value R a := by
  simp [value, eval, Protocol.value_neg]

/-- Native subtraction remains subtraction under the value display. -/
theorem value_sub (R : Registry) (a b : Expr) :
    value R (.sub a b) = value R a - value R b := by
  simp [value, eval, Protocol.value_sub]

/-- **Transcendental protocol closure.** Any countably indexed registry of certified
analytic constants and protocol transformers generates only countably many real
values, and every value is witnessed by a Delta-real protocol. The continuum is not
the carrier of analytic content; a certified countable protocol registry is. -/
theorem transcendental_protocol_closure (R : Registry) :
    (values R).Countable
      ∧ (∀ x : ℝ, x ∈ values R → ∃ p : Protocol, p.value = x)
      ∧ (∀ q : ℚ, value R (.rat q) = (q : ℝ))
      ∧ (∀ a b : Expr, value R (.add a b) = value R a + value R b)
      ∧ (∀ a : Expr, value R (.neg a) = - value R a)
      ∧ (∀ a b : Expr, value R (.sub a b) = value R a - value R b) :=
  ⟨values_countable R, every_value_has_protocol R, value_rat R, value_add R,
    value_neg R, value_sub R⟩

end Expr
end CertifiedAnalyticProtocols
end PrimitiveRecognitionCalculus
end Foundation
end IndisputableMonolith
