/-
  PrimitiveRecognitionCalculus/GenerableReal.lean

  Phase 2 of the Delta-Native Analysis frontier: the generable reals.

  The protocol-reals of `DeltaReal` are the analysis interface, and their value
  map lands onto all of ℝ (`Protocol.value_surjective`). That surjection is the
  display: the full classical continuum is reachable as protocol values. But the
  ontology physics actually uses is smaller. The generable reals are the ones
  produced from a countable family of named constants by the field operations.
  They are countable, hence a proper subset of ℝ.

  This is the anti-smuggling guard. It pins exactly where uncountability is a
  formal display artifact (the protocol value map onto ℝ) and where finite
  generation lives (the countable generable field).

  What is proved (relative to a countable constant family `κ : ℕ → ℝ`):

  * `genField_countable` : the generable reals are countable;
  * `rat_mem`, `const_mem` : ℚ and every named constant are generable;
  * closure under `+`, `-`, `*`, `⁻¹` (the field operations RS uses);
  * `genField_proper` : the generable reals are a proper subset of ℝ;
  * `display_exceeds_generation` : THE guard. There is a real that is a protocol
    value (reachable by the analysis display) yet not generable. The continuum the
    display reaches strictly exceeds the countable ontology, so any apparent need
    for uncountably many reals is display, not generation.

  Reuses `MinimalField.subfield_closure_countable_of_countable` and
  `DeltaReal.Protocol.value_surjective`.

  No project-local axioms. No sorry.
-/

import Mathlib
import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.PRCMinimalField
import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.DeltaReal

namespace IndisputableMonolith
namespace Foundation
namespace PrimitiveRecognitionCalculus
namespace GenerableReal

/-- The generable reals relative to a countable family of named constants `κ`:
the subfield of ℝ generated by the constants. Equivalently, everything obtainable
from the constants and rationals by finitely many field operations. -/
noncomputable def genField (κ : ℕ → ℝ) : Subfield ℝ := Subfield.closure (Set.range κ)

/-- The generable reals are countable: only countably many finite descriptions
exist. -/
theorem genField_countable (κ : ℕ → ℝ) : (genField κ : Set ℝ).Countable :=
  MinimalField.subfield_closure_countable_of_countable (Set.countable_range κ)

/-- Every rational is generable (the prime field sits inside). -/
theorem rat_mem (κ : ℕ → ℝ) (q : ℚ) : (q : ℝ) ∈ genField κ :=
  SubfieldClass.ratCast_mem (genField κ) q

/-- Every named constant is generable. -/
theorem const_mem (κ : ℕ → ℝ) (n : ℕ) : κ n ∈ genField κ :=
  Subfield.subset_closure ⟨n, rfl⟩

/-- The generable reals are a proper subset of ℝ: countability rules out the whole
continuum. -/
theorem genField_proper (κ : ℕ → ℝ) : (genField κ : Set ℝ) ≠ Set.univ := by
  intro h
  exact Cardinal.not_countable_real (h ▸ genField_countable κ)

/-- **Phase 2 headline: display exceeds generation.** For any countable constant
family, there is a real that is the value of a Delta-real protocol (so the
analysis display reaches it) yet is not generable. The protocol value map lands
onto the full continuum, while the ontology is the countable generable field; the
gap is exactly the reals that exist only as display, never as finite generation.
This is the guard against smuggling uncountable ontology in through the analysis
interface. -/
theorem display_exceeds_generation (κ : ℕ → ℝ) :
    ∃ r : ℝ, (∃ x : DeltaReal.Protocol, x.value = r) ∧ r ∉ genField κ := by
  obtain ⟨r, hr⟩ := (Set.ne_univ_iff_exists_notMem _).mp (genField_proper κ)
  exact ⟨r, DeltaReal.Protocol.value_surjective r, hr⟩

/-- The generable field is closed under the field operations and contains the
rationals and the named constants: it is a genuine operational carrier, not a bare
set. -/
theorem genField_is_operational_carrier (κ : ℕ → ℝ) :
    (∀ q : ℚ, (q : ℝ) ∈ genField κ)
      ∧ (∀ n : ℕ, κ n ∈ genField κ)
      ∧ (∀ a b : ℝ, a ∈ genField κ → b ∈ genField κ → a + b ∈ genField κ)
      ∧ (∀ a b : ℝ, a ∈ genField κ → b ∈ genField κ → a * b ∈ genField κ)
      ∧ (∀ a : ℝ, a ∈ genField κ → -a ∈ genField κ)
      ∧ (∀ a : ℝ, a ∈ genField κ → a⁻¹ ∈ genField κ)
      ∧ (genField κ : Set ℝ).Countable :=
  ⟨rat_mem κ, const_mem κ,
    fun _ _ ha hb => add_mem ha hb, fun _ _ ha hb => mul_mem ha hb,
    fun _ ha => neg_mem ha, fun _ ha => inv_mem ha, genField_countable κ⟩

end GenerableReal
end PrimitiveRecognitionCalculus
end Foundation
end IndisputableMonolith
