/-
  PrimitiveRecognitionCalculus/PRCExpLogField.lean

  Item 1 of the δ frontier, the deep half: the *construction*, not just the
  *values*, never needs the continuum.

  `PRCMinimalField` proved the named RS constant values live in a countable
  subfield of ℝ. That leaves an honest residual: the constants are not given as
  bare values, they are *built* by the operations

      +, −, ×, ÷, exp, log

  applied to ℚ, π, and φ. For example

      α⁻¹ = 44·π·exp( − w₈·ln φ / (44·π) ).

  A reasonable objection is that even if the answers are countable, the
  *definitional closure* under those operations might force the uncountable line:
  `exp` and `log` are analytic functions on ℝ. This module closes that objection.

  We build the smallest subfield of ℝ that contains ℚ, π, φ AND is closed under
  `exp` and `log`, as the union of an increasing chain

      S₀ = ℚ(π, φ),   S_{n+1} = ℚ( S_n ∪ exp(S_n) ∪ log(S_n) ).

  Each stage is a subfield generated by a countable set, hence countable; the
  union of the directed chain is a subfield (`Subfield.mem_iSup_of_directed`),
  countable (`Set.countable_iUnion`), closed under `exp` and `log` by
  construction, and a proper subset of ℝ (the continuum is uncountable).

  The headline `rs_operations_below_continuum` then exhibits ONE countable field
  `T` that is closed under exactly the operations the RS constants are built from
  and that already contains π, φ, e, and α⁻¹. Every step of every RS constant's
  definition can be carried out inside `T`; the construction never has to reach
  outside a countable structure.

  HONEST BOUNDARY (the only residual that survives). `Real.exp` and `Real.log` are
  here the standard Mathlib functions, whose *type* is ℝ → ℝ. We do not rebuild
  analysis over a countable model; we show the orbit of the RS generators under
  those functions is countable and field-closed. The remaining philosophical step,
  giving `exp`/`log` themselves a definition with no uncountable ambient (a fully
  constructive/computable analysis), is outside this framework and outside RS. What
  is eliminated here is the claim that the continuum is needed as the *workspace*
  of the construction: it is not; a single countable exp/log-closed field suffices.

  No project-local axioms. No sorry.
-/

import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.PRCMinimalField

namespace IndisputableMonolith
namespace Foundation
namespace PrimitiveRecognitionCalculus
namespace ExpLogField

/-- The generators of the exp/log closure: π and φ. Rationals come for free as the
prime field of any subfield, so these two transcendental/algebraic seeds plus the
field and exp/log operations reach every RS constant. -/
noncomputable def gens : Set ℝ := {Real.pi, Real.goldenRatio}

theorem gens_finite : gens.Finite := by
  unfold gens
  exact (Set.finite_singleton _).insert _

/-- One stage of the construction: adjoin the images of the current field under
`exp` and `log`, then take the subfield they generate. -/
noncomputable def Sstep (K : Subfield ℝ) : Subfield ℝ :=
  Subfield.closure ((K : Set ℝ) ∪ Real.exp '' (K : Set ℝ) ∪ Real.log '' (K : Set ℝ))

/-- The increasing chain of stages. -/
noncomputable def S : ℕ → Subfield ℝ
  | 0 => Subfield.closure gens
  | (n + 1) => Sstep (S n)

/-- Each stage embeds in the next: the chain is increasing. -/
theorem S_mono (n : ℕ) : S n ≤ S (n + 1) := by
  have hsub : (S n : Set ℝ) ⊆ (S (n + 1) : Set ℝ) := by
    intro x hx
    have : x ∈ Sstep (S n) := Subfield.subset_closure (Or.inl (Or.inl hx))
    exact this
  exact SetLike.coe_subset_coe.mp hsub

theorem S_monotone : Monotone S := monotone_nat_of_le_succ S_mono

theorem S_directed : Directed (· ≤ ·) S := S_monotone.directed_le

/-- Every stage is countable: a subfield generated by a countable set. -/
theorem S_countable (n : ℕ) : (S n : Set ℝ).Countable := by
  induction n with
  | zero =>
      show (Subfield.closure gens : Set ℝ).Countable
      exact MinimalField.subfield_closure_countable_of_finite gens_finite
  | succ n ih =>
      have hc :
          ((S n : Set ℝ) ∪ Real.exp '' (S n : Set ℝ) ∪ Real.log '' (S n : Set ℝ)).Countable :=
        (ih.union (ih.image Real.exp)).union (ih.image Real.log)
      exact MinimalField.subfield_closure_countable_of_countable hc

/-- **The exp/log-closed RS field.** The union of the directed chain. -/
noncomputable def T : Subfield ℝ := ⨆ n, S n

theorem mem_T_iff {x : ℝ} : x ∈ T ↔ ∃ n, x ∈ S n :=
  Subfield.mem_iSup_of_directed S_directed

theorem T_coe : (T : Set ℝ) = ⋃ n, (S n : Set ℝ) :=
  Subfield.coe_iSup_of_directed S_directed

/-- `T` is countable: a countable union of countable stages. -/
theorem T_countable : (T : Set ℝ).Countable := by
  rw [T_coe]
  exact Set.countable_iUnion S_countable

/-- `T` is closed under `exp`. -/
theorem T_exp_closed {x : ℝ} (hx : x ∈ T) : Real.exp x ∈ T := by
  rw [mem_T_iff] at hx ⊢
  obtain ⟨n, hn⟩ := hx
  refine ⟨n + 1, ?_⟩
  have : Real.exp x ∈ Sstep (S n) :=
    Subfield.subset_closure (Or.inl (Or.inr ⟨x, hn, rfl⟩))
  exact this

/-- `T` is closed under `log`. -/
theorem T_log_closed {x : ℝ} (hx : x ∈ T) : Real.log x ∈ T := by
  rw [mem_T_iff] at hx ⊢
  obtain ⟨n, hn⟩ := hx
  refine ⟨n + 1, ?_⟩
  have : Real.log x ∈ Sstep (S n) :=
    Subfield.subset_closure (Or.inr ⟨x, hn, rfl⟩)
  exact this

theorem pi_mem_T : Real.pi ∈ T :=
  mem_T_iff.mpr ⟨0, Subfield.subset_closure (Set.mem_insert _ _)⟩

theorem phi_mem_T : Real.goldenRatio ∈ T :=
  mem_T_iff.mpr ⟨0, Subfield.subset_closure (Set.mem_insert_of_mem _ rfl)⟩

/-- Euler's number is `exp 1`, and `1 ∈ T`, so `e ∈ T` by exp-closure. -/
theorem e_mem_T : Real.exp 1 ∈ T := T_exp_closed (one_mem T)

/-- **The payoff: α⁻¹ is built entirely inside `T`.** Every operation in
`α⁻¹ = 44·π·exp(−w₈·ln φ/(44·π))` (field operations, one `log`, one `exp`) lands in
`T`, so the constant is a `T`-element produced without leaving the countable
field. -/
theorem alphaInv_mem_T : MinimalField.alphaInv ∈ T := by
  have hpi : Real.pi ∈ T := pi_mem_T
  have hphi : Real.goldenRatio ∈ T := phi_mem_T
  have h44 : (44 : ℝ) ∈ T := by exact_mod_cast (natCast_mem T 44)
  have hw8 : MinimalField.w8 ∈ T := by
    unfold MinimalField.w8
    exact_mod_cast (natCast_mem T 4)
  have hlogphi : Real.log Real.goldenRatio ∈ T := T_log_closed hphi
  have harg :
      -(MinimalField.w8) * Real.log Real.goldenRatio / (44 * Real.pi) ∈ T :=
    div_mem (mul_mem (neg_mem hw8) hlogphi) (mul_mem h44 hpi)
  have hexp :
      Real.exp (-(MinimalField.w8) * Real.log Real.goldenRatio / (44 * Real.pi)) ∈ T :=
    T_exp_closed harg
  unfold MinimalField.alphaInv
  exact mul_mem (mul_mem h44 hpi) hexp

/-- `T` is a proper subset of ℝ: it is countable, the continuum is not. -/
theorem T_proper : (T : Set ℝ) ≠ Set.univ := by
  intro h
  exact Cardinal.not_countable_real (h ▸ T_countable)

/-- **Item 1, deep half.** There is a single countable subfield `T` of ℝ that is
closed under exactly the operations the RS constants are built from (field
operations, `exp`, `log`), already contains the seeds π and φ, and contains the
derived constants `e` and `α⁻¹`. The construction of every RS constant can be
performed entirely inside this countable field; the uncountable real line is not
required as the workspace, only (at most) as the ambient in which the standard
`exp`/`log` happen to be defined. The continuum is removed from the framework's
operations, not just its outputs. -/
theorem rs_operations_below_continuum :
    ∃ K : Subfield ℝ,
      (K : Set ℝ).Countable
        ∧ (∀ x ∈ K, Real.exp x ∈ K)
        ∧ (∀ x ∈ K, Real.log x ∈ K)
        ∧ Real.pi ∈ K
        ∧ Real.goldenRatio ∈ K
        ∧ Real.exp 1 ∈ K
        ∧ MinimalField.alphaInv ∈ K
        ∧ (K : Set ℝ) ≠ Set.univ :=
  ⟨T, T_countable, fun _ hx => T_exp_closed hx, fun _ hx => T_log_closed hx,
    pi_mem_T, phi_mem_T, e_mem_T, alphaInv_mem_T, T_proper⟩

end ExpLogField
end PrimitiveRecognitionCalculus
end Foundation
end IndisputableMonolith
