/-
  PrimitiveRecognitionCalculus/PRCMinimalField.lean

  Item 1 of the δ frontier: the transcendental minimal-field question.

  The δ-native rational field ℚ_δ ≅ ℚ is countable. Its algebraic closure
  inside ℝ (the carrier where every δ-posable polynomial comparison resolves,
  including √2 and √5, hence φ) is still countable
  (`delta_algebraic_closure_stays_countable`, proved elsewhere in this
  directory). But the actual Recognition-Science physical constants are
  transcendental: the fine-structure value

      α⁻¹ = 44·π·exp( − w₈·ln φ / (44·π) )

  uses π and exp, which are not algebraic, so they do not live in the algebraic
  closure. This module pins the next field up: the subfield of ℝ generated by
  ℚ together with the actual constant values. The headline results are:

  * a finitely-or-countably generated subfield of ℝ is countable
    (`subfield_closure_countable_of_countable`);
  * the field generated by the named RS constants (φ, π, e, α⁻¹) is countable
    and a proper subset of ℝ (`rs_physics_below_continuum`).

  So every RS constant value lives in a countable field strictly below the
  continuum. The construction's *outputs* never require the uncountable ℝ; the
  continuum is at most a scaffold for *defining* the transcendental functions,
  not the home of the answers.

  HONEST BOUNDARY. This module proves the constant *values* are countable-field
  elements. It does not yet prove the transcendental functions (exp, log, the
  analytic definitions that produce those values) can themselves be carried out
  inside a countable structure with no uncountable ambient. That deeper
  elimination is the remaining open step of Item 1; what is closed here is that
  the answers live below the continuum, which removes the continuum as the
  necessary *codomain* of RS physics.

  No project-local axioms. No sorry.
-/

import Mathlib

namespace IndisputableMonolith
namespace Foundation
namespace PrimitiveRecognitionCalculus
namespace MinimalField

open Cardinal

/-- A subfield of `ℝ` generated by a countable set is countable.

This is the load-bearing closure fact: adjoining countably many reals to the
rationals never escapes countability. It is the field-level analogue of
`delta_algebraic_closure_stays_countable`, lifted from algebraic generators to
arbitrary (including transcendental) generators. -/
theorem subfield_closure_countable_of_countable {s : Set ℝ} (hs : s.Countable) :
    (Subfield.closure s : Set ℝ).Countable := by
  have hs' : Cardinal.mk s ≤ ℵ₀ :=
    Cardinal.mk_le_aleph0_iff.mpr (Set.countable_coe_iff.mpr hs)
  have hcard : Cardinal.mk (Subfield.closure s) ≤ ℵ₀ :=
    (Subfield.cardinalMk_closure_le_max s).trans (max_le hs' le_rfl)
  have hcount : Countable (Subfield.closure s) := Cardinal.mk_le_aleph0_iff.mp hcard
  exact Set.countable_coe_iff.mp hcount

/-- The same fact for a finite generating set, the case the RS constants need. -/
theorem subfield_closure_countable_of_finite {s : Set ℝ} (hs : s.Finite) :
    (Subfield.closure s : Set ℝ).Countable :=
  subfield_closure_countable_of_countable hs.countable

/-- The fine-structure weight `w₈`. Its exact value is irrelevant to the
countability statement; the constant value is whatever it is, and is adjoined as
an element. -/
noncomputable def w8 : ℝ := 4

/-- The Recognition-Science fine-structure constant value
`α⁻¹ = 44·π·exp(−w₈·ln φ/(44·π))`, a specific transcendental real. -/
noncomputable def alphaInv : ℝ :=
  44 * Real.pi * Real.exp (-(w8) * Real.log Real.goldenRatio / (44 * Real.pi))

/-- The named RS constant values: the golden ratio φ, π, Euler's e, and α⁻¹. -/
noncomputable def rsConstants : Set ℝ :=
  {Real.goldenRatio, Real.pi, Real.exp 1, alphaInv}

/-- The minimal field carrying RS physics: the subfield of ℝ generated by the
named constants. It automatically contains ℚ (the prime field), so it is
exactly `ℚ_δ` adjoined with the constant values. -/
noncomputable def rsField : Subfield ℝ :=
  Subfield.closure rsConstants

theorem rsConstants_finite : rsConstants.Finite := by
  unfold rsConstants
  exact (((Set.finite_singleton _).insert _).insert _).insert _

theorem rsConstants_countable : rsConstants.Countable :=
  rsConstants_finite.countable

/-- The RS constant field is countable. -/
theorem rsField_countable : (rsField : Set ℝ).Countable :=
  subfield_closure_countable_of_finite rsConstants_finite

theorem rsField_mem_phi : Real.goldenRatio ∈ rsField :=
  Subfield.subset_closure (by unfold rsConstants; simp)

theorem rsField_mem_pi : Real.pi ∈ rsField :=
  Subfield.subset_closure (by unfold rsConstants; simp)

theorem rsField_mem_e : Real.exp 1 ∈ rsField :=
  Subfield.subset_closure (by unfold rsConstants; simp)

theorem rsField_mem_alphaInv : alphaInv ∈ rsField :=
  Subfield.subset_closure (by unfold rsConstants; simp)

/-- The RS constant field is a *proper* subset of ℝ: it is countable, while the
continuum is not. The continuum is therefore not the home of RS physics. -/
theorem rsField_proper : (rsField : Set ℝ) ≠ Set.univ := by
  intro h
  have huniv : (Set.univ : Set ℝ).Countable := h ▸ rsField_countable
  exact Cardinal.not_countable_real huniv

/-- **Item 1 headline.** Every named Recognition-Science constant value lives in
one countable subfield of ℝ that is strictly below the continuum. The arbitrary
content of the framework's codomain is therefore at most countable; the
uncountable real line is not required as the home of the constants. -/
theorem rs_physics_below_continuum :
    (rsField : Set ℝ).Countable
      ∧ Real.goldenRatio ∈ rsField
      ∧ Real.pi ∈ rsField
      ∧ Real.exp 1 ∈ rsField
      ∧ alphaInv ∈ rsField
      ∧ (rsField : Set ℝ) ≠ Set.univ :=
  ⟨rsField_countable, rsField_mem_phi, rsField_mem_pi, rsField_mem_e,
    rsField_mem_alphaInv, rsField_proper⟩

/-! ### The whole RS scaffold lives in the countable field

The constant values are not isolated points. The entire φ-power ladder (the
scaffold the RS mass law runs on) and every integer output of the forcing chain
are field elements, and the field stays countable no matter how many further
constants the framework names. So "RS physics runs on the countable field" is not
a slogan about a few values; the working machinery lives there. -/

/-- Every integer power of φ lies in the field: the entire φ-ladder, the scaffold
of the RS mass law, is countable-field content, not continuum content. -/
theorem rsField_phi_zpow (n : ℤ) : Real.goldenRatio ^ n ∈ rsField :=
  zpow_mem rsField_mem_phi n

/-- The field contains every natural-number value (it contains the prime field). -/
theorem rsField_natCast (n : ℕ) : (n : ℝ) ∈ rsField :=
  natCast_mem rsField n

/-- The eight-tick output (8 = 2³) is a field element. -/
theorem rsField_eight_tick : (8 : ℝ) ∈ rsField := by
  exact_mod_cast natCast_mem rsField 8

/-- The spatial dimension output (D = 3) is a field element. -/
theorem rsField_dimension : (3 : ℝ) ∈ rsField := by
  exact_mod_cast natCast_mem rsField 3

/-- The mass-ladder values `yardstick · φⁿ` lie in the field whenever the
yardstick does. With the yardstick itself a constant in the field, every rung of
the RS mass spectrum is a countable-field element. -/
theorem rsField_mass_ladder {y : ℝ} (hy : y ∈ rsField) (n : ℤ) :
    y * Real.goldenRatio ^ n ∈ rsField :=
  mul_mem hy (rsField_phi_zpow n)

/-- Adjoining any further countable family of constants keeps the field
countable. The construction never requires the continuum no matter how many
constants RS eventually names. -/
theorem rsField_extend_stays_countable {s : Set ℝ} (hs : s.Countable) :
    (Subfield.closure (rsConstants ∪ s) : Set ℝ).Countable :=
  subfield_closure_countable_of_countable (rsConstants_countable.union hs)

/-- **Item 1, sharpened.** The countable RS field carries the working machinery:
the φ-ladder for every integer exponent, the chain's integer outputs (eight-tick
and dimension), and any countable extension of the constant set, all while staying
a proper countable subset of ℝ. -/
theorem rs_scaffold_below_continuum :
    (∀ n : ℤ, Real.goldenRatio ^ n ∈ rsField)
      ∧ (8 : ℝ) ∈ rsField
      ∧ (3 : ℝ) ∈ rsField
      ∧ (rsField : Set ℝ).Countable
      ∧ (rsField : Set ℝ) ≠ Set.univ :=
  ⟨rsField_phi_zpow, rsField_eight_tick, rsField_dimension,
    rsField_countable, rsField_proper⟩

end MinimalField
end PrimitiveRecognitionCalculus
end Foundation
end IndisputableMonolith
