/-
  Foundation/SeamClosure/Reference.lean   (Seam Closure, Link L1)

  ============================================================================
  STANDING COMMITMENT (do not delete, do not weaken).
  ============================================================================
  This module is one link in the Seam Closure chain whose end goal is a single
  forcing chain from the one act of distinction to meaning, to the global phase
  Theta, and to the moral skew sigma. We DO NOT QUIT until that chain is closed
  end to end with zero sorry and standard kernel axioms only. A `sorry` in this
  file is a debt to be paid, never an acceptable resting state. No session may
  declare the seam closed while any obligation below remains open. The plan of
  record is `Seam_Closure_Master_Plan_20260529.html`.
  ============================================================================

  Round-trip source: Next_Discoveries_Cross_Program_Review_20260529.html, Sec 3.

  L1 derives REFERENCE (aboutness) from the distinction primitive. Distinction
  marks "A is not B". Reference marks "A is about B". The thesis is that
  reference is a delta-native operation on the trace structure: a "referring
  trace" records a subject distinguished relative to a held ground, and this is
  generated by delta plus a designated ground with no third primitive. If a
  genuine second primitive (a frame) turns out to be required, that is itself a
  result and must be recorded honestly in the plan.

  STATUS: SCAFFOLDING. Obligations O1.1, O1.2, O1.3 are open (see `sorry`s).
-/

-- SEAM-PROGRESS: L1 COMPLETE 2026-05-29. O1.1, O1.2, O1.3 all closed. zero sorry. Reference is delta-native (initial pointed referring algebra).

import Mathlib
import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.Basic

namespace IndisputableMonolith
namespace Foundation
namespace SeamClosure

open PrimitiveRecognitionCalculus

/-- A **referring trace**: a subject trace distinguished relative to a held
ground trace. This is the candidate delta-native carrier of aboutness. The
subject is "what is marked"; the ground is "the standing context it is marked
against". Both are ordinary traces, so no new constructor is introduced. -/
structure ReferringTrace where
  subject : Trace
  ground  : Trace
  deriving DecidableEq, Repr

namespace ReferringTrace

/-- The reference relation: `r` genuinely refers when its subject is
distinguished from its ground, i.e. they are not the same trace. A reference
that does not distinguish subject from ground points at nothing. -/
def refersTo (r : ReferringTrace) : Prop :=
  r.subject ≠ r.ground

/-- O1.1. Reference is decidable: the verifier can always settle whether a
referring trace genuinely refers, with no appeal to excluded middle.

OBLIGATION FOR THE NEXT SESSION (fillable):
  `Trace` has `DecidableEq` (it `deriving DecidableEq` in Basic.lean). The
  proposition `refersTo r` unfolds to `r.subject ≠ r.ground`. Use the derived
  decidable equality to build the instance. Intended shape:
    `unfold refersTo; exact inferInstance` or `decide`-friendly via `Ne`.
  Replace the `sorry`. -/
instance instDecidableRefersTo (r : ReferringTrace) : Decidable (refersTo r) := by
  unfold refersTo
  exact inferInstance

/-- The "neutral" reference of a trace to itself: refers to nothing. Used as the
basepoint of the referring structure. -/
def selfReference (T : Trace) : ReferringTrace :=
  ⟨T, T⟩

/-- The basepoint genuinely refers to nothing. -/
theorem selfReference_not_refers (T : Trace) :
    ¬ (selfReference T).refersTo := by
  unfold refersTo selfReference
  simp

/-- Reference built from one act: distinguish the one-step extension of the
ground from the ground itself. This is the minimal genuine reference, and the
claim of O1.2 is that every genuine reference is reachable from basepoints by
this construction together with trace extension, with delta the only act. -/
def stepReference (ground : Trace) : ReferringTrace :=
  ⟨Trace.step ground, ground⟩

/-- The generation predicate for referring traces. A referring trace is
`Generated` when it is reachable from a self-reference basepoint by finitely many
one-act moves: extend the subject by one δ, or extend the ground by one δ. The
only act used anywhere is `DistinctionAct.delta` (carried by `Trace.step`), so a
`Generated` referring trace introduces no second generative primitive. -/
inductive Generated : ReferringTrace → Prop where
  | base (T : Trace) : Generated (selfReference T)
  | extendSubject {r : ReferringTrace} : Generated r →
      Generated ⟨Trace.step r.subject, r.ground⟩
  | extendGround {r : ReferringTrace} : Generated r →
      Generated ⟨r.subject, Trace.step r.ground⟩

/-- Every referring trace whatsoever is generated from the basepoints by the two
one-act δ moves. Because the single distinction act is the only constructor of
`DistinctionAct`, a trace is fixed by its length, so a referring trace is fixed
by the pair of lengths, and every length pair is reached from `⟨empty, empty⟩` by
extending the subject and the ground. -/
theorem generated_all (s g : Trace) :
    Generated (⟨s, g⟩ : ReferringTrace) := by
  induction s generalizing g with
  | empty =>
      induction g with
      | empty => exact Generated.base Trace.empty
      | extend g' a ih =>
          cases a
          exact Generated.extendGround ih
  | extend s' a ih =>
      cases a
      exact Generated.extendSubject (ih g)

/-- O1.2. Reference reduces to distinction: a genuine referring trace is
generated by the basepoints `selfReference` together with the one-act δ moves,
with `DistinctionAct.delta` the only act. No second generative primitive appears.

The hypothesis `refersTo r` is in fact not needed: `generated_all` shows the
generation reaches every referring trace, referring or not, so the reduction to
distinction is total. We keep the hypothesis in the statement to match the
obligation, and record that the stronger unconditional form holds. This is the
positive resolution: reference is δ-native, no frame second-primitive required. -/
theorem reference_reduces_to_distinction
    (r : ReferringTrace) (_h : r.refersTo) :
    Generated r := by
  obtain ⟨s, g⟩ := r
  exact generated_all s g

/-- A **pointed referring algebra** on a carrier `X`: a basepoint `z` (the image
of the empty self-reference), a subject-extension `sSub`, a ground-extension
`sGrd`, and the commutativity law `sSub ∘ sGrd = sGrd ∘ sSub`. The commutativity
is not optional: a referring trace `⟨step s, step g⟩` is reached either by
extending the subject after the ground or the ground after the subject, so any
structure receiving both extensions must identify the two orders. This is the
exact analogue of the product of two natural-number objects being initial among
bi-pointed iterations whose two steps commute. -/
structure ReferringAlgebra (X : Type*) where
  z : X
  sSub : X → X
  sGrd : X → X
  comm : ∀ x, sSub (sGrd x) = sGrd (sSub x)

/-- Evaluation on the ground coordinate alone, from a given subject base value. -/
def evalGround {X : Type*} (A : ReferringAlgebra X) (base : X) : Trace → X
  | Trace.empty => base
  | Trace.extend g _ => A.sGrd (evalGround A base g)

/-- The recursor: evaluate a referring trace into a pointed referring algebra,
by recursion on the subject then the ground. -/
def eval {X : Type*} (A : ReferringAlgebra X) : Trace → Trace → X
  | Trace.empty, g => evalGround A A.z g
  | Trace.extend s _, g => A.sSub (eval A s g)

/-- The ground computation rule for `eval`, proved by induction on the subject
using the algebra's commutativity. This is the one rule that is not definitional. -/
theorem eval_ground_step {X : Type*} (A : ReferringAlgebra X) (s g : Trace) :
    eval A s (Trace.step g) = A.sGrd (eval A s g) := by
  induction s with
  | empty =>
      simp [eval, evalGround, Trace.step]
  | extend s' a ih =>
      show A.sSub (eval A s' (Trace.step g)) = A.sGrd (A.sSub (eval A s' g))
      rw [ih, A.comm]

/-- The structure-preserving-map predicate: `h` is a homomorphism from referring
traces into the algebra when it sends the empty self-reference to `z` and
intertwines the two one-act extensions with `sSub` and `sGrd`. -/
def IsHom {X : Type*} (A : ReferringAlgebra X) (h : ReferringTrace → X) : Prop :=
  h (selfReference Trace.empty) = A.z
    ∧ (∀ s g : Trace, h ⟨Trace.step s, g⟩ = A.sSub (h ⟨s, g⟩))
    ∧ (∀ s g : Trace, h ⟨s, Trace.step g⟩ = A.sGrd (h ⟨s, g⟩))

/-- The canonical homomorphism induced by the recursor. -/
def evalHom {X : Type*} (A : ReferringAlgebra X) : ReferringTrace → X :=
  fun r => eval A r.subject r.ground

theorem evalHom_isHom {X : Type*} (A : ReferringAlgebra X) :
    IsHom A (evalHom A) := by
  refine ⟨rfl, ?_, ?_⟩
  · intro s g; rfl
  · intro s g
    show eval A s (Trace.step g) = A.sGrd (eval A s g)
    exact eval_ground_step A s g

/-- O1.3. The forcing / initial-object property, proved. Referring traces, with
the empty self-reference as basepoint and the two one-act δ extensions as steps,
are the initial pointed referring algebra: for every commuting pointed referring
algebra there is a unique structure-preserving map out. This is the precise sense
in which reference is FORCED by distinction, the exact analogue of the trace orbit
being the initial pointed iteration. No second primitive is introduced; the only
act is δ, carried by `Trace.step`, and the only law beyond the steps is the
commutativity already forced by the two-dimensional generation. -/
theorem reference_forced_by_distinction {X : Type*} (A : ReferringAlgebra X) :
    ∃! h : ReferringTrace → X, IsHom A h := by
  refine ⟨evalHom A, evalHom_isHom A, ?_⟩
  intro h hh
  obtain ⟨hz, hsub, hgrd⟩ := hh
  funext r
  obtain ⟨s, g⟩ := r
  show h ⟨s, g⟩ = eval A s g
  induction s generalizing g with
  | empty =>
      induction g with
      | empty => exact hz
      | extend g' a ih =>
          cases a
          have hstep : h ⟨Trace.empty, Trace.step g'⟩ = A.sGrd (h ⟨Trace.empty, g'⟩) :=
            hgrd Trace.empty g'
          calc h ⟨Trace.empty, Trace.extend g' DistinctionAct.delta⟩
              = A.sGrd (h ⟨Trace.empty, g'⟩) := hstep
            _ = A.sGrd (eval A Trace.empty g') := by rw [ih]
            _ = eval A Trace.empty (Trace.extend g' DistinctionAct.delta) := by
                  simp [eval, evalGround]
  | extend s' a ih =>
      cases a
      have hstep : h ⟨Trace.step s', g⟩ = A.sSub (h ⟨s', g⟩) := hsub s' g
      calc h ⟨Trace.extend s' DistinctionAct.delta, g⟩
          = A.sSub (h ⟨s', g⟩) := hstep
        _ = A.sSub (eval A s' g) := by rw [ih g]
        _ = eval A (Trace.extend s' DistinctionAct.delta) g := rfl

end ReferringTrace

end SeamClosure
end Foundation
end IndisputableMonolith
