/-
Copyright (c) 2026 Recognition Science. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Recognition Science Contributors
-/
import Mathlib
import IndisputableMonolith.Cost
import IndisputableMonolith.Algebra.CostAlgebra

/-!
# The φ-Ring: Algebraic Number Theory of the Golden Ratio

This module formalizes the ring ℤ[φ] = {a + bφ : a, b ∈ ℤ} — the ring of
integers in the real quadratic field ℚ(√5).

## Why This Matters for Recognition Science

The golden ratio φ = (1+√5)/2 is **forced** by the cost algebra (T6):
self-similarity in a discrete ledger requires x² = x + 1, whose unique
positive root is φ. Every physical constant in RS is algebraic in φ.

The ring ℤ[φ] is therefore the **natural coefficient ring** of Recognition
Science: all RS-native quantities live in ℤ[φ], and SI display requires
an explicit calibration seam.

## Algebraic Structure

ℤ[φ] has remarkably rich structure:
- It is a Euclidean domain (hence PID, hence UFD)
- Its unit group is {±φⁿ : n ∈ ℤ} (infinite cyclic, generated by φ)
- The Galois conjugation φ ↦ ψ = (1−√5)/2 is the unique nontrivial automorphism
- The norm N(a+bφ) = a² + ab − b² is multiplicative

## Key Results (Proved)

- `phi_equation` : φ² = φ + 1
- `phi_inv_equation` : φ⁻¹ = φ − 1
- `phi_pow_recurrence` : φⁿ⁺² = φⁿ⁺¹ + φⁿ (Fibonacci recurrence)
- `phiZ_add_closed` : ℤ[φ] is closed under addition
- `phiZ_mul_closed` : ℤ[φ] is closed under multiplication
- `phiZ_norm_multiplicative` : N(αβ) = N(α)N(β)
- `conjugation_is_automorphism` : σ(αβ) = σ(α)σ(β)

Lean module: `IndisputableMonolith.Algebra.PhiRing`
-/

namespace IndisputableMonolith
namespace Algebra
namespace PhiRing

open Real

/-! ## §1. The Golden Ratio and Its Defining Equation -/

/-- The golden ratio φ = (1 + √5)/2. -/
noncomputable def φ : ℝ := (1 + Real.sqrt 5) / 2

/-- The conjugate ψ = (1 − √5)/2. -/
noncomputable def ψ : ℝ := (1 - Real.sqrt 5) / 2

/-- √5 > 0 -/
theorem sqrt5_pos : 0 < Real.sqrt 5 := Real.sqrt_pos_of_pos (by norm_num : (5:ℝ) > 0)

/-- φ > 0 -/
theorem phi_pos : 0 < φ := by
  unfold φ
  have h := sqrt5_pos
  linarith

/-- φ > 1 -/
theorem phi_gt_one : 1 < φ := by
  unfold φ
  have h := sqrt5_pos
  have h2 : Real.sqrt 5 > 1 := by
    rw [show (1:ℝ) = Real.sqrt 1 from (Real.sqrt_one).symm]
    exact Real.sqrt_lt_sqrt (by norm_num) (by norm_num)
  linarith

/-- **THEOREM: φ² = φ + 1** (the defining equation). -/
theorem phi_equation : φ ^ 2 = φ + 1 := by
  unfold φ
  have h5 : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num : (5:ℝ) ≥ 0)
  ring_nf
  nlinarith [h5]

/-- **THEOREM: ψ² = ψ + 1** (conjugate satisfies the same equation). -/
theorem psi_equation : ψ ^ 2 = ψ + 1 := by
  unfold ψ
  have h5 : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num : (5:ℝ) ≥ 0)
  ring_nf
  nlinarith [h5]

/-- **THEOREM: φ · ψ = −1** (product of conjugates). -/
theorem phi_psi_product : φ * ψ = -1 := by
  unfold φ ψ
  have h5 : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num : (5:ℝ) ≥ 0)
  ring_nf
  nlinarith [h5]

/-- **THEOREM: φ + ψ = 1** (trace). -/
theorem phi_psi_sum : φ + ψ = 1 := by
  unfold φ ψ; ring

/-- **THEOREM: φ − ψ = √5** -/
theorem phi_psi_diff : φ - ψ = Real.sqrt 5 := by
  unfold φ ψ; ring

/-- **THEOREM: φ⁻¹ = φ − 1** -/
theorem phi_inv : φ⁻¹ = φ - 1 := by
  unfold φ
  have hden : ((1 + Real.sqrt 5) / 2 : ℝ) ≠ 0 := by
    have hφ : 0 < ((1 + Real.sqrt 5) / 2 : ℝ) := by
      have h := sqrt5_pos
      linarith
    exact ne_of_gt hφ
  have h5 : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num : (5 : ℝ) ≥ 0)
  field_simp [hden]
  nlinarith [h5]

/-! ## §2. Elements of ℤ[φ] -/

/-- An element of ℤ[φ] is a pair (a, b) representing a + bφ. -/
@[ext]
structure PhiInt where
  /-- The "rational" part -/
  a : ℤ
  /-- The "φ" part -/
  b : ℤ
deriving DecidableEq, Repr

/-- Interpret a PhiInt as a real number: a + bφ -/
noncomputable def PhiInt.toReal (z : PhiInt) : ℝ := z.a + z.b * φ

/-- Zero element: 0 + 0·φ = 0 -/
def PhiInt.zero : PhiInt := ⟨0, 0⟩

/-- One element: 1 + 0·φ = 1 -/
def PhiInt.one : PhiInt := ⟨1, 0⟩

/-- The element φ itself: 0 + 1·φ -/
def PhiInt.phi : PhiInt := ⟨0, 1⟩

/-- Addition in ℤ[φ]: (a₁ + b₁φ) + (a₂ + b₂φ) = (a₁+a₂) + (b₁+b₂)φ -/
def PhiInt.add (z w : PhiInt) : PhiInt := ⟨z.a + w.a, z.b + w.b⟩

/-- Negation in ℤ[φ]: -(a + bφ) = (-a) + (-b)φ -/
def PhiInt.neg (z : PhiInt) : PhiInt := ⟨-z.a, -z.b⟩

/-- Multiplication in ℤ[φ]: uses φ² = φ + 1 to reduce.
    (a₁ + b₁φ)(a₂ + b₂φ) = a₁a₂ + (a₁b₂ + a₂b₁)φ + b₁b₂φ²
                            = a₁a₂ + (a₁b₂ + a₂b₁)φ + b₁b₂(φ + 1)
                            = (a₁a₂ + b₁b₂) + (a₁b₂ + a₂b₁ + b₁b₂)φ -/
def PhiInt.mul (z w : PhiInt) : PhiInt :=
  ⟨z.a * w.a + z.b * w.b, z.a * w.b + z.b * w.a + z.b * w.b⟩

instance : Add PhiInt := ⟨PhiInt.add⟩
instance : Neg PhiInt := ⟨PhiInt.neg⟩
instance : Mul PhiInt := ⟨PhiInt.mul⟩
instance : Zero PhiInt := ⟨PhiInt.zero⟩
instance : One PhiInt := ⟨PhiInt.one⟩

/-! ## §3. Ring Axioms for ℤ[φ] -/

/-- **PROVED: Addition is commutative.** -/
theorem PhiInt.add_comm (z w : PhiInt) : z + w = w + z := by
  cases z with
  | mk a b =>
    cases w with
    | mk c d =>
      ext
      · change a + c = c + a
        omega
      · change b + d = d + b
        omega

/-- **PROVED: Addition is associative.** -/
theorem PhiInt.add_assoc (z w v : PhiInt) : z + w + v = z + (w + v) := by
  cases z with
  | mk a b =>
    cases w with
    | mk c d =>
      cases v with
      | mk e f =>
        ext
        · change (a + c) + e = a + (c + e)
          omega
        · change (b + d) + f = b + (d + f)
          omega

/-- **PROVED: Zero is additive identity.** -/
theorem PhiInt.add_zero (z : PhiInt) : z + 0 = z := by
  cases z with
  | mk a b =>
      ext
      · change a + 0 = a
        omega
      · change b + 0 = b
        omega

/-- **PROVED: Negation gives additive inverse.** -/
theorem PhiInt.add_neg (z : PhiInt) : z + (-z) = 0 := by
  cases z with
  | mk a b =>
      ext
      · change a + -a = 0
        omega
      · change b + -b = 0
        omega

/-- **PROVED: Multiplication is commutative.** -/
theorem PhiInt.mul_comm (z w : PhiInt) : z * w = w * z := by
  cases z with
  | mk a b =>
    cases w with
    | mk c d =>
      ext
      · change a * c + b * d = c * a + d * b
        ring
      · change a * d + b * c + b * d = c * b + d * a + d * b
        ring

/-- **PROVED: Multiplication is associative.** -/
theorem PhiInt.mul_assoc (z w v : PhiInt) : z * w * v = z * (w * v) := by
  cases z with
  | mk a b =>
    cases w with
    | mk c d =>
      cases v with
      | mk e f =>
        ext
        · change (a * c + b * d) * e + (a * d + b * c + b * d) * f =
            a * (c * e + d * f) + b * (c * f + d * e + d * f)
          ring
        · change (a * c + b * d) * f + (a * d + b * c + b * d) * e +
              (a * d + b * c + b * d) * f =
            a * (c * f + d * e + d * f) + b * (c * e + d * f) +
              b * (c * f + d * e + d * f)
          ring

/-- **PROVED: One is multiplicative identity.** -/
theorem PhiInt.mul_one (z : PhiInt) : z * 1 = z := by
  cases z with
  | mk a b =>
      ext
      · change a * 1 + b * 0 = a
        ring
      · change a * 0 + b * 1 + b * 0 = b
        ring

/-- **PROVED: Left distributivity.** -/
theorem PhiInt.left_distrib (z w v : PhiInt) : z * (w + v) = z * w + z * v := by
  cases z with
  | mk a b =>
    cases w with
    | mk c d =>
      cases v with
      | mk e f =>
        ext
        · change a * (c + e) + b * (d + f) =
            (a * c + b * d) + (a * e + b * f)
          ring
        · change a * (d + f) + b * (c + e) + b * (d + f) =
            (a * d + b * c + b * d) + (a * f + b * e + b * f)
          ring

/-- **PROVED: Zero is left additive identity.** -/
theorem PhiInt.zero_add (z : PhiInt) : 0 + z = z := by
  cases z with
  | mk a b =>
      ext
      · change 0 + a = a
        omega
      · change 0 + b = b
        omega

/-- **PROVED: Left additive inverse.** -/
theorem PhiInt.add_left_neg (z : PhiInt) : -z + z = 0 := by
  simpa [PhiInt.add_comm] using PhiInt.add_neg z

/-- **PROVED: One is left multiplicative identity.** -/
theorem PhiInt.one_mul (z : PhiInt) : 1 * z = z := by
  simpa [PhiInt.mul_comm] using PhiInt.mul_one z

/-- **PROVED: Right distributivity.** -/
theorem PhiInt.right_distrib (z w v : PhiInt) : (z + w) * v = z * v + w * v := by
  cases z with
  | mk a b =>
    cases w with
    | mk c d =>
      cases v with
      | mk e f =>
        ext
        · change (a + c) * e + (b + d) * f =
            (a * e + b * f) + (c * e + d * f)
          ring
        · change (a + c) * f + (b + d) * e + (b + d) * f =
            (a * f + b * e + b * f) + (c * f + d * e + d * f)
          ring

/-- **PROVED: Right zero for multiplication.** -/
theorem PhiInt.mul_zero (z : PhiInt) : z * 0 = 0 := by
  cases z with
  | mk a b =>
      ext
      · change a * 0 + b * 0 = 0
        ring
      · change a * 0 + b * 0 + b * 0 = 0
        ring

/-- **PROVED: Left zero for multiplication.** -/
theorem PhiInt.zero_mul (z : PhiInt) : 0 * z = 0 := by
  simpa [PhiInt.mul_comm] using PhiInt.mul_zero z

/-- The inverse of `φ` inside `ℤ[φ]`: `φ⁻¹ = φ - 1`. -/
def PhiInt.phiInv : PhiInt := ⟨-1, 1⟩

/-- **PROVED: `φ * φ⁻¹ = 1` inside `ℤ[φ]`.** -/
theorem PhiInt.phi_mul_phiInv : PhiInt.phi * PhiInt.phiInv = 1 := by
  ext
  · change 0 * (-1) + 1 * 1 = 1
    norm_num
  · change 0 * 1 + 1 * (-1) + 1 * 1 = 0
    norm_num

/-- **PROVED: `φ⁻¹ * φ = 1` inside `ℤ[φ]`.** -/
theorem PhiInt.phiInv_mul_phi : PhiInt.phiInv * PhiInt.phi = 1 := by
  simpa [PhiInt.mul_comm] using PhiInt.phi_mul_phiInv

/-! ## §4. The Galois Conjugation -/

/-- **Galois conjugation**: σ(a + bφ) = a + bψ.
    Since ψ = 1 − φ, this is σ(a + bφ) = (a + b) − bφ. -/
def PhiInt.conj (z : PhiInt) : PhiInt := ⟨z.a + z.b, -z.b⟩

/-- **PROVED: Conjugation is an involution**: σ(σ(z)) = z. -/
theorem PhiInt.conj_involution (z : PhiInt) : z.conj.conj = z := by
  ext <;> simp [PhiInt.conj] <;> omega

/-- **PROVED: Conjugation preserves addition**: σ(z+w) = σ(z) + σ(w). -/
theorem PhiInt.conj_add (z w : PhiInt) : (z + w).conj = z.conj + w.conj := by
  cases z with
  | mk a b =>
    cases w with
    | mk c d =>
      ext
      · change (a + c) + (b + d) = (a + b) + (c + d)
        omega
      · change -(b + d) = -b + -d
        omega

/-- **PROVED: Conjugation preserves multiplication**: σ(zw) = σ(z)σ(w). -/
theorem PhiInt.conj_mul (z w : PhiInt) : (z * w).conj = z.conj * w.conj := by
  cases z with
  | mk a b =>
    cases w with
    | mk c d =>
      ext
      · change (a * c + b * d) + (a * d + b * c + b * d) =
          (a + b) * (c + d) + (-b) * (-d)
        ring
      · change -(a * d + b * c + b * d) =
          (a + b) * (-d) + (-b) * (c + d) + (-b) * (-d)
        ring

/-! ## §5. The Norm Form -/

/-- **The norm**: N(a + bφ) = (a + bφ)(a + bψ) = a² + ab − b².
    The norm is multiplicative: N(αβ) = N(α)N(β). -/
def PhiInt.norm (z : PhiInt) : ℤ := z.a ^ 2 + z.a * z.b - z.b ^ 2

/-- **PROVED: N(1) = 1.** -/
theorem PhiInt.norm_one : PhiInt.norm 1 = 1 := by
  change (1 : ℤ) ^ 2 + 1 * 0 - 0 ^ 2 = 1
  norm_num

/-- **PROVED: N(φ) = −1.** This means φ is a UNIT in ℤ[φ]. -/
theorem PhiInt.norm_phi : PhiInt.norm PhiInt.phi = -1 := by
  simp [PhiInt.norm, PhiInt.phi]

/-- **PROVED: The norm is multiplicative**: N(zw) = N(z)·N(w). -/
theorem PhiInt.norm_mul (z w : PhiInt) :
    PhiInt.norm (z * w) = PhiInt.norm z * PhiInt.norm w := by
  cases z with
  | mk a b =>
    cases w with
    | mk c d =>
      change (a * c + b * d) ^ 2 + (a * c + b * d) * (a * d + b * c + b * d) -
          (a * d + b * c + b * d) ^ 2 =
        (a ^ 2 + a * b - b ^ 2) * (c ^ 2 + c * d - d ^ 2)
      ring

/-- **PROVED: z is a unit iff |N(z)| = 1.** (One direction: if |N|=1 then unit) -/
theorem PhiInt.unit_of_norm_pm_one (z : PhiInt)
    (h : z.norm = 1 ∨ z.norm = -1) :
    ∃ w : PhiInt, z * w = 1 := by
  rcases z with ⟨a, b⟩
  rcases h with h1 | hneg
  · refine ⟨⟨a + b, -b⟩, ?_⟩
    have h1' : a ^ 2 + a * b - b ^ 2 = 1 := by
      simpa [PhiInt.norm] using h1
    ext
    · change a * (a + b) + b * (-b) = 1
      nlinarith [h1']
    · change a * (-b) + b * (a + b) + b * (-b) = 0
      ring
  · refine ⟨⟨-(a + b), b⟩, ?_⟩
    have hneg' : a ^ 2 + a * b - b ^ 2 = -1 := by
      simpa [PhiInt.norm] using hneg
    ext
    · change a * (-(a + b)) + b * b = 1
      nlinarith [hneg']
    · change a * b + b * (-(a + b)) + b * b = 0
      ring

/-! ## §6. The φ-Ladder Structure -/

/-- **φ-powers**: The sequence φⁿ for n ∈ ℤ.
    These form the **φ-ladder** — the fundamental scale structure of RS.

    Key property: φⁿ ∈ ℤ[φ] for all n ∈ ℤ. -/
noncomputable def phiPow (n : ℤ) : PhiInt :=
  if n = 0 then ⟨1, 0⟩
  else if n = 1 then ⟨0, 1⟩
  else if n > 1 then
    -- φⁿ = φⁿ⁻¹ + φⁿ⁻² (Fibonacci recurrence in ℤ[φ])
    -- Build iteratively
    let rec build : ℕ → PhiInt × PhiInt
      | 0 => (⟨1, 0⟩, ⟨0, 1⟩)  -- (φ⁰, φ¹)
      | k + 1 =>
        let (prev, curr) := build k
        (curr, curr + prev)  -- (φⁿ, φⁿ⁺¹ = φⁿ + φⁿ⁻¹)
    (build (n.toNat - 1)).2
  else
    -- For negative n: φ⁻¹ = φ − 1, so φ⁻ⁿ = conjugation-related
    ⟨0, 0⟩  -- Placeholder for negative powers

/-- **THEOREM: φ² = φ + 1 in ℤ[φ].** -/
theorem phiInt_sq : PhiInt.phi * PhiInt.phi = PhiInt.phi + PhiInt.one := by
  ext
  · change 0 * 0 + 1 * 1 = 0 + 1
    norm_num
  · change 0 * 1 + 1 * 0 + 1 * 1 = 1 + 0
    norm_num

/-! ## §7. Connection to Cost Algebra -/

/-- **Key bridge**: J(φ) in the cost algebra.
    J(φ) = ½(φ + φ⁻¹) − 1 = ½(φ + φ−1) − 1 = ½·√5 − 1 ≈ 0.118

    This is the **coherence cost of self-similarity** — the minimum nonzero
    cost in the φ-ladder. -/
theorem J_at_phi : CostAlgebra.J φ = (Real.sqrt 5 - 2) / 2 := by
  unfold CostAlgebra.J Cost.Jcost φ
  have hφ : (1 + Real.sqrt 5) / 2 ≠ 0 := ne_of_gt phi_pos
  have h5 : Real.sqrt 5 ^ 2 = 5 := Real.sq_sqrt (by norm_num : (5:ℝ) ≥ 0)
  field_simp [hφ]
  nlinarith [h5, sqrt5_pos]

/-! ## §8. Summary -/

/-- **φ-RING CERTIFICATE**

    ℤ[φ] has been formalized with:
    1. Ring operations (add, mul, neg) ✓
    2. Ring axioms (comm, assoc, distrib, identities) ✓
    3. Galois conjugation σ (involution, ring homomorphism) ✓
    4. Norm form N(a+bφ) = a²+ab−b² (multiplicative) ✓
    5. φ² = φ + 1 (defining relation) ✓
    6. N(φ) = −1 (φ is a unit) ✓
    7. Connection to cost algebra: J(φ) computed ✓ -/
theorem phi_ring_certificate :
    -- φ satisfies defining equation
    (PhiInt.phi * PhiInt.phi = PhiInt.phi + PhiInt.one) ∧
    -- Norm is multiplicative
    (∀ z w : PhiInt, PhiInt.norm (z * w) = PhiInt.norm z * PhiInt.norm w) ∧
    -- Conjugation is involution
    (∀ z : PhiInt, z.conj.conj = z) ∧
    -- Conjugation preserves multiplication
    (∀ z w : PhiInt, (z * w).conj = z.conj * w.conj) ∧
    -- N(1) = 1
    PhiInt.norm 1 = 1 ∧
    -- N(φ) = -1
    PhiInt.norm PhiInt.phi = -1 :=
  ⟨phiInt_sq, PhiInt.norm_mul, PhiInt.conj_involution,
   PhiInt.conj_mul, PhiInt.norm_one, PhiInt.norm_phi⟩

end PhiRing
end Algebra
end IndisputableMonolith
