import Mathlib.Data.Finset.Image
import Mathlib.Data.Finset.Card
import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Fintype.Card
import Mathlib.Logic.Function.Defs

/-!
# CellInjection: the cell-injection test (does a bulk flip necessarily post?)

Greenlit as the first step of the entropy-fork program (panel
`holo_bigger_discovery_20260702`, judge Fable 5): *flip one interior bit of the D=3
cell and check whether the boundary record necessarily changes.* The test is designed
to separate two futures for recognition complementarity: if bulk degeneracy is
unrecorded (like the boundary fiber degeneracy of `RecordCostAsymmetry.
fiber_posts_one_record`), complementarity stays an axiom; if every bulk distinction
posts, complementarity moves toward a theorem.

## The setup (all forced substrate, no new modeling freedom)

The forced 8-tick cell in D=3 is the cube `2³`: 8 vertices, 6 faces
(`PixelLocal.cube_vertices`, `PixelLocal.cube_faces`). Put one recognition bit on each
vertex (`CellCfg = Fin 256`). The **boundary record** of the cell is what the ledger
closure posts: the six face-closure parities (`faceRecord`), one per face, exactly the
per-face `PixelLocal.closed` functional read on all six faces of one cell.

## The verdict (machine-checked, axiom-clean, all by `decide`)

The answer is a sharp dichotomy, not a yes or a no:

1. **Every local bulk flip posts** (`single_flip_posts`): flipping any single vertex
   bit changes the boundary record, from every one of the 256 configurations, and it
   changes exactly the three face records incident to that vertex
   (`single_flip_posts_three`). No single bulk distinction is unrecorded.
2. **The record map is nonetheless non-injective** (`record_not_injective`): its
   blind set is a rank-4 subgroup of 16 moves (`recordKernel_card`,
   `record_nullity_eq_four`), the group generated by whole-face flips
   (`recordKernel_eq`), including the global complement and the two inscribed
   tetrahedra (`105`, `150`).
3. **Blindness is only global** (`record_blind_only_global`): any two configurations
   with the same boundary record differ on at least 4 of the 8 vertices, half the
   cell. The bound is tight: one whole-face flip (weight 4) is invisible from every
   base configuration (`face_flip_invisible_everywhere`).
4. **Rank-nullity of the cell record map**: `|image| = 16 = 2⁴`, `|kernel| = 16 = 2⁴`,
   `16 · 16 = 256` (`record_image_times_kernel`). At whole-cell granularity the
   record cost (4 posted bits) and the fiber degeneracy (4 free bits) COINCIDE; the
   entropy fork of `CoefficientBridge` (rank 1 vs nullity 3 per face; rank 2 vs
   nullity 4 on the domino) is a per-face / glued-surface phenomenon, invisible at
   the single whole cell.

## What this buys for recognition complementarity (honest scope)

The complementarity premise of the holography paper ("no bulk distinction exists
without a boundary-readable witness") REDUCES, on the forced cell, from a statement
about all `2⁸` bulk states to a statement about 16 explicit global parity moves:
weak complementarity through the posted record holds iff the whole-face parity flips
are recognition gauge. That identification is exactly the record-cost reading again
(an unposted move is not a performed distinction), so the fork selector and the
complementarity axiom are the SAME choice at cell level, now with the blind set
computed and classified rather than postulated. This module does NOT prove the
16 moves are gauge; it isolates them.
-/

namespace IndisputableMonolith
namespace Holography
namespace CellInjection

/- The `decide` proofs below enumerate `Fin 256` (and pairs over it); the derived
`Fintype` decidability instances recurse once per element, so the default
`maxRecDepth 512` and heartbeat budget are far too small. Raising them changes
nothing about trust: the kernel still checks every case. -/
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

/-- A full-cell configuration: one recognition bit on each of the `8 = 2³` vertices of
the forced D=3 cell, packed into `Fin 256`. Vertex `v ∈ Fin 8` has coordinate bits
`(v&1, v&2, v&4)`. -/
abbrev CellCfg := Fin 256

/-- Vertex bit `i ∈ Fin 8` of a cell configuration. -/
def vbit (c : CellCfg) (i : Fin 8) : Bool := Nat.testBit c.val i.val

/-- Ledger-closure record of one face with vertices `i j k l`: the four bits XOR to 0
(even parity), i.e. the closed-loop condition of `PixelLocal.closed`, negated XOR. -/
def closedOn (c : CellCfg) (i j k l : Fin 8) : Bool :=
  ! (vbit c i ^^ vbit c j ^^ vbit c k ^^ vbit c l)

/-- **The boundary record of the cell**: the six face-closure parities, one per cube
face (axis, side), each face collecting the four vertices whose axis-bit equals the
side. This is everything the ledger closure posts at the cell boundary. -/
def faceRecord (c : CellCfg) : List Bool :=
  [ closedOn c 0 2 4 6   -- x = 0
  , closedOn c 1 3 5 7   -- x = 1
  , closedOn c 0 1 4 5   -- y = 0
  , closedOn c 2 3 6 7   -- y = 1
  , closedOn c 0 1 2 3   -- z = 0
  , closedOn c 4 5 6 7 ] -- z = 1

/-- Flip vertex `i` of configuration `c`. -/
def flipv (c : CellCfg) (i : Fin 8) : CellCfg :=
  ⟨(c.val ^^^ (1 <<< i.val)) % 256, Nat.mod_lt _ (by decide)⟩

/-- Bitwise XOR of two configurations (the move taking one to the other). -/
def xorCfg (c d : CellCfg) : CellCfg :=
  ⟨(c.val ^^^ d.val) % 256, Nat.mod_lt _ (by decide)⟩

/-- Hamming weight: how many of the 8 vertex bits are set. -/
def weight (c : CellCfg) : ℕ := (List.finRange 8).countP (fun i => vbit c i)

/-- The empty cell. -/
def cell0 : CellCfg := ⟨0, by decide⟩

/-- The global complement (all 8 vertex bits flipped). -/
def cellComplement : CellCfg := ⟨255, by decide⟩

/-- One whole-face flip: the four vertices of the `z = 0` face (`{0,1,2,3}`). -/
def faceFlip : CellCfg := ⟨15, by decide⟩

/-! ## 1. The injection test: every local bulk flip posts -/

/-- **THE CELL-INJECTION TEST (the panel's question, answered positively for local
moves).** Flipping any single vertex bit of the D=3 cell changes the boundary record,
from every configuration. No single bulk distinction is unrecorded. -/
theorem single_flip_posts :
    ∀ (c : CellCfg) (i : Fin 8), faceRecord (flipv c i) ≠ faceRecord c := by decide

/-- Sharper: a single vertex flip changes EXACTLY three of the six face records — the
three faces incident to that vertex. The posting is local and quantized. -/
theorem single_flip_posts_three :
    ∀ (c : CellCfg) (i : Fin 8),
      (List.zipWith (fun a b => a != b) (faceRecord (flipv c i)) (faceRecord c)).count
        true = 3 := by decide

/-! ## 2. The record map is not injective: the blind set -/

/-- The global complement posts nothing: flipping all 8 vertices leaves every face
parity unchanged (each face has 4 flipped vertices, an even number). -/
theorem complement_invisible : faceRecord cellComplement = faceRecord cell0 := by decide

/-- **The boundary record map is NOT injective on raw bulk states.** The countermodel
of the holography paper survives at cell level unless record-equal states are
physically identified. -/
theorem record_not_injective : ¬ Function.Injective faceRecord := fun h =>
  absurd (h complement_invisible) (by decide)

/-- The **record kernel**: configurations sharing the empty cell's boundary record
(all six faces closed). These are the record-invisible states. -/
def recordKernel : Finset CellCfg :=
  Finset.univ.filter (fun c => faceRecord c = faceRecord cell0)

theorem recordKernel_card : recordKernel.card = 16 := by decide

/-- The blind set, explicitly: the rank-4 GF(2) group generated by the six whole-face
flips (`15, 51, 85, ...`), containing the global complement `255` and the two
inscribed tetrahedra `105 = {0,3,5,6}` and `150 = {1,2,4,7}`. -/
theorem recordKernel_eq :
    recordKernel =
      ({0, 15, 51, 60, 85, 90, 102, 105, 150, 153, 165, 170, 195, 204, 240, 255} :
        Finset CellCfg) := by decide

/-! ## 3. Rank-nullity of the cell record map -/

theorem record_image_card : (Finset.univ.image faceRecord).card = 16 := by decide

/-- Record rank of the whole cell: 4 posted bits (`log₂ 16`). -/
theorem record_rank_eq_four :
    Nat.log2 (Finset.univ.image faceRecord).card = 4 := by decide

/-- Record nullity of the whole cell: 4 free bits (`log₂ 16`). At whole-cell
granularity rank = nullity; the entropy fork splits only per face and under gluing. -/
theorem record_nullity_eq_four : Nat.log2 recordKernel.card = 4 := by decide

/-- First-isomorphism check of the actual cell record map:
`|image| · |kernel| = |domain|` (`16 · 16 = 256`). -/
theorem record_image_times_kernel :
    (Finset.univ.image faceRecord).card * recordKernel.card = 256 := by decide

/-! ## 4. The dichotomy: blindness is only global -/

/-- **THE DICHOTOMY (the module's headline).** Any two distinct bulk configurations
with the SAME boundary record differ on at least 4 of the 8 vertices, half the cell.
Together with `single_flip_posts`: the record misses nothing local; what it misses is
exactly a 4-bit group of cell-global parity moves. -/
theorem record_blind_only_global :
    ∀ c c' : CellCfg, faceRecord c = faceRecord c' → c ≠ c' →
      4 ≤ weight (xorCfg c c') := by decide

/-- The bound is tight, and blindness is base-independent: one whole-face flip
(weight 4) leaves the boundary record unchanged from EVERY configuration. -/
theorem face_flip_invisible_everywhere :
    ∀ c : CellCfg, faceRecord (xorCfg c faceFlip) = faceRecord c := by decide

theorem faceFlip_weight : weight faceFlip = 4 := by decide

/-- Shift-invariance classifies blindness exactly: a move `d` is invisible from every
base iff `d` lies in the record kernel. The 16 kernel elements are the complete list
of unrecorded bulk moves. -/
theorem invisible_iff_kernel :
    ∀ d : CellCfg,
      (∀ c : CellCfg, faceRecord (xorCfg c d) = faceRecord c) ↔ d ∈ recordKernel := by
  decide

/-! ## 5. Bundled target + certificate handle -/

/-- **The cell-injection bundle.** Every local flip posts (on exactly three faces);
the record map is non-injective with a 16-element blind group; rank·nullity checks;
and blindness is only global (minimum invisible weight 4). -/
def target_cell_injection : Prop :=
  (∀ (c : CellCfg) (i : Fin 8), faceRecord (flipv c i) ≠ faceRecord c)
  ∧ (∀ (c : CellCfg) (i : Fin 8),
      (List.zipWith (fun a b => a != b) (faceRecord (flipv c i)) (faceRecord c)).count
        true = 3)
  ∧ ¬ Function.Injective faceRecord
  ∧ recordKernel.card = 16
  ∧ (Finset.univ.image faceRecord).card * recordKernel.card = 256
  ∧ (∀ c c' : CellCfg, faceRecord c = faceRecord c' → c ≠ c' →
      4 ≤ weight (xorCfg c c'))

theorem target_cell_injection_holds : target_cell_injection :=
  ⟨single_flip_posts, single_flip_posts_three, record_not_injective,
   recordKernel_card, record_image_times_kernel, record_blind_only_global⟩

/-- Verify-target certificate handle for the holography loop (`#print axioms`-gated). -/
theorem cellInjectionCert : target_cell_injection := target_cell_injection_holds

end CellInjection
end Holography
end IndisputableMonolith
