import Mathlib
import IndisputableMonolith.Gravity.Analysis.EdgeTTDecomposition4D

/-!
# The continuum transverse-traceless second variation of `∫ R √g` (4D, derived)

Arc 2, step 7.  This module derives, from the Levi-Civita connection and
nothing else, the number that the Einstein-Hilbert action puts on a real
transverse-traceless plane wave, in the *same convention* the banked Regge
midpoint dictionary uses.

## Why this module exists

`ReggeExactFlatHessianNormGate4D` bridges the computed `-(1/8)` and the frozen
preflight `-(1/4)` with `discreteBookkeepingFactor := 2`, a definition with no
derivation.  Step 6 refuted the cheap explanation (that the 2 is the Frobenius
square of `axisTTPlus`) by reading both sides at a normalized polarization.  So
the honest move is to derive the continuum side independently and see which
number appears.

## Non-circularity is structural, not promised

This module imports `Mathlib` and `EdgeTTDecomposition4D` (linear algebra only,
itself importing nothing but `Mathlib`).  It does **not** import the coupling
table, the Bloch symbol, the norm gate, the preflight, or any existing
coefficient in the tree.  Nothing here can have read the answer.  The
comparison against the dictionary lives in the separate module
`ReggeNormalizationDerived4D`.

## Conventions, matched to the discrete side by reading it first

The discrete symbol (`ReggeExactFlatHessianBlochSymbol4D`, generated by
`scripts/qg/regge_4d_exact_m2_table_20260721.py`) is the unit-cell average of
`d²/dt²` of the Regge action under the **real** perturbation
`h(x) = H cos(k·x)`; the explicit `1/2` in its `couplingWeight` is the lattice
average of `cos(k·m_e) cos(k·m_e')`, which the generator states as
"real-cos = (1/2) Re(complex)".  So the object derived here is the phase
average of `d²/dt² ∫ R √g` per unit volume under the same real cosine wave,
and *not* the quadratic Taylor coefficient, which would differ by a further 2.

## Named classical inputs

* **A1** linearized Christoffel symbol `Γ⁽¹⁾_{λμν} = ½(∂_μ h_{λν} + ∂_ν h_{λμ}
  - ∂_λ h_{μν})`, the Levi-Civita connection linearized.  `linChristoffel`.
* **A2** `R⁽¹⁾_{μν} = ∂_λ Γ⁽¹⁾^λ_{μν} - ∂_ν Γ⁽¹⁾^λ_{μλ}`; the `ΓΓ` terms of the
  Ricci contraction are second order in `h` and drop.  `linRicci`.
* **A3** `d²/dt² ∫√g R = -∫ h_{μν} G⁽¹⁾^{μν}`, from Euler's theorem for a
  quadratic form together with `δ(√g R)/δg_{μν} = -√g G^{μν}`, flat space being
  a solution so the linear term vanishes.  `ehSecondVariationDensity`.

A1 and A2 are formalized here as definitions of the standard objects and every
derivative in them is *proved*, not asserted.  A3 fixes the normalization of the
density and is stated as such.  The fourth input, Regge's own normalization
`Σ_h A_h δ_h = ½ ∫ R √g`, belongs to the comparison and lives in
`ReggeNormalizationDerived4D`.

Expected axiom footprint: `[propext, Classical.choice, Quot.sound]`.
-/

namespace IndisputableMonolith
namespace Gravity
namespace Analysis
namespace ContinuumTTSecondVariation4D

open BigOperators
open EdgeTTDecomposition4D

noncomputable section

abbrev Pt := Fin 4 → ℝ

/-! ## §1. Coordinates, partial derivatives, and the plane wave -/

/-- Plane-wave phase `k · x`. -/
def phase (k x : Pt) : ℝ := ∑ i : Fin 4, k i * x i

/-- Partial derivative of a scalar field in coordinate direction `μ`. -/
def pd (μ : Fin 4) (f : Pt → ℝ) (x : Pt) : ℝ :=
  deriv (fun t : ℝ => f (Function.update x μ t)) (x μ)

/-- Frobenius square, `∑_{ij} H_{ij}²`.  Definitionally the same expression as
`ReggeExactMidpointM2TTIdentity4D.frobeniusNormSq`, restated here so this module
imports nothing from the Regge side. -/
def frobSq (H : Mat4) : ℝ := ∑ i : Fin 4, ∑ j : Fin 4, H i j * H i j

theorem phase_update (k x : Pt) (μ : Fin 4) (t : ℝ) :
    phase k (Function.update x μ t) = phase k x + k μ * (t - x μ) := by
  unfold phase
  have hterm : ∀ i : Fin 4,
      k i * Function.update x μ t i
        = k i * x i + (if i = μ then k μ * (t - x μ) else 0) := by
    intro i
    rcases eq_or_ne i μ with h | h
    · rw [h]
      have hu : Function.update x μ t μ = t := by simp
      rw [hu, if_pos rfl]
      ring
    · have hu : Function.update x μ t i = x i := by simp [h]
      rw [hu, if_neg h]
      ring
  rw [Finset.sum_congr rfl (fun i _ => hterm i), Finset.sum_add_distrib]
  simp

theorem hasDerivAt_phase_update (k x : Pt) (μ : Fin 4) :
    HasDerivAt (fun t : ℝ => phase k (Function.update x μ t)) (k μ) (x μ) := by
  have hrw : (fun t : ℝ => phase k (Function.update x μ t))
      = fun t : ℝ => phase k x + k μ * (t - x μ) :=
    funext fun t => phase_update k x μ t
  rw [hrw]
  have h1 : HasDerivAt (fun t : ℝ => t - x μ) 1 (x μ) :=
    (hasDerivAt_id (x μ)).sub_const (x μ)
  simpa using ((h1.const_mul (k μ)).const_add (phase k x))

theorem phase_update_self (k x : Pt) (μ : Fin 4) :
    phase k (Function.update x μ (x μ)) = phase k x := by
  simp

/-- Derivative of a cosine plane wave.  **Proved**, not asserted: this is the
step that carries the real-standing-wave convention into the answer. -/
theorem pd_cos (c : ℝ) (k : Pt) (μ : Fin 4) (x : Pt) :
    pd μ (fun y => c * Real.cos (phase k y)) x = -(c * k μ) * Real.sin (phase k x) := by
  have hp := hasDerivAt_phase_update k x μ
  have hcos : HasDerivAt (fun t : ℝ => Real.cos (phase k (Function.update x μ t)))
      (-Real.sin (phase k x) * k μ) (x μ) := by
    have hc := (Real.hasDerivAt_cos (phase k (Function.update x μ (x μ)))).comp (x μ) hp
    rw [phase_update_self] at hc
    exact hc
  have hmul := hcos.const_mul c
  rw [pd, hmul.deriv]
  ring

/-- Derivative of a sine plane wave. -/
theorem pd_sin (c : ℝ) (k : Pt) (μ : Fin 4) (x : Pt) :
    pd μ (fun y => c * Real.sin (phase k y)) x = (c * k μ) * Real.cos (phase k x) := by
  have hp := hasDerivAt_phase_update k x μ
  have hsin : HasDerivAt (fun t : ℝ => Real.sin (phase k (Function.update x μ t)))
      (Real.cos (phase k x) * k μ) (x μ) := by
    have hc := (Real.hasDerivAt_sin (phase k (Function.update x μ (x μ)))).comp (x μ) hp
    rw [phase_update_self] at hc
    exact hc
  have hmul := hsin.const_mul c
  rw [pd, hmul.deriv]
  ring

/-- The metric perturbation `h_{ab}(x) = H_{ab} cos(k·x)`: a **real** standing
wave, matching the discrete side's convention. -/
def hWave (H : Mat4) (k : Pt) (a b : Fin 4) (x : Pt) : ℝ :=
  H a b * Real.cos (phase k x)

/-! ## §2. A1: the linearized Christoffel symbol -/

/-- **A1.**  `Γ⁽¹⁾_{λμν} = ½(∂_μ h_{λν} + ∂_ν h_{λμ} - ∂_λ h_{μν})`, indices
raised with the flat Euclidean metric. -/
def linChristoffel (H : Mat4) (k : Pt) (l μ ν : Fin 4) (x : Pt) : ℝ :=
  (1 / 2 : ℝ) *
    (pd μ (hWave H k l ν) x + pd ν (hWave H k l μ) x - pd l (hWave H k μ ν) x)

/-- Closed-form amplitude of the linearized Christoffel symbol on the plane wave. -/
def chrAmp (H : Mat4) (k : Pt) (l μ ν : Fin 4) : ℝ :=
  (1 / 2 : ℝ) * (k l * H μ ν - k μ * H l ν - k ν * H l μ)

theorem linChristoffel_eq (H : Mat4) (k : Pt) (l μ ν : Fin 4) (x : Pt) :
    linChristoffel H k l μ ν x = chrAmp H k l μ ν * Real.sin (phase k x) := by
  unfold linChristoffel chrAmp hWave
  rw [pd_cos, pd_cos, pd_cos]
  ring

/-! ## §3. A2: the linearized Ricci tensor -/

/-- **A2.**  `R⁽¹⁾_{μν} = ∂_λ Γ⁽¹⁾^λ_{μν} - ∂_ν Γ⁽¹⁾^λ_{μλ}`.  The `ΓΓ` terms of
the full Ricci contraction are quadratic in `h` and absent at this order. -/
def linRicci (H : Mat4) (k : Pt) (μ ν : Fin 4) (x : Pt) : ℝ :=
  (∑ l : Fin 4, pd l (linChristoffel H k l μ ν) x)
    - pd ν (fun y => ∑ l : Fin 4, linChristoffel H k l μ l y) x

/-- Closed-form amplitude of the linearized Ricci tensor on the plane wave. -/
def ricciAmp (H : Mat4) (k : Pt) (μ ν : Fin 4) : ℝ :=
  (∑ l : Fin 4, k l * chrAmp H k l μ ν) - k ν * (∑ l : Fin 4, chrAmp H k l μ l)

theorem linRicci_eq (H : Mat4) (k : Pt) (μ ν : Fin 4) (x : Pt) :
    linRicci H k μ ν x = ricciAmp H k μ ν * Real.cos (phase k x) := by
  have hdiv : ∀ l : Fin 4,
      pd l (linChristoffel H k l μ ν) x
        = (chrAmp H k l μ ν * k l) * Real.cos (phase k x) := by
    intro l
    have hfun : linChristoffel H k l μ ν
        = fun y => chrAmp H k l μ ν * Real.sin (phase k y) :=
      funext fun y => linChristoffel_eq H k l μ ν y
    rw [hfun, pd_sin]
  have htracefun : (fun y => ∑ l : Fin 4, linChristoffel H k l μ l y)
      = fun y => (∑ l : Fin 4, chrAmp H k l μ l) * Real.sin (phase k y) := by
    funext y
    rw [Finset.sum_mul]
    exact Finset.sum_congr rfl fun l _ => linChristoffel_eq H k l μ l y
  unfold linRicci ricciAmp
  rw [htracefun, pd_sin, Finset.sum_congr rfl (fun l _ => hdiv l), ← Finset.sum_mul]
  rw [sub_mul]
  refine congrArg₂ (· - ·) ?_ ?_
  · exact congrArg (· * Real.cos (phase k x))
      (Finset.sum_congr rfl fun l _ => mul_comm _ _)
  · ring

/-! ## §4. The transverse-traceless reduction -/

theorem sum_k_mul_row (H : Mat4) (k : Pt) (hsym : IsSymmetric H)
    (htrans : IsTransverse k H) (ν : Fin 4) :
    ∑ l : Fin 4, k l * H l ν = 0 := by
  have h := htrans ν
  rw [← h]
  refine Finset.sum_congr rfl fun l _ => ?_
  rw [hsym l ν]
  ring

theorem sum_k_chrAmp (H : Mat4) (k : Pt) (hsym : IsSymmetric H)
    (htrans : IsTransverse k H) (μ ν : Fin 4) :
    ∑ l : Fin 4, k l * chrAmp H k l μ ν = (1 / 2 : ℝ) * momentumSq k * H μ ν := by
  have hμ := sum_k_mul_row H k hsym htrans μ
  have hν := sum_k_mul_row H k hsym htrans ν
  have hexp : ∀ l : Fin 4, k l * chrAmp H k l μ ν
      = ((1 / 2 : ℝ) * H μ ν) * (k l * k l)
        - ((1 / 2 : ℝ) * k μ) * (k l * H l ν)
        - ((1 / 2 : ℝ) * k ν) * (k l * H l μ) := by
    intro l; unfold chrAmp; ring
  rw [Finset.sum_congr rfl (fun l _ => hexp l), Finset.sum_sub_distrib,
    Finset.sum_sub_distrib, ← Finset.mul_sum, ← Finset.mul_sum, ← Finset.mul_sum, hμ, hν]
  simp only [momentumSq, mul_zero, sub_zero]
  ring

theorem sum_chrAmp_trace (H : Mat4) (k : Pt) (hsym : IsSymmetric H)
    (htr : IsTraceless H) (μ : Fin 4) :
    ∑ l : Fin 4, chrAmp H k l μ l = 0 := by
  have hexp : ∀ l : Fin 4, chrAmp H k l μ l = -(((1 / 2 : ℝ) * k μ) * H l l) := by
    intro l
    unfold chrAmp
    rw [hsym l μ]
    ring
  rw [Finset.sum_congr rfl (fun l _ => hexp l), Finset.sum_neg_distrib, ← Finset.mul_sum]
  have : ∑ l : Fin 4, H l l = 0 := htr
  rw [this]
  ring

theorem ricciAmp_tt (H : Mat4) (k : Pt) (hTT : IsTT k H) (μ ν : Fin 4) :
    ricciAmp H k μ ν = (1 / 2 : ℝ) * momentumSq k * H μ ν := by
  obtain ⟨hsym, htr, htrans⟩ := hTT
  unfold ricciAmp
  rw [sum_k_chrAmp H k hsym htrans μ ν, sum_chrAmp_trace H k hsym htr μ]
  ring

/-- On the transverse-traceless space the linearized Ricci tensor is exactly
`-(1/2) □ h`, the massless wave operator. -/
theorem linRicci_tt (H : Mat4) (k : Pt) (hTT : IsTT k H) (μ ν : Fin 4) (x : Pt) :
    linRicci H k μ ν x = (1 / 2 : ℝ) * momentumSq k * H μ ν * Real.cos (phase k x) := by
  rw [linRicci_eq, ricciAmp_tt H k hTT]

/-! ## §5. A3: the second variation density -/

/-- Ricci scalar at linear order, traced with the flat metric. -/
def linRicciScalar (H : Mat4) (k : Pt) (x : Pt) : ℝ :=
  ∑ μ : Fin 4, linRicci H k μ μ x

/-- Linearized Einstein tensor `G⁽¹⁾_{μν} = R⁽¹⁾_{μν} - ½ δ_{μν} R⁽¹⁾`. -/
def linEinstein (H : Mat4) (k : Pt) (μ ν : Fin 4) (x : Pt) : ℝ :=
  linRicci H k μ ν x
    - (1 / 2 : ℝ) * (if μ = ν then (1 : ℝ) else 0) * linRicciScalar H k x

theorem linRicciScalar_tt (H : Mat4) (k : Pt) (hTT : IsTT k H) (x : Pt) :
    linRicciScalar H k x = 0 := by
  have htr : euclideanTrace H = 0 := hTT.2.1
  unfold linRicciScalar
  rw [Finset.sum_congr rfl (fun μ _ => linRicci_tt H k hTT μ μ x)]
  have hfac : ∀ μ : Fin 4,
      (1 / 2 : ℝ) * momentumSq k * H μ μ * Real.cos (phase k x)
        = ((1 / 2 : ℝ) * momentumSq k * Real.cos (phase k x)) * H μ μ := by
    intro μ; ring
  rw [Finset.sum_congr rfl (fun μ _ => hfac μ), ← Finset.mul_sum]
  have : ∑ μ : Fin 4, H μ μ = 0 := htr
  rw [this, mul_zero]

theorem linEinstein_tt (H : Mat4) (k : Pt) (hTT : IsTT k H) (μ ν : Fin 4) (x : Pt) :
    linEinstein H k μ ν x
      = (1 / 2 : ℝ) * momentumSq k * H μ ν * Real.cos (phase k x) := by
  unfold linEinstein
  rw [linRicci_tt H k hTT, linRicciScalar_tt H k hTT]
  ring

/-- **A3.**  The second derivative of `∫ √g R` along `g = δ + t h`, as a
density: `d²/dt² ∫√g R = -∫ h_{μν} G⁽¹⁾^{μν}`.  This is Euler's theorem for a
quadratic form applied to `S⁽²⁾[h] = -½ ∫ h G⁽¹⁾`, itself
`δ(√g R)/δg_{μν} = -√g G^{μν}` expanded about flat space. -/
def ehSecondVariationDensity (H : Mat4) (k : Pt) (x : Pt) : ℝ :=
  - ∑ μ : Fin 4, ∑ ν : Fin 4, hWave H k μ ν x * linEinstein H k μ ν x

theorem ehSecondVariationDensity_tt (H : Mat4) (k : Pt) (hTT : IsTT k H) (x : Pt) :
    ehSecondVariationDensity H k x
      = -((1 / 2 : ℝ) * momentumSq k * frobSq H) * Real.cos (phase k x) ^ 2 := by
  unfold ehSecondVariationDensity hWave frobSq
  have hin : ∀ μ ν : Fin 4,
      H μ ν * Real.cos (phase k x) * linEinstein H k μ ν x
        = ((1 / 2 : ℝ) * momentumSq k * Real.cos (phase k x) ^ 2) * (H μ ν * H μ ν) := by
    intro μ ν
    rw [linEinstein_tt H k hTT]
    ring
  rw [Finset.sum_congr rfl
    (fun μ _ => Finset.sum_congr rfl (fun ν _ => hin μ ν))]
  simp only [← Finset.mul_sum]
  ring

/-! ## §6. The phase average, and the derived Einstein-Hilbert face -/

/-- Mean of a phase function over one period.  The density of §5 depends on `x`
only through `phase k x`, so for a nonzero wave covector the spatial average over
a large box equals this. -/
def phaseAverage (f : ℝ → ℝ) : ℝ :=
  (1 / (2 * Real.pi)) * ∫ θ in (0 : ℝ)..(2 * Real.pi), f θ

theorem phaseAverage_const_mul (c : ℝ) (f : ℝ → ℝ) :
    phaseAverage (fun θ => c * f θ) = c * phaseAverage f := by
  unfold phaseAverage
  rw [intervalIntegral.integral_const_mul]
  ring

/-- The mean square of a real cosine wave is `1/2`.  This is the entire content
of the discrete side's explicit `1/2`, and one of the two factors of two that
arc 2 has been unable to account for. -/
theorem phaseAverage_cos_sq : phaseAverage (fun θ => Real.cos θ ^ 2) = 1 / 2 := by
  have hpi : Real.pi ≠ 0 := Real.pi_ne_zero
  unfold phaseAverage
  rw [integral_cos_sq]
  simp only [Real.sin_two_pi, Real.cos_two_pi, Real.sin_zero, Real.cos_zero,
    mul_zero, sub_zero, sub_self]
  field_simp
  ring

/-- The density of §5, written as a function of the phase alone. -/
def densityOfPhase (H : Mat4) (k : Pt) (θ : ℝ) : ℝ :=
  -((1 / 2 : ℝ) * momentumSq k * frobSq H) * Real.cos θ ^ 2

theorem density_factors_through_phase (H : Mat4) (k : Pt) (hTT : IsTT k H) (x : Pt) :
    ehSecondVariationDensity H k x = densityOfPhase H k (phase k x) :=
  ehSecondVariationDensity_tt H k hTT x

/-- **The derived continuum Einstein-Hilbert face.**  The phase average, per unit
volume, of `d²/dt² ∫ √g R` on a real transverse-traceless cosine wave. -/
def ehFace (H : Mat4) (k : Pt) : ℝ :=
  -(1 / 4 : ℝ) * momentumSq k * frobSq H

/-- **P1.**  The derived face is the average of the derived density.  Every step
between the Levi-Civita connection and this number is proved above. -/
theorem ehFace_eq_phaseAverage (H : Mat4) (k : Pt) :
    ehFace H k = phaseAverage (densityOfPhase H k) := by
  unfold densityOfPhase ehFace
  rw [phaseAverage_const_mul, phaseAverage_cos_sq]
  ring

theorem ehFace_eq_average_of_density (H : Mat4) (k : Pt) (hTT : IsTT k H) (x : Pt) :
    ehSecondVariationDensity H k x = densityOfPhase H k (phase k x)
      ∧ ehFace H k = phaseAverage (densityOfPhase H k) :=
  ⟨density_factors_through_phase H k hTT x, ehFace_eq_phaseAverage H k⟩

/-! ## §7. Rigidity: the derivation has no free constant

Decoy T3 says a derivation with named inputs can be steered anywhere.  It cannot.
With A1 to A3 fixed, `ehFace` is a single number for each `(H, k)`, and the
statements below show it is not merely one of a family: scaling the density by
any `c ≠ 1` changes the face. -/

theorem ehFace_rigid (H : Mat4) (k : Pt) (c : ℝ)
    (hne : momentumSq k * frobSq H ≠ 0)
    (h : phaseAverage (fun θ => c * densityOfPhase H k θ) = ehFace H k) :
    c = 1 := by
  rw [phaseAverage_const_mul, ← ehFace_eq_phaseAverage] at h
  unfold ehFace at h
  have hx : c * (-(1 / 4 : ℝ) * momentumSq k * frobSq H)
      = 1 * (-(1 / 4 : ℝ) * momentumSq k * frobSq H) := by rw [h]; ring
  have hne' : (-(1 / 4 : ℝ) * momentumSq k * frobSq H) ≠ 0 := by
    intro hz
    apply hne
    have : (-(1 / 4 : ℝ)) * (momentumSq k * frobSq H) = 0 := by
      rw [← hz]; ring
    rcases mul_eq_zero.mp this with h1 | h2
    · norm_num at h1
    · exact h2
  exact mul_right_cancel₀ hne' hx

/-! ## §8. Status -/

/-- What is derived here and what is assumed, in one string, so a reader who
never saw the write-up cannot mistake the tag. -/
def provenance : String :=
  "DERIVED: linearized Christoffel (A1), linearized Ricci (A2), TT reduction, the \
plane-wave derivatives (proved from Mathlib's deriv, not asserted), the cos-squared \
mean 1/2, and the resulting face -(1/4)·|k|²·‖H‖²_F for d²/dt² of ∫R√g per unit \
volume on a real cosine wave. ASSUMED: A3, that d²/dt² ∫√gR = -∫ h·G⁽¹⁾, which is \
Euler's theorem for a quadratic form plus δ(√gR)/δg = -√g G. NOT USED ANYWHERE HERE: \
the coupling table, the Bloch symbol, the norm gate, the preflight, or any existing \
coefficient in the tree."

end

end ContinuumTTSecondVariation4D
end Analysis
end Gravity
end IndisputableMonolith
