import Mathlib
import IndisputableMonolith.Gravity.Analysis.ReggeExactFlatHessianBlochData4D
import IndisputableMonolith.Gravity.Analysis.ReggeExactFlatHessianBlochSymbol4D
import IndisputableMonolith.Gravity.Analysis.EdgeTTDecomposition4D
import IndisputableMonolith.Gravity.Analysis.ReggeExactMidpointM2TTIdentity4DKernelCert
import IndisputableMonolith.Gravity.Analysis.ReggeExactMidpointM2TTIdentity4DM2NumAssemble
import IndisputableMonolith.Gravity.Analysis.ReggeExactMidpointM2TTIdentity4DKernelGlue

/-!
# Exact midpoint Bloch m² TT identity (4D)

Closes `exact_midpoint_m2_tt_identity`.
Script: `scripts/qg/regge_4d_m2_tt_identity_20260721.py`.
Kernel upgrade: `scripts/qg/regge_4d_m2_kernel_certs_20260721.py`.
-/

namespace IndisputableMonolith
namespace Gravity
namespace Analysis
namespace ReggeExactMidpointM2TTIdentity4D

open ReggeExactFlatHessianBlochData4D
open ReggeExactFlatHessianBlochSymbol4D (exactMidpointBlochM2 edgeStrain couplingPhase
  couplingWeight couplingWeightIdx couplingPhaseIdx CouplingIdx)
open KernelCert
open KernelGlue (m2CoeffSum_eq_m2Num_div m2CoeffSum_eq_explicitM2CoeffZ
  explicitM2CoeffZ closedCoeffZ closedCoeff_eq_closedCoeffZ
  symFull_scale symFullZ_rat_explicit_eq_closed)
open EdgeTTDecomposition4D
  (IsSymmetric IsTT IsTraceless IsTransverse euclideanTrace gaugePart
    gaugePart_symmetric)
open BigOperators

set_option maxRecDepth 4096
set_option maxHeartbeats 40000000

abbrev Mat4 := Matrix (Fin 4) (Fin 4) ℝ
abbrev Wave4 := Fin 4 → ℝ

def frobeniusNormSq (E : Mat4) : ℝ :=
  ∑ i : Fin 4, ∑ j : Fin 4, E i j * E i j

def waveNormSq (k : Wave4) : ℝ :=
  ∑ i : Fin 4, k i * k i

def couplingS (coup : Coupling) : ℚ :=
  (coup.num : ℚ) / (coup.den : ℚ)

theorem couplingS_eq_s (coup : Coupling) : couplingS coup = coup.s := rfl

def deltaQ (coup : Coupling) (i : Fin 4) : ℚ :=
  (coup.delta2 i : ℚ) / 2

def m2Coeff (a b c d i j : Fin 4) : ℚ :=
  ∑ idx : CouplingIdx,
    (-(1 / 4) : ℚ) * couplingS couplingTable[idx] *
      (couplingTable[idx].De a : ℚ) * (couplingTable[idx].De b : ℚ) *
      (couplingTable[idx].Dep c : ℚ) * (couplingTable[idx].Dep d : ℚ) *
      deltaQ couplingTable[idx] i * deltaQ couplingTable[idx] j

theorem m2Coeff_eq_m2CoeffSum (a b c d i j : Fin 4) :
    m2Coeff a b c d i j = KernelGlue.m2CoeffSum a b c d i j := by
  unfold m2Coeff KernelGlue.m2CoeffSum couplingS deltaQ
  rfl

/-- Scale-32 Int table cast; kernel-checkable via `KernelCert.explicitZ`. -/
def explicitM2Coeff (a b c d i j : Fin 4) : ℚ :=
  explicitM2CoeffZ a b c d i j

/-- Array/Finset m² coefficient equals the Int fold / 256. -/
theorem m2Coeff_eq_m2Num_div (a b c d i j : Fin 4) :
    m2Coeff a b c d i j = (m2Num a b c d i j : ℚ) / 256 := by
  rw [m2Coeff_eq_m2CoeffSum, m2CoeffSum_eq_m2Num_div]

theorem m2Coeff_eq_explicitM2Coeff :
    ∀ (a b c d i j : Fin 4), m2Coeff a b c d i j = explicitM2Coeff a b c d i j := by
  intro a b c d i j
  rw [m2Coeff_eq_m2CoeffSum, explicitM2Coeff, m2CoeffSum_eq_explicitM2CoeffZ]

/-! ## S3. Symmetrized coefficient certificate -/

/-- Closed-form coefficient table: Frobenius + load + trace^2 + trace-quadratic
pieces of `closedForm`, written per matrix index. -/
def closedCoeff (a b c d i j : Fin 4) : ℚ :=
  (if a = c ∧ b = d ∧ i = j then -(1 / 8) else 0) +
    (if a = c ∧ b = i ∧ d = j then (1 / 4) else 0) +
    (if a = b ∧ c = d ∧ i = j then (1 / 8) else 0) +
    (if a = b ∧ c = i ∧ d = j then -(1 / 4) else 0)

/-- Average over the `(a,b)`- and `(c,d)`-flips. -/
def sym4C (C : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℚ)
    (a b c d i j : Fin 4) : ℚ :=
  (C a b c d i j + C b a c d i j + C a b d c i j + C b a d c i j) / 4

/-- Average over the pair exchange `(a,b) ←> (c,d)`. -/
def sym2exC (C : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℚ)
    (a b c d i j : Fin 4) : ℚ :=
  (C a b c d i j + C c d a b i j) / 2

/-- Full bi-quadratic symmetrization (order-8 group generated by the two
flips and the pair exchange). -/
def symFull (C : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℚ)
    (a b c d i j : Fin 4) : ℚ :=
  sym2exC (sym4C C) a b c d i j

/-- Certificate: the symmetrizations of the explicit m^2 table and of the
closed-form coefficient table agree pointwise (4096 rational identities). -/
theorem closedCoeff_eq_closedCoeffZ_pointwise :
    ∀ a b c d i j : Fin 4,
      closedCoeff a b c d i j = closedCoeffZ a b c d i j := by
  intro a b c d i j
  simpa [closedCoeff] using closedCoeff_eq_closedCoeffZ a b c d i j

private theorem symFull_eq_symFullZ_div
    (C : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Int)
    (D : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℚ)
    (hD : ∀ a b c d i j, D a b c d i j = (C a b c d i j : ℚ) / 32)
    (a b c d i j : Fin 4) :
    symFull D a b c d i j = (symFullZ C a b c d i j : ℚ) / 32 := by
  unfold symFull sym2exC sym4C
  simp only [hD]
  exact symFull_scale C a b c d i j

theorem symFull_explicit_eq_symFull_closed :
    ∀ a b c d i j : Fin 4,
      symFull explicitM2Coeff a b c d i j = symFull closedCoeff a b c d i j := by
  intro a b c d i j
  have hE : ∀ a b c d i j,
      explicitM2Coeff a b c d i j = (explicitZ a b c d i j : ℚ) / 32 := by
    intro a b c d i j; rfl
  have hC : ∀ a b c d i j,
      closedCoeff a b c d i j = (closedZ a b c d i j : ℚ) / 32 :=
    closedCoeff_eq_closedCoeffZ_pointwise
  rw [symFull_eq_symFullZ_div explicitZ explicitM2Coeff hE,
      symFull_eq_symFullZ_div closedZ closedCoeff hC,
      symFullZ_rat_explicit_eq_closed]


/-! ## S4. ℝ-bridge: bi-quadratic form and sum relabelings -/

noncomputable section

/-- Generic bi-quadratic form: quadratic in `H` entries, quadratic in `k`. -/
def biquad (C : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℚ)
    (H : Mat4) (k : Wave4) : ℝ :=
  ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
    ((C a b c d i j : ℚ) : ℝ) * H a b * H c d * k i * k j

theorem biquad_congr {C1 C2 : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℚ}
    (h : ∀ a b c d i j : Fin 4, C1 a b c d i j = C2 a b c d i j)
    (H : Mat4) (k : Wave4) : biquad C1 H k = biquad C2 H k := by
  unfold biquad
  refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ =>
    Finset.sum_congr rfl fun c _ => Finset.sum_congr rfl fun d _ =>
    Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
  rw [h]

private theorem sum2_mul (P : Fin 4 → Fin 4 → ℝ) (X : ℝ) :
    (∑ a : Fin 4, ∑ b : Fin 4, P a b) * X =
      ∑ a : Fin 4, ∑ b : Fin 4, P a b * X := by
  rw [Finset.sum_mul]
  exact Finset.sum_congr rfl fun a _ => Finset.sum_mul _ _ _

private theorem triple_double_sum_mul (P Q3 R3 : Fin 4 → Fin 4 → ℝ) (c0 : ℝ) :
    c0 * (∑ a : Fin 4, ∑ b : Fin 4, P a b) * (∑ c : Fin 4, ∑ d : Fin 4, Q3 c d) *
        (∑ i : Fin 4, ∑ j : Fin 4, R3 i j) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        c0 * P a b * Q3 c d * R3 i j := by
  have h1 : c0 * (∑ a : Fin 4, ∑ b : Fin 4, P a b) * (∑ c : Fin 4, ∑ d : Fin 4, Q3 c d) *
      (∑ i : Fin 4, ∑ j : Fin 4, R3 i j) =
      (∑ a : Fin 4, ∑ b : Fin 4, P a b) *
        ((∑ c : Fin 4, ∑ d : Fin 4, Q3 c d) *
          ((∑ i : Fin 4, ∑ j : Fin 4, R3 i j) * c0)) := by ring
  rw [h1, sum2_mul]
  refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ => ?_
  have h2 : P a b * ((∑ c : Fin 4, ∑ d : Fin 4, Q3 c d) *
      ((∑ i : Fin 4, ∑ j : Fin 4, R3 i j) * c0)) =
      (∑ c : Fin 4, ∑ d : Fin 4, Q3 c d) *
        ((∑ i : Fin 4, ∑ j : Fin 4, R3 i j) * (c0 * P a b)) := by ring
  rw [h2, sum2_mul]
  refine Finset.sum_congr rfl fun c _ => Finset.sum_congr rfl fun d _ => ?_
  have h3 : Q3 c d * ((∑ i : Fin 4, ∑ j : Fin 4, R3 i j) * (c0 * P a b)) =
      (∑ i : Fin 4, ∑ j : Fin 4, R3 i j) * (c0 * P a b * Q3 c d) := by
    ring
  rw [h3, sum2_mul]
  refine Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
  ring

private theorem term_expand (H : Mat4) (k : Wave4) (idx : CouplingIdx) :
    couplingWeightIdx H idx * (-(couplingPhaseIdx k idx) ^ 2 / 2) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        (((-(1 / 4) : ℚ) * couplingS couplingTable[idx] *
            (couplingTable[idx].De a : ℚ) * (couplingTable[idx].De b : ℚ) *
            (couplingTable[idx].Dep c : ℚ) * (couplingTable[idx].Dep d : ℚ) *
            deltaQ couplingTable[idx] i * deltaQ couplingTable[idx] j : ℚ) : ℝ) *
          H a b * H c d * k i * k j := by
  unfold couplingWeightIdx couplingPhaseIdx
  generalize couplingTable[idx] = t
  have h0 : couplingWeight H t * (-(couplingPhase t k) ^ 2 / 2) =
      (-(1 / 4) * (t.s : ℝ)) * edgeStrain H t.De * edgeStrain H t.Dep *
        (couplingPhase t k * couplingPhase t k) := by
    unfold couplingWeight
    ring
  rw [h0]
  unfold edgeStrain couplingPhase
  rw [Finset.sum_mul_sum]
  rw [triple_double_sum_mul]
  refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ =>
    Finset.sum_congr rfl fun c _ => Finset.sum_congr rfl fun d _ =>
    Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
  simp only [couplingS, deltaQ, Coupling.s, Coupling.delta]
  push_cast
  ring

/-- Expansion of the 1208-coupling m^2 sum as a bi-quadratic with the
`m2Coeff` coefficient table. -/
theorem exactMidpointBlochM2_eq_biquad (H : Mat4) (k : Wave4) :
    exactMidpointBlochM2 H k = biquad m2Coeff H k := by
  unfold exactMidpointBlochM2 biquad
  refine (Finset.sum_congr rfl fun idx _ => term_expand H k idx).trans ?_
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun b _ => ?_
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun c _ => ?_
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun d _ => ?_
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun j _ => ?_
  have hcast : ((m2Coeff a b c d i j : ℚ) : ℝ) =
      ∑ idx : CouplingIdx,
        (((-(1 / 4) : ℚ) * couplingS couplingTable[idx] *
            (couplingTable[idx].De a : ℚ) * (couplingTable[idx].De b : ℚ) *
            (couplingTable[idx].Dep c : ℚ) * (couplingTable[idx].Dep d : ℚ) *
            deltaQ couplingTable[idx] i * deltaQ couplingTable[idx] j : ℚ) : ℝ) := by
    unfold m2Coeff
    exact Rat.cast_sum _ _
  rw [hcast, Finset.sum_mul, Finset.sum_mul, Finset.sum_mul, Finset.sum_mul]

/-! Sum relabeling lemmas (pure index bookkeeping). -/

private theorem sum6_flip_ab (F : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℝ) :
    (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        F a b c d i j) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        F b a c d i j :=
  Finset.sum_comm

private theorem sum6_flip_cd (F : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℝ) :
    (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        F a b c d i j) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        F a b d c i j := by
  refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ => ?_
  exact Finset.sum_comm

private theorem sum4_exchange (G : Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℝ) :
    (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, G a b c d) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, G c d a b := by
  have h : ∀ P : Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℝ,
      (∑ x : Fin 4 × Fin 4, ∑ y : Fin 4 × Fin 4, P x.1 x.2 y.1 y.2) =
        ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, P a b c d := by
    intro P
    rw [Fintype.sum_prod_type]
    refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ => ?_
    rw [Fintype.sum_prod_type]
  have h1 := h G
  have h2 : (∑ x : Fin 4 × Fin 4, ∑ y : Fin 4 × Fin 4, G y.1 y.2 x.1 x.2) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, G c d a b :=
    h fun a b c d => G c d a b
  rw [← h1, ← h2]
  exact Finset.sum_comm

private theorem sum6_exchange (F : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℝ) :
    (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        F a b c d i j) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        F c d a b i j :=
  sum4_exchange fun a b c d => ∑ i : Fin 4, ∑ j : Fin 4, F a b c d i j

/-! Symmetrization invariance of the bi-quadratic form. -/

theorem biquad_sym4 (C : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℚ)
    (H : Mat4) (k : Wave4) (hsym : IsSymmetric H) :
    biquad (sym4C C) H k = biquad C H k := by
  have hba : (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
      ((C b a c d i j : ℚ) : ℝ) * H a b * H c d * k i * k j) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        ((C a b c d i j : ℚ) : ℝ) * H a b * H c d * k i * k j := by
    have h1 : (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        ((C b a c d i j : ℚ) : ℝ) * H a b * H c d * k i * k j) =
        ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
          ((C a b c d i j : ℚ) : ℝ) * H b a * H c d * k i * k j :=
      sum6_flip_ab fun x y c d i j => ((C y x c d i j : ℚ) : ℝ) * H x y * H c d * k i * k j
    rw [h1]
    refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ =>
      Finset.sum_congr rfl fun c _ => Finset.sum_congr rfl fun d _ =>
      Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
    rw [hsym b a]
  have hdc : (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
      ((C a b d c i j : ℚ) : ℝ) * H a b * H c d * k i * k j) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        ((C a b c d i j : ℚ) : ℝ) * H a b * H c d * k i * k j := by
    have h1 : (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        ((C a b d c i j : ℚ) : ℝ) * H a b * H c d * k i * k j) =
        ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
          ((C a b c d i j : ℚ) : ℝ) * H a b * H d c * k i * k j :=
      sum6_flip_cd fun a b x y i j => ((C a b y x i j : ℚ) : ℝ) * H a b * H x y * k i * k j
    rw [h1]
    refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ =>
      Finset.sum_congr rfl fun c _ => Finset.sum_congr rfl fun d _ =>
      Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
    rw [hsym d c]
  have hbadc : (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
      ((C b a d c i j : ℚ) : ℝ) * H a b * H c d * k i * k j) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        ((C a b c d i j : ℚ) : ℝ) * H a b * H c d * k i * k j := by
    have h1 : (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        ((C b a d c i j : ℚ) : ℝ) * H a b * H c d * k i * k j) =
        ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
          ((C a b d c i j : ℚ) : ℝ) * H b a * H c d * k i * k j :=
      sum6_flip_ab fun x y c d i j => ((C y x d c i j : ℚ) : ℝ) * H x y * H c d * k i * k j
    have h2 : (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        ((C a b d c i j : ℚ) : ℝ) * H b a * H c d * k i * k j) =
        ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
          ((C a b c d i j : ℚ) : ℝ) * H b a * H d c * k i * k j :=
      sum6_flip_cd fun a b x y i j => ((C a b y x i j : ℚ) : ℝ) * H b a * H x y * k i * k j
    rw [h1, h2]
    refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ =>
      Finset.sum_congr rfl fun c _ => Finset.sum_congr rfl fun d _ =>
      Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
    rw [hsym b a, hsym d c]
  unfold biquad sym4C
  have expand : ∀ a b c d i j : Fin 4,
      (((C a b c d i j + C b a c d i j + C a b d c i j + C b a d c i j) / 4 : ℚ) : ℝ) *
          H a b * H c d * k i * k j =
        (((C a b c d i j : ℚ) : ℝ) * H a b * H c d * k i * k j +
            ((C b a c d i j : ℚ) : ℝ) * H a b * H c d * k i * k j +
            ((C a b d c i j : ℚ) : ℝ) * H a b * H c d * k i * k j +
            ((C b a d c i j : ℚ) : ℝ) * H a b * H c d * k i * k j) / 4 := by
    intro a b c d i j
    push_cast
    ring
  simp_rw [expand, ← Finset.sum_div, Finset.sum_add_distrib]
  rw [hba, hdc, hbadc]
  ring

theorem biquad_sym2ex (D : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℚ)
    (H : Mat4) (k : Wave4) :
    biquad (sym2exC D) H k = biquad D H k := by
  have hex : (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
      ((D c d a b i j : ℚ) : ℝ) * H a b * H c d * k i * k j) =
      ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        ((D a b c d i j : ℚ) : ℝ) * H a b * H c d * k i * k j := by
    have h1 : (∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
        ((D a b c d i j : ℚ) : ℝ) * H c d * H a b * k i * k j) =
        ∑ a : Fin 4, ∑ b : Fin 4, ∑ c : Fin 4, ∑ d : Fin 4, ∑ i : Fin 4, ∑ j : Fin 4,
          ((D c d a b i j : ℚ) : ℝ) * H a b * H c d * k i * k j :=
      sum6_exchange fun a b c d i j => ((D a b c d i j : ℚ) : ℝ) * H c d * H a b * k i * k j
    rw [← h1]
    refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun b _ =>
      Finset.sum_congr rfl fun c _ => Finset.sum_congr rfl fun d _ =>
      Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
    ring
  unfold biquad sym2exC
  have expand : ∀ a b c d i j : Fin 4,
      (((D a b c d i j + D c d a b i j) / 2 : ℚ) : ℝ) * H a b * H c d * k i * k j =
        (((D a b c d i j : ℚ) : ℝ) * H a b * H c d * k i * k j +
            ((D c d a b i j : ℚ) : ℝ) * H a b * H c d * k i * k j) / 2 := by
    intro a b c d i j
    push_cast
    ring
  simp_rw [expand, ← Finset.sum_div, Finset.sum_add_distrib]
  rw [hex]
  ring

theorem biquad_symFull (C : Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → Fin 4 → ℚ)
    (H : Mat4) (k : Wave4) (hsym : IsSymmetric H) :
    biquad (symFull C) H k = biquad C H k := by
  have h1 : biquad (symFull C) H k = biquad (sym4C C) H k :=
    biquad_sym2ex (sym4C C) H k
  exact h1.trans (biquad_sym4 C H k hsym)

/-! ## S5. Closed form -/

def loadNormSq (H : Mat4) (k : Wave4) : ℝ :=
  ∑ m : Fin 4, (∑ n : Fin 4, H m n * k n) ^ 2

def quadraticForm (H : Mat4) (k : Wave4) : ℝ :=
  ∑ i : Fin 4, ∑ j : Fin 4, k i * H i j * k j

def closedForm (H : Mat4) (k : Wave4) : ℝ :=
  (-(1 / 8) : ℝ) * frobeniusNormSq H * waveNormSq k +
    (1 / 4 : ℝ) * loadNormSq H k +
    (1 / 8 : ℝ) * euclideanTrace H *
      (euclideanTrace H * waveNormSq k - 2 * quadraticForm H k)

/-- The closed-coefficient bi-quadratic reproduces `closedForm` for every `H`
(not only symmetric ones): each ite piece collapses to its invariant. -/
theorem biquad_closedCoeff_eq_closedForm (H : Mat4) (k : Wave4) :
    biquad closedCoeff H k = closedForm H k := by
  unfold biquad closedCoeff closedForm frobeniusNormSq waveNormSq loadNormSq
    quadraticForm euclideanTrace
  simp only [Rat.cast_add, apply_ite ((↑) : ℚ → ℝ), Rat.cast_neg,
    Rat.cast_div, Rat.cast_one, Rat.cast_ofNat, Rat.cast_zero,
    add_mul, ite_mul, zero_mul, Finset.sum_add_distrib, ite_and,
    Finset.sum_ite_irrel, Finset.sum_const_zero, Finset.sum_ite_eq,
    Finset.mem_univ, if_true]
  simp only [Fin.sum_univ_four]
  ring

/-! ## S6. Main chain and TT identity -/

theorem exactMidpointBlochM2_eq_closedForm_of_symmetric
    (H : Mat4) (k : Wave4) (hsym : IsSymmetric H) :
    exactMidpointBlochM2 H k = closedForm H k := by
  calc
    exactMidpointBlochM2 H k = biquad m2Coeff H k :=
      exactMidpointBlochM2_eq_biquad H k
    _ = biquad explicitM2Coeff H k :=
      biquad_congr m2Coeff_eq_explicitM2Coeff H k
    _ = biquad (symFull explicitM2Coeff) H k :=
      (biquad_symFull explicitM2Coeff H k hsym).symm
    _ = biquad (symFull closedCoeff) H k :=
      biquad_congr symFull_explicit_eq_symFull_closed H k
    _ = biquad closedCoeff H k := biquad_symFull closedCoeff H k hsym
    _ = closedForm H k := biquad_closedCoeff_eq_closedForm H k

theorem closedForm_eq_neg_eighth_of_TT
    (H : Mat4) (k : Wave4) (hTT : IsTT k H) :
    closedForm H k = (-(1 / 8) : ℝ) * frobeniusNormSq H * waveNormSq k := by
  rcases hTT with ⟨_, htr, htrans⟩
  unfold closedForm
  have hload : loadNormSq H k = 0 := by
    unfold loadNormSq
    refine Finset.sum_eq_zero fun m _ => by simp [htrans m]
  rw [htr, hload]
  ring

/-- **Typed blocker `exact_midpoint_m2_tt_identity`, closed.**  For TT pairs
the exact midpoint Bloch m^2 equals `-(1/8) |H|_F^2 |k|^2`. -/
theorem exactMidpointBlochM2_eq_neg_eighth_frobenius_tt
    (H : Mat4) (k : Wave4) (hTT : IsTT k H) :
    exactMidpointBlochM2 H k =
      (-(1 / 8) : ℝ) * frobeniusNormSq H * waveNormSq k := by
  rw [exactMidpointBlochM2_eq_closedForm_of_symmetric H k hTT.1,
    closedForm_eq_neg_eighth_of_TT H k hTT]


/-- Unit-Frobenius TT Rayleigh face `-1/8`. -/
theorem exactMidpointBlochM2_rayleigh_eq_neg_eighth_of_TT
    (H : Mat4) (k : Wave4) (hTT : IsTT k H)
    (hF : frobeniusNormSq H = 1) (hk : waveNormSq k ≠ 0) :
    exactMidpointBlochM2 H k / waveNormSq k = (-(1 / 8) : ℝ) := by
  rw [exactMidpointBlochM2_eq_neg_eighth_frobenius_tt H k hTT, hF]
  field_simp [hk]

/-- Algebraic identity: closed form of a pure gauge pair is identically zero. -/
theorem closedForm_gaugePart_eq_zero (m v : Wave4) :
    closedForm (gaugePart m v) m = 0 := by
  unfold closedForm frobeniusNormSq waveNormSq loadNormSq quadraticForm
    euclideanTrace gaugePart
  simp only [Fin.sum_univ_four]
  ring

/-- Exact midpoint Bloch m² vanishes on pure gauge pairs. -/
theorem exactMidpointBlochM2_eq_zero_of_gaugePart (m v : Wave4) :
    exactMidpointBlochM2 (gaugePart m v) m = 0 := by
  rw [exactMidpointBlochM2_eq_closedForm_of_symmetric
      (gaugePart m v) m (gaugePart_symmetric m v),
    closedForm_gaugePart_eq_zero]

/-- Alias kept for packing-route name compatibility. -/
theorem exactMidpointBlochM2_gaugePart_eq_zero (m v : Wave4) :
    exactMidpointBlochM2 (gaugePart m v) m = 0 :=
  exactMidpointBlochM2_eq_zero_of_gaugePart m v

/-- Pure-gauge Rayleigh quotient is zero when the mode is nonzero. -/
theorem exactMidpointBlochM2_gauge_rayleigh_eq_zero
    (m v : Wave4) (_hm : waveNormSq m ≠ 0) :
    exactMidpointBlochM2 (gaugePart m v) m / waveNormSq m = 0 := by
  rw [exactMidpointBlochM2_eq_zero_of_gaugePart, zero_div]

/-- Packaged TT/gauge m² faces used by residual R3. -/
theorem exactMidpointBlochM2_faces :
    (∀ (H : Mat4) (k : Wave4),
        IsTT k H →
          frobeniusNormSq H = 1 →
            waveNormSq k ≠ 0 →
              exactMidpointBlochM2 H k / waveNormSq k = (-(1 / 8) : ℝ)) ∧
      (∀ (m v : Wave4),
        waveNormSq m ≠ 0 →
          exactMidpointBlochM2 (gaugePart m v) m / waveNormSq m = 0) :=
  ⟨exactMidpointBlochM2_rayleigh_eq_neg_eighth_of_TT,
    exactMidpointBlochM2_gauge_rayleigh_eq_zero⟩

def ExactMidpointM2TTIdentityProved : Bool := true
theorem exactMidpointM2TTIdentityProved_true :
    ExactMidpointM2TTIdentityProved = true := rfl

end

end ReggeExactMidpointM2TTIdentity4D
end Analysis
end Gravity
end IndisputableMonolith
