import IndisputableMonolith.Gravity.Analysis.ReggeBlochTransportedAllOrbitM2Eval4D

/-!
# Audit: transported all-orbit m² evaluation certificates
-/

open IndisputableMonolith.Gravity.Analysis.ReggeBlochTransportedAllOrbitM2Eval4D

#print axioms m2TransportedAllOrbitMoment_axisTTPlus_symbolDir
#print axioms M2TransportedAllOrbitAxisSymbolDirEvalOpen_holds
#print axioms m2TransportedAllOrbitMoment_decoyGauge_symbolDir
#print axioms m2TransportedAllOrbitMomentDistinctHinge_axisTTPlus_symbolDir
#print axioms M2DistinctHingeAxisSymbolDirEvalOpen_holds
#print axioms m2TransportedAllOrbitMomentDistinctHinge_decoyGauge_symbolDir
#print axioms m2TransportedAllOrbitMomentDistinctHinge_axisTTPlusNormalized_symbolDir
#print axioms m2TransportedAllOrbitMoment_axisTTCross_symbolDir
#print axioms m2TransportedAllOrbitMomentDistinctHinge_axisTTCross_symbolDir
#print axioms M2DistinctHingeAxisTTCrossSymbolDirEvalOpen_holds
#print axioms m2TransportedAllOrbitMomentDistinctHinge_axisTTCrossNormalized_symbolDir
#print axioms m2TransportedDistinctHinge_plus_cross_normalized_agree_symbolDir
#print axioms m2TransportedOrbitMoment_t11_axis
#print axioms m2TransportedOrbitMoment_t12_axis
#print axioms m2TransportedOrbitMoment_t13_axis
#print axioms m2TransportedOrbitMoment_t21_axis
#print axioms m2TransportedOrbitMoment_t22_axis
#print axioms m2TransportedOrbitMoment_t31_axis
#print axioms m2TransportedOrbitMoment_t11_cross
#print axioms m2TransportedOrbitMoment_t12_cross
#print axioms m2TransportedOrbitMoment_t13_cross
#print axioms m2TransportedOrbitMoment_t21_cross
#print axioms m2TransportedOrbitMoment_t22_cross
#print axioms m2TransportedOrbitMoment_t31_cross
#print axioms m2TransportedAllOrbitMomentDistinctHinge_axisTTPlus_e0Dir
#print axioms m2TransportedAllOrbitMomentDistinctHinge_axisTTCross_e0Dir
#print axioms m2TransportedAllOrbitMomentDistinctHinge_axisTTPlusNormalized_e0Dir
#print axioms m2TransportedAllOrbitMomentDistinctHinge_axisTTCrossNormalized_e0Dir
#print axioms Regge4DContinuumIsotropyBlockedOnAxisMode_status_false
#print axioms axis_mode_plus_cross_disagree_e0Dir
#print axioms phaseScaleDir_e0Dir
#print axioms e0Dir_normSq
#print axioms slotOrbitKerDot_axisTTPlus
#print axioms slotOrbitKerDot_axisTTCross
#print axioms m2TransportedOrbitSlotCoeffFull_eq_trunc_axisTTPlus
#print axioms m2TransportedOrbitSlotCoeffFull_eq_trunc_axisTTCross
#print axioms m2TransportedAllOrbitMomentDistinctHingeFull_eq_trunc_axisTTPlus
#print axioms m2TransportedAllOrbitMomentDistinctHingeFull_eq_trunc_axisTTCross
#print axioms m2TransportedAllOrbitMomentDistinctHingeFull_axisTTPlus_e0Dir
#print axioms m2TransportedAllOrbitMomentDistinctHingeFull_axisTTCross_e0Dir
#print axioms m2TransportedAllOrbitMomentDistinctHingeFull_axisTTPlus_symbolDir
#print axioms m2TransportedAllOrbitMomentDistinctHingeFull_axisTTCross_symbolDir
#print axioms full_twojet_does_not_repair_e0_anisotropy
#print axioms Regge4DFullTwoJetRestoresE0PlusVanishing_status_false
#print axioms Regge4DFullTwoJetRestoresE0Isotropy_status_false
#print axioms continuumFace_fullTwoJet_normalizedCross_e0Dir
#print axioms full_twojet_does_not_flip_gap_action_recovery
#print axioms reggeBlochFullTwoJetM2Eval4DStatus_flags
