import Mathlib
import IndisputableMonolith.Constants
import IndisputableMonolith.Mathematics.HodgeConjecture
import IndisputableMonolith.Mathematics.HodgeHarmonicForms

/-!
# Hodge Hard Direction — Proof Assembly

This module assembles the hard direction of the RS Hodge Conjecture:

    Every CoarseGrainingStableClass is generated by JCostMinimalCycles.

## Proof Chain

The hard direction is proved under two conditions:

**Case A** (zero-limit ledger): If the DefectBoundedSubLedger's coarse-graining
flow limit is 0, then every stable class has z_charge = 0, hence is generated
by a zero-defect JCostMinimalCycle. (PROVED below)

**Case B** (general): The full hard direction requires showing that ANY stable
class (not just z_charge = 0) decomposes into minimal cycles. This uses the
Hodge decomposition theorem (PROVED for defect ≤ 1 ledgers).

**Case C** (unrestricted): The general RSHodgeConjecture requires showing that
the sum of minimal cycle z_charges equals cls.z_charge. Since all minimal cycles
have z_charge = 0 or ≤ 1, the sum is 0 for a finite list, which only works when
cls.z_charge = 0. The full conjecture for positive z_charge is therefore:

    cls.z_charge > 0 → cls is generated by rational combinations of minimal cycles
    with possibly fractional coefficients.

This requires extending the definition of "generated" to rational combinations.
That extension is left for `HodgeConjecture.lean` §RSHodgeConjectureGeneral.

-/

namespace IndisputableMonolith
namespace Mathematics
namespace HodgeHardDirection

open HodgeConjecture HodgeHarmonicForms Foundation.LedgerForcing

/-! ## Case A: Zero-Limit Ledger (Full Hard Direction) -/

/-- **The Hard Direction — Case A**: For "asymptotically trivial" sub-ledgers
    (those whose coarse-graining flow converges to 0), the Hodge conjecture holds fully.

    This is the main case relevant to the RS framework, where "asymptotic triviality"
    means the sub-ledger is in a ground state (no persistent cost defects). -/
theorem hodge_hard_direction_case_A (L : DefectBoundedSubLedger)
    (h_trivial : ∀ (cgf : CoarseGrainingFlow L), flowLimit cgf = 0) :
    ∀ cls : CoarseGrainingStableClass L,
      ∃ cycles : List (JCostMinimalCycle L),
        cls.z_charge = (cycles.map (fun c => c.cycle_class.z_charge)).sum := by
  intro cls
  -- The defect budget theorem gives cls.z_charge = 0
  have h_all_flows : ∀ cgf : CoarseGrainingFlow L, IsFlowStable L cgf cls := by
    intro cgf
    unfold IsFlowStable
    have hdef_zero : L.defect = 0 := by
      simpa [flowLimit, trivialFlow] using h_trivial (trivialFlow L)
    have hz_le_zero : cls.z_charge ≤ 0 := by
      simpa [hdef_zero] using cls.dpi_stable
    rw [h_trivial cgf]
    exact hz_le_zero
  have h_zero := defect_budget_theorem L cls h_trivial h_all_flows
  -- Construct a single minimal cycle with z_charge = 0
  obtain ⟨cyc, hcyc⟩ := harmonic_form_theorem_zero_charge L cls h_zero
  use [cyc]
  simp [hcyc]

/-! ## Case B: Defect ≤ 1 Ledgers -/

/-- **The Hard Direction — Case B**: For sub-ledgers with defect ≤ 1,
    every stable class is generated by a single minimal cycle. -/
theorem hodge_hard_direction_case_B (L : DefectBoundedSubLedger) (h : L.defect ≤ 1) :
    ∀ cls : CoarseGrainingStableClass L,
      ∃ cycles : List (JCostMinimalCycle L),
        cls.z_charge = (cycles.map (fun c => c.cycle_class.z_charge)).sum := by
  intro cls
  -- The stable class has z_charge ≤ L.defect ≤ 1
  -- By harmonic form theorem for minimal ledgers, it's generated by a single cycle
  obtain ⟨cyc, hcyc⟩ := harmonic_form_theorem_minimal_ledger L h cls
  use [cyc]
  simp [hcyc]

/-! ## The Full RSHodgeConjecture for Special Cases -/

/-- **The RSHodgeConjecture holds for asymptotically trivial sub-ledgers.** -/
theorem rs_hodge_holds_for_trivial_ledgers :
    ∀ (L : DefectBoundedSubLedger),
      (∀ cgf : CoarseGrainingFlow L, flowLimit cgf = 0) →
      ∀ cls : CoarseGrainingStableClass L,
        ∃ cycles : List (JCostMinimalCycle L),
          cls.z_charge = (cycles.map (fun c => c.cycle_class.z_charge)).sum :=
  fun L h cls => hodge_hard_direction_case_A L h cls

/-- **The RSHodgeConjecture holds for unit-defect sub-ledgers.** -/
theorem rs_hodge_holds_for_unit_defect :
    ∀ (L : DefectBoundedSubLedger), L.defect ≤ 1 →
      ∀ cls : CoarseGrainingStableClass L,
        ∃ cycles : List (JCostMinimalCycle L),
          cls.z_charge = (cycles.map (fun c => c.cycle_class.z_charge)).sum :=
  fun L h cls => hodge_hard_direction_case_B L h cls

/-! ## Comparison with Classical Hodge -/

/-- The RS proof works because:
    1. For zero z_charge: trivially generated by a single zero-defect cycle
    2. For nonzero z_charge: requires rational combinations (general case)

    Classical Hodge works because harmonic forms provide unique representatives.
    The RS analog (defect budget = "energy minimization") achieves the same result
    for the special cases above.

    The remaining gap for the full RSHodgeConjecture: handle z_charge > 1 without
    the defect ≤ 1 assumption. This requires a recursive cycle decomposition. -/
theorem hodge_hard_direction_summary :
    -- Case A: zero-limit
    (∀ L : DefectBoundedSubLedger,
      (∀ cgf : CoarseGrainingFlow L, flowLimit cgf = 0) →
      ∀ cls : CoarseGrainingStableClass L,
        ∃ cycles : List (JCostMinimalCycle L),
          cls.z_charge = (cycles.map (fun c => c.cycle_class.z_charge)).sum) ∧
    -- Case B: unit defect
    (∀ L : DefectBoundedSubLedger, L.defect ≤ 1 →
      ∀ cls : CoarseGrainingStableClass L,
        ∃ cycles : List (JCostMinimalCycle L),
          cls.z_charge = (cycles.map (fun c => c.cycle_class.z_charge)).sum) :=
  ⟨rs_hodge_holds_for_trivial_ledgers, rs_hodge_holds_for_unit_defect⟩

/-! ## Hard Direction Certificate -/

structure HodgeSpecialCaseDirectionsWitness where
  case_A_available : ∀ L : DefectBoundedSubLedger,
    (∀ cgf : CoarseGrainingFlow L, flowLimit cgf = 0) →
    ∀ cls : CoarseGrainingStableClass L,
      ∃ cycles : List (JCostMinimalCycle L),
        cls.z_charge = (cycles.map (fun c => c.cycle_class.z_charge)).sum
  case_B_available : ∀ L : DefectBoundedSubLedger, L.defect ≤ 1 →
    ∀ cls : CoarseGrainingStableClass L,
      ∃ cycles : List (JCostMinimalCycle L),
        cls.z_charge = (cycles.map (fun c => c.cycle_class.z_charge)).sum

structure HodgeHardCert where
  /-- Case A proved -/
  case_A : ∀ L : DefectBoundedSubLedger,
    (∀ cgf : CoarseGrainingFlow L, flowLimit cgf = 0) →
    ∀ cls : CoarseGrainingStableClass L,
      ∃ cycles : List (JCostMinimalCycle L),
        cls.z_charge = (cycles.map (fun c => c.cycle_class.z_charge)).sum
  /-- Case B proved -/
  case_B : ∀ L : DefectBoundedSubLedger, L.defect ≤ 1 →
    ∀ cls : CoarseGrainingStableClass L,
      ∃ cycles : List (JCostMinimalCycle L),
        cls.z_charge = (cycles.map (fun c => c.cycle_class.z_charge)).sum
  /-- Both directions together (full Hodge for special cases) -/
  both_directions : HodgeSpecialCaseDirectionsWitness

def hodgeHardCert : HodgeHardCert where
  case_A := rs_hodge_holds_for_trivial_ledgers
  case_B := rs_hodge_holds_for_unit_defect
  both_directions := {
    case_A_available := rs_hodge_holds_for_trivial_ledgers
    case_B_available := rs_hodge_holds_for_unit_defect
  }

end HodgeHardDirection
end Mathematics
end IndisputableMonolith
