/-
# Gauge orbit composition from real characters

The proposed odd-power classification has a degenerate boundary member. The
anchor-free structural ledger admits the sign character, whose value on every
positive rational is one and whose exponent is zero. Its generated cost is zero
on positive ratios, minus two on negative ratios, and minus one at zero.

This module packages the structural-to-real-factorization bridge and proves
that the sign member is a countermodel to `GaugeOrbitIsOddPowerFamily`.

It then goes one step further, because the corrected target was wrong too. The second half
of the file shows that the ledger admits an inhabitant of EVERY nonnegative integer
exponent, via the sign-extended character `x ↦ x·|x|^m`, so
`GaugeOrbitIsSignOrOddPowerFamily` is refuted as well and the live target is
`GaugeOrbitIsSignedPowerFamily`. The even-power refutation that had been read as excluding
even exponents excludes only the parameterization `q ↦ J(q^n)`, which forgets the sign.
-/

import IndisputableMonolith.Cost.RealCharacterFactorization
import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.PRCNativeCostStructuralLedger

namespace IndisputableMonolith
namespace Foundation
namespace PrimitiveRecognitionCalculus
namespace PRCJCost

/-- The structural ledger fields imply the light hypothesis pack used by the
real-character factorization theorem. -/
theorem realCharacterFactorizationHypotheses_of_structural
    {F : RatioOrbit → RatioOrbit}
    (hF : PRCStructuralNativeCostHypothesesSansAnchor F) :
    IndisputableMonolith.Cost.RealCharacterFactorization.SansAnchorHypotheses F where
  base_sans_two :=
    { reciprocal := hF.base_sans_two.reciprocal
      normalized_invariant := hF.base_sans_two.normalized_invariant
      canonical_rcl := hF.base_sans_two.canonical_rcl
      unit_zero := hF.base_sans_two.unit_zero }
  sign_reversing := fun q r hr => hF.sign_reversing q r hr
  monotone := by
    intro a b ha hb hab
    exact hF.monotone a b ha hb hab
  zero_calibrated := hF.zero_calibrated

/-- Every structural anchor-free cost has the real factorization proved in
`RealCharacterFactorization`. -/
theorem structural_sansAnchor_realCharacterFactorization
    {F : RatioOrbit → RatioOrbit}
    (hF : PRCStructuralNativeCostHypothesesSansAnchor F) :
    ∃ χ : RatioOrbit → ℝ,
      IndisputableMonolith.Cost.RealCharacterFactorization.PRCRealRatioCharacter χ ∧
        (∀ q : RatioOrbit, 0 < q.toRat →
          ((F q).toRat : ℝ) =
            IndisputableMonolith.Cost.RealCharacterFactorization.costFromRealCharacter χ q) ∧
        (∀ n : ℕ, 2 ≤ n → n ≤ 5 →
          ∃ t : ℚ,
            χ (IndisputableMonolith.Cost.RealCharacterFactorization.natOrbit n) +
                (χ (IndisputableMonolith.Cost.RealCharacterFactorization.natOrbit n))⁻¹ =
              (t : ℝ)) :=
  IndisputableMonolith.Cost.RealCharacterFactorization.SansAnchorRealCharacterFactorizationTarget_proved F
    (realCharacterFactorizationHypotheses_of_structural hF)

/-- Display of the zero-exponent sign cost. -/
def signGaugeCostDisplay (x : ℚ) : ℚ :=
  if 0 < x then 0 else if x = 0 then -1 else -2

/-- The cost generated by the sign character. -/
def signGaugeNativeCost (q : RatioOrbit) : RatioOrbit :=
  if 0 < q.toRat then RatioOrbit.zero
  else if q.toRat = 0 then ratioOrbitOfRat (-1)
  else ratioOrbitOfRat (-2)

theorem signGaugeNativeCost_toRat (q : RatioOrbit) :
    (signGaugeNativeCost q).toRat = signGaugeCostDisplay q.toRat := by
  by_cases hp : 0 < q.toRat
  · rw [signGaugeNativeCost, if_pos hp, RatioOrbit.zero_toRat,
      signGaugeCostDisplay, if_pos hp]
  · by_cases hz : q.toRat = 0
    · rw [signGaugeNativeCost, if_neg hp, if_pos hz, ratioOrbitOfRat_toRat,
        signGaugeCostDisplay, if_neg hp, if_pos hz]
    · rw [signGaugeNativeCost, if_neg hp, if_neg hz, ratioOrbitOfRat_toRat,
        signGaugeCostDisplay, if_neg hp, if_neg hz]

theorem signGaugeNativeCost_base_sans_two :
    PRCNativeCostHypothesesSansTwoCalibration signGaugeNativeCost where
  reciprocal := by
    intro q
    rw [RatioOrbit.crossEq_iff_toRat_eq, signGaugeNativeCost_toRat,
      signGaugeNativeCost_toRat, RatioOrbit.recip_toRat]
    by_cases hz : q.toRat = 0
    · simp [signGaugeCostDisplay, hz]
    · rcases lt_or_gt_of_ne hz with hn | hp
      · have hi : q.toRat⁻¹ < 0 := inv_lt_zero.mpr hn
        simp [signGaugeCostDisplay, hz, hn.not_gt, inv_ne_zero hz, hi.not_gt]
      · have hi : 0 < q.toRat⁻¹ := inv_pos.mpr hp
        simp [signGaugeCostDisplay, hp, hi]
  normalized_invariant := by
    intro q
    rw [RatioOrbit.crossEq_iff_toRat_eq, signGaugeNativeCost_toRat,
      signGaugeNativeCost_toRat, DistinctionNat.normalizeRatio_toRat]
  canonical_rcl := by
    intro x y hx hy
    rw [RatioOrbit.crossEq_iff_toRat_eq]
    simp only [RatioOrbit.add_toRat, RatioOrbit.mul_toRat,
      signGaugeNativeCost_toRat, div_toRat, two_toRat]
    rcases lt_or_gt_of_ne hx with hxn | hxp
    · rcases lt_or_gt_of_ne hy with hyn | hyp
      · have hmul : 0 < x.toRat * y.toRat := mul_pos_of_neg_of_neg hxn hyn
        have hdiv : 0 < x.toRat / y.toRat := div_pos_of_neg_of_neg hxn hyn
        norm_num [signGaugeCostDisplay, hmul, hdiv, hxn.not_gt, hyn.not_gt,
          ne_of_lt hxn, ne_of_lt hyn]
      · have hmul : x.toRat * y.toRat < 0 := mul_neg_of_neg_of_pos hxn hyp
        have hdiv : x.toRat / y.toRat < 0 := div_neg_of_neg_of_pos hxn hyp
        norm_num [signGaugeCostDisplay, hmul.not_gt, hdiv.not_gt, hxn.not_gt,
          hyp, ne_of_lt hmul, ne_of_lt hdiv, ne_of_lt hxn, ne_of_gt hyp]
    · rcases lt_or_gt_of_ne hy with hyn | hyp
      · have hmul : x.toRat * y.toRat < 0 := mul_neg_of_pos_of_neg hxp hyn
        have hdiv : x.toRat / y.toRat < 0 := div_neg_of_pos_of_neg hxp hyn
        norm_num [signGaugeCostDisplay, hmul.not_gt, hdiv.not_gt, hxp,
          hyn.not_gt, ne_of_lt hmul, ne_of_lt hdiv, ne_of_gt hxp, ne_of_lt hyn]
      · have hmul : 0 < x.toRat * y.toRat := mul_pos hxp hyp
        have hdiv : 0 < x.toRat / y.toRat := div_pos hxp hyp
        norm_num [signGaugeCostDisplay, hmul, hdiv, hxp, hyp,
          ne_of_gt hxp, ne_of_gt hyp]
  unit_zero := by
    rw [signGaugeNativeCost, if_pos (by rw [RatioOrbit.one_toRat]; norm_num)]

theorem signGaugeNativeCost_signReversing :
    PRCNativeCostSignReversing signGaugeNativeCost := by
  intro q r hr
  rw [signGaugeNativeCost_toRat, signGaugeNativeCost_toRat, hr]
  rcases lt_trichotomy q.toRat 0 with hn | hz | hp
  · have hnegpos : 0 < -q.toRat := neg_pos.mpr hn
    norm_num [signGaugeCostDisplay, hn.not_gt, ne_of_lt hn, hnegpos]
  · rw [hz]
    norm_num [signGaugeCostDisplay]
  · have hnegneg : -q.toRat < 0 := neg_neg_of_pos hp
    norm_num [signGaugeCostDisplay, hp, hnegneg.not_gt, ne_of_lt hnegneg]

theorem signGaugeNativeCost_monotone :
    PRCNativeCostMonotone signGaugeNativeCost := by
  rintro a b ⟨m, hm, ha⟩ ⟨n, hn, hb⟩ _
  rw [signGaugeNativeCost_toRat, signGaugeNativeCost_toRat]
  have hapos : 0 < a.toRat := by
    rw [ha]
    exact_mod_cast (show 0 < m by omega)
  have hbpos : 0 < b.toRat := by
    rw [hb]
    exact_mod_cast (show 0 < n by omega)
  simp [signGaugeCostDisplay, hapos, hbpos]

theorem signGaugeNativeCost_zero_calibrated :
    PRCDoubledTraceZeroCalibrated
      (nativeCostDoubledTrace signGaugeNativeCost) := by
  rw [PRCDoubledTraceZeroCalibrated, RatioOrbit.crossEq_iff_toRat_eq]
  simp only [nativeCostDoubledTrace, doubledTraceValue, RatioOrbit.mul_toRat,
    RatioOrbit.add_toRat, two_toRat, RatioOrbit.one_toRat,
    signGaugeNativeCost_toRat, RatioOrbit.zero_toRat]
  norm_num [signGaugeCostDisplay]

/-- The zero-exponent sign member satisfies every field of the anchor-free
structural ledger. -/
theorem signGaugeNativeCost_sansAnchor :
    PRCStructuralNativeCostHypothesesSansAnchor signGaugeNativeCost where
  base_sans_two := signGaugeNativeCost_base_sans_two
  sign_reversing := signGaugeNativeCost_signReversing
  monotone := signGaugeNativeCost_monotone
  zero_calibrated := signGaugeNativeCost_zero_calibrated

/-- The sign member takes the degenerate trace value two at the anchor. -/
theorem signGaugeNativeCost_rationalTrace_two :
    IndisputableMonolith.Cost.RealCharacterFactorization.rationalTrace
      signGaugeNativeCost 2 = 2 := by
  rw [IndisputableMonolith.Cost.RealCharacterFactorization.rationalTrace,
    IndisputableMonolith.Cost.RealCharacterFactorization.traceDisplay,
    nativeCostDoubledTrace, doubledTraceValue]
  simp only [RatioOrbit.mul_toRat, RatioOrbit.add_toRat, two_toRat,
    RatioOrbit.one_toRat, signGaugeNativeCost_toRat, ratioOrbitOfRat_toRat]
  norm_num [signGaugeCostDisplay]

/-- The factorization theorem extracts the sign character on this member. -/
theorem signGaugeNativeCost_realCharacterCandidate (q : RatioOrbit) :
    IndisputableMonolith.Cost.RealCharacterFactorization.realCharacterCandidate
        signGaugeNativeCost q =
      IndisputableMonolith.Cost.RealCharacterFactorization.rationalSignCharacter
        q.toRat := by
  rw [IndisputableMonolith.Cost.RealCharacterFactorization.realCharacterCandidate,
    if_pos signGaugeNativeCost_rationalTrace_two]

/-- The extracted character has exponent zero. -/
theorem signGaugeNativeCost_characterExponent_zero :
    IndisputableMonolith.Cost.RealCharacterFactorization.exponentOfCharacter
      (IndisputableMonolith.Cost.RealCharacterFactorization.realCharacterCandidate
        signGaugeNativeCost) = 0 := by
  rw [IndisputableMonolith.Cost.RealCharacterFactorization.exponentOfCharacter,
    signGaugeNativeCost_realCharacterCandidate,
    IndisputableMonolith.Cost.RealCharacterFactorization.natOrbit_toRat]
  have hsign :
      IndisputableMonolith.Cost.RealCharacterFactorization.rationalSignCharacter
        (((2 : ℕ) : ℚ)) = 1 := by
    norm_num
      [IndisputableMonolith.Cost.RealCharacterFactorization.rationalSignCharacter]
  rw [hsign]
  norm_num

/-- The extracted sign character is not any positive odd-integer power,
already at the anchor. -/
theorem signGaugeNativeCost_character_not_oddPower (k : ℕ) :
    IndisputableMonolith.Cost.RealCharacterFactorization.realCharacterCandidate
        signGaugeNativeCost
        (IndisputableMonolith.Cost.RealCharacterFactorization.natOrbit 2) ≠
      (2 : ℝ) ^ (2 * k + 1) := by
  rw [signGaugeNativeCost_realCharacterCandidate,
    IndisputableMonolith.Cost.RealCharacterFactorization.natOrbit_toRat]
  have hsign :
      IndisputableMonolith.Cost.RealCharacterFactorization.rationalSignCharacter
        (((2 : ℕ) : ℚ)) = 1 := by
    norm_num
      [IndisputableMonolith.Cost.RealCharacterFactorization.rationalSignCharacter]
  rw [hsign]
  exact ne_of_lt (one_lt_pow₀ (by norm_num) (by omega))

/-- The sign member cannot equal any positive odd-power cost. -/
theorem signGaugeNativeCost_not_oddPowerGeneratedNativeCost (k : ℕ) :
    ¬ ∀ q : RatioOrbit,
      RatioOrbit.crossEq (signGaugeNativeCost q)
        (oddPowerGeneratedNativeCost k q) := by
  intro h
  have htwo := crossDisp (h two)
  rw [signGaugeNativeCost_toRat, oddPowerGeneratedNativeCost_toRat,
    two_toRat] at htwo
  have hexp : 2 * k + 1 ≠ 0 := by omega
  have hp : (1 : ℚ) < 2 ^ (2 * k + 1) :=
    one_lt_pow₀ (by norm_num) hexp
  have hzero : jq ((2 : ℚ) ^ (2 * k + 1)) = 0 := by
    norm_num [signGaugeCostDisplay] at htwo
    exact htwo.symm
  have hone := jq_eq_zero (ne_of_gt (lt_trans zero_lt_one hp)) hzero
  exact (ne_of_gt hp) hone

/-- The proposed classification is false: it omits the zero-exponent sign
member already allowed by the structural ledger. -/
theorem GaugeOrbitIsOddPowerFamily_refuted :
    ¬ GaugeOrbitIsOddPowerFamily := by
  intro h
  obtain ⟨k, hk⟩ := h signGaugeNativeCost signGaugeNativeCost_sansAnchor
  exact signGaugeNativeCost_not_oddPowerGeneratedNativeCost k hk

/-- **OPEN**, corrected classification. Every anchor-free structural inhabitant
is either the zero-exponent sign cost or an odd-power generated cost. -/
def GaugeOrbitIsSignOrOddPowerFamily : Prop :=
  ∀ F : RatioOrbit → RatioOrbit, PRCStructuralNativeCostHypothesesSansAnchor F →
    (∀ q : RatioOrbit, RatioOrbit.crossEq (F q) (signGaugeNativeCost q)) ∨
      ∃ k : ℕ, ∀ q : RatioOrbit,
        RatioOrbit.crossEq (F q) (oddPowerGeneratedNativeCost k q)

/-! ## The even exponents are inhabited too, so the corrected target also fails

Orientation reversal constrains the character at `-1`. It does not constrain the parity of
the exponent, and the two were being confused.

What is true is that `powerGeneratedNativeCost (2k+2)`, the cost `q ↦ J(q^(2k+2))`, fails
sign reversal (`powerGeneratedNativeCost_not_signReversing`): an even power forgets the sign
of its argument, so the cost cannot reverse. That is a fact about the parameterization
`q ↦ q^n`, and the ledger constrains costs rather than parameterizations.

Take instead the character `χ(x) = x·|x|^m`, which is `sgn(x)·|x|^(m+1)`. It is completely
multiplicative for every `m` with no case analysis, it sends `-1` to `-1`, so its generated
cost reverses orientation while carrying the exponent `m+1`, whatever the parity. At even
`m` it reproduces the odd powers exactly (`signedPowerNativeCost_even_eq_oddPower`). At odd
`m` it is new. The member `m = 1` has exponent two, charges `J(4) = 9/8` at the anchor, and
is therefore neither the sign cost nor any odd power, which refutes
`GaugeOrbitIsSignOrOddPowerFamily`. Its doubled trace at two is `17/4`, whose principal root
is `4 = 2^2`, so the extracted character really does have the even exponent.

Net: the ledger contains an inhabitant of every nonnegative integer exponent, and the honest
target is `GaugeOrbitIsSignedPowerFamily` below. This is the third correction to this
classification in one day, and all three came from building the witness rather than
reasoning about the family. -/

/-- `signedPow m x = sgn(x)·|x|^(m+1)`, written as `x·|x|^m` so that multiplicativity is one
`abs_mul` away and needs no sign case analysis. -/
def signedPow (m : ℕ) (x : ℚ) : ℚ := x * |x| ^ m

@[simp] theorem signedPow_zero_arg (m : ℕ) : signedPow m 0 = 0 := by
  simp [signedPow]

@[simp] theorem signedPow_one_arg (m : ℕ) : signedPow m 1 = 1 := by
  simp [signedPow]

theorem signedPow_mul (m : ℕ) (x y : ℚ) :
    signedPow m (x * y) = signedPow m x * signedPow m y := by
  simp only [signedPow, abs_mul, mul_pow]
  ring

theorem signedPow_inv (m : ℕ) (x : ℚ) :
    signedPow m x⁻¹ = (signedPow m x)⁻¹ := by
  rw [signedPow, signedPow, abs_inv, inv_pow, mul_inv]

theorem signedPow_div (m : ℕ) (x y : ℚ) :
    signedPow m (x / y) = signedPow m x / signedPow m y := by
  rw [div_eq_mul_inv, signedPow_mul, signedPow_inv, div_eq_mul_inv]

theorem signedPow_neg (m : ℕ) (x : ℚ) :
    signedPow m (-x) = -signedPow m x := by
  simp only [signedPow, abs_neg]
  ring

theorem signedPow_ne_zero {m : ℕ} {x : ℚ} (hx : x ≠ 0) : signedPow m x ≠ 0 :=
  mul_ne_zero hx (pow_ne_zero m (abs_ne_zero.mpr hx))

theorem signedPow_of_one_le {m : ℕ} {x : ℚ} (hx : 1 ≤ x) : 1 ≤ signedPow m x := by
  have hx0 : (0 : ℚ) ≤ x := le_trans zero_le_one hx
  have hpow : (1 : ℚ) ≤ x ^ m := one_le_pow₀ hx
  rw [signedPow, abs_of_nonneg hx0]
  nlinarith

theorem signedPow_mono {m : ℕ} {a b : ℚ} (ha : 1 ≤ a) (hab : a ≤ b) :
    signedPow m a ≤ signedPow m b := by
  have ha0 : (0 : ℚ) ≤ a := le_trans zero_le_one ha
  have hb0 : (0 : ℚ) ≤ b := le_trans ha0 hab
  have hpow : a ^ m ≤ b ^ m := pow_le_pow_left₀ ha0 hab m
  have h1 : (1 : ℚ) ≤ a ^ m := one_le_pow₀ ha
  rw [signedPow, signedPow, abs_of_nonneg ha0, abs_of_nonneg hb0]
  calc a * a ^ m ≤ b * a ^ m :=
        mul_le_mul_of_nonneg_right hab (le_trans zero_le_one h1)
    _ ≤ b * b ^ m := mul_le_mul_of_nonneg_left hpow hb0

/-- At an even index the sign-extended power is the ordinary odd power. -/
theorem signedPow_even (k : ℕ) (x : ℚ) : signedPow (2 * k) x = x ^ (2 * k + 1) := by
  have habs : |x| ^ (2 * k) = x ^ (2 * k) := by
    rw [pow_mul, sq_abs, ← pow_mul]
  rw [signedPow, habs]
  ring

/-- The cost generated by the sign-extended power character `χ(x) = sgn(x)·|x|^(m+1)`. -/
def signedPowerNativeCost (m : ℕ) (q : RatioOrbit) : RatioOrbit :=
  if q.toRat = 1 then RatioOrbit.zero
  else onRatioOrbit (ratioOrbitOfRat (signedPow m q.toRat))

theorem signedPowerNativeCost_toRat (m : ℕ) (q : RatioOrbit) :
    (signedPowerNativeCost m q).toRat = jq (signedPow m q.toRat) := by
  rw [signedPowerNativeCost]
  by_cases h : q.toRat = 1
  · rw [if_pos h, RatioOrbit.zero_toRat, h, signedPow_one_arg]
    norm_num [jq]
  · rw [if_neg h, jq_onRatioOrbit, ratioOrbitOfRat_toRat]

theorem signedPowerNativeCost_base (m : ℕ) :
    PRCNativeCostHypothesesSansTwoCalibration (signedPowerNativeCost m) where
  reciprocal := by
    intro q
    rw [RatioOrbit.crossEq_iff_toRat_eq, signedPowerNativeCost_toRat,
      signedPowerNativeCost_toRat, RatioOrbit.recip_toRat, signedPow_inv, jq_inv]
  normalized_invariant := by
    intro q
    rw [RatioOrbit.crossEq_iff_toRat_eq, signedPowerNativeCost_toRat,
      signedPowerNativeCost_toRat, DistinctionNat.normalizeRatio_toRat]
  canonical_rcl := by
    intro x y hx hy
    rw [RatioOrbit.crossEq_iff_toRat_eq]
    simp only [RatioOrbit.add_toRat, RatioOrbit.mul_toRat,
      signedPowerNativeCost_toRat, div_toRat, two_toRat]
    rw [signedPow_mul, signedPow_div]
    exact jq_rcl (signedPow_ne_zero hx) (signedPow_ne_zero hy)
  unit_zero := by
    rw [signedPowerNativeCost, if_pos RatioOrbit.one_toRat]

theorem signedPowerNativeCost_signReversing (m : ℕ) :
    PRCNativeCostSignReversing (signedPowerNativeCost m) := by
  intro q r hr
  rw [signedPowerNativeCost_toRat, signedPowerNativeCost_toRat, hr,
    signedPow_neg, jq_neg]

theorem signedPowerNativeCost_monotone (m : ℕ) :
    PRCNativeCostMonotone (signedPowerNativeCost m) := by
  rintro a b ⟨n, hn, han⟩ ⟨_, _, _⟩ hab
  rw [signedPowerNativeCost_toRat, signedPowerNativeCost_toRat]
  have ha1 : (1 : ℚ) ≤ a.toRat := by
    rw [han]
    exact_mod_cast hn
  exact jq_mono (signedPow_of_one_le ha1) (signedPow_mono ha1 hab)

theorem signedPowerNativeCost_zero_calibrated (m : ℕ) :
    PRCDoubledTraceZeroCalibrated
      (nativeCostDoubledTrace (signedPowerNativeCost m)) := by
  rw [PRCDoubledTraceZeroCalibrated, RatioOrbit.crossEq_iff_toRat_eq]
  simp only [nativeCostDoubledTrace, doubledTraceValue, RatioOrbit.mul_toRat,
    RatioOrbit.add_toRat, two_toRat, RatioOrbit.one_toRat,
    signedPowerNativeCost_toRat, RatioOrbit.zero_toRat, signedPow_zero_arg]
  norm_num [jq]

/-- **Every nonnegative integer exponent inhabits the anchor-free ledger.** The
sign-extended power character satisfies every structural field, including orientation
reversal, at every index and so at both parities of exponent. -/
theorem signedPowerNativeCost_sansAnchor (m : ℕ) :
    PRCStructuralNativeCostHypothesesSansAnchor (signedPowerNativeCost m) where
  base_sans_two := signedPowerNativeCost_base m
  sign_reversing := signedPowerNativeCost_signReversing m
  monotone := signedPowerNativeCost_monotone m
  zero_calibrated := signedPowerNativeCost_zero_calibrated m

/-- The even indices recover the known odd-power family, so the new family contains it. -/
theorem signedPowerNativeCost_even_eq_oddPower (k : ℕ) (q : RatioOrbit) :
    (signedPowerNativeCost (2 * k) q).toRat =
      (oddPowerGeneratedNativeCost k q).toRat := by
  rw [signedPowerNativeCost_toRat, oddPowerGeneratedNativeCost_toRat, signedPow_even]

/-- The exponent-two member charges `J(4)` at the anchor. -/
theorem signedPowerNativeCost_one_two_toRat :
    (signedPowerNativeCost 1 two).toRat = jq 4 := by
  rw [signedPowerNativeCost_toRat, two_toRat]
  norm_num [signedPow]

theorem signedPowerNativeCost_one_not_oddPower (k : ℕ) :
    ¬ ∀ q : RatioOrbit,
      RatioOrbit.crossEq (signedPowerNativeCost 1 q)
        (oddPowerGeneratedNativeCost k q) := by
  intro h
  have htwo := crossDisp (h two)
  rw [signedPowerNativeCost_one_two_toRat, oddPowerGeneratedNativeCost_toRat,
    two_toRat] at htwo
  have hone : (1 : ℚ) ≤ (2 : ℚ) ^ (2 * k + 1) := one_le_pow₀ (by norm_num)
  have heq : (4 : ℚ) = 2 ^ (2 * k + 1) :=
    jq_inj_ge_one (by norm_num) hone htwo
  rcases Nat.eq_zero_or_pos k with hk | hk
  · subst hk
    norm_num at heq
  · have h8 : (8 : ℚ) ≤ 2 ^ (2 * k + 1) := by
      calc (8 : ℚ) = 2 ^ 3 := by norm_num
        _ ≤ 2 ^ (2 * k + 1) := pow_le_pow_right₀ (by norm_num) (by omega)
    rw [← heq] at h8
    norm_num at h8

theorem signedPowerNativeCost_one_not_signGauge :
    ¬ ∀ q : RatioOrbit,
      RatioOrbit.crossEq (signedPowerNativeCost 1 q) (signGaugeNativeCost q) := by
  intro h
  have htwo := crossDisp (h two)
  rw [signedPowerNativeCost_one_two_toRat, signGaugeNativeCost_toRat,
    two_toRat] at htwo
  norm_num [signGaugeCostDisplay, jq] at htwo

/-- **The corrected classification is false too.** The exponent-two sign-extended member is
neither the sign cost nor any odd power. -/
theorem GaugeOrbitIsSignOrOddPowerFamily_refuted :
    ¬ GaugeOrbitIsSignOrOddPowerFamily := by
  intro h
  rcases h (signedPowerNativeCost 1) (signedPowerNativeCost_sansAnchor 1) with
    hsign | ⟨k, hk⟩
  · exact signedPowerNativeCost_one_not_signGauge hsign
  · exact signedPowerNativeCost_one_not_oddPower k hk

/-- **PROVED**, on one named import, in `Cost.GaugeOrbitClassification`
(`GaugeOrbitIsSignedPowerFamily_of_sixExponentials`). Corrected a third time before it
closed: every anchor-free structural inhabitant is the sign cost (exponent zero) or a
sign-extended power cost (exponent `m+1`), so the classification allows every nonnegative
integer exponent and no more. The odd powers are the even indices by
`signedPowerNativeCost_even_eq_oddPower`. The single hypothesis of the proof is
`Cost.TraceRationalExponent.SixExponentialsTraceInput`. -/
def GaugeOrbitIsSignedPowerFamily : Prop :=
  ∀ F : RatioOrbit → RatioOrbit, PRCStructuralNativeCostHypothesesSansAnchor F →
    (∀ q : RatioOrbit, RatioOrbit.crossEq (F q) (signGaugeNativeCost q)) ∨
      ∃ m : ℕ, ∀ q : RatioOrbit,
        RatioOrbit.crossEq (F q) (signedPowerNativeCost m q)

#print axioms structural_sansAnchor_realCharacterFactorization
#print axioms signGaugeNativeCost_sansAnchor
#print axioms signGaugeNativeCost_character_not_oddPower
#print axioms GaugeOrbitIsOddPowerFamily_refuted
#print axioms signedPowerNativeCost_sansAnchor
#print axioms signedPowerNativeCost_even_eq_oddPower
#print axioms GaugeOrbitIsSignOrOddPowerFamily_refuted

end PRCJCost
end PrimitiveRecognitionCalculus
end Foundation
end IndisputableMonolith
