import IndisputableMonolith.Foundation.ForcingStatus
import IndisputableMonolith.Foundation.HierarchyRealizationObstruction
import IndisputableMonolith.Foundation.PositiveRatioBridgeStrict
import IndisputableMonolith.Foundation.LinkingNecessity

/-!
# Chain Obstructions

Forward bridges are only convincing when paired with independence checks.  This
module gathers the proved obstructions for the T6 hierarchy bridge, the
positive-ratio bridge, the RCL gate's `rightAffine` field, and (since the
`LinkingNecessity` closure) the T8 linking interpretation.

The linking row was historically a `documentedBridgeDefinition`: the linking
requirement was asserted by definition with no independence check.
`LinkingNecessity` factored that bridge into the named
`DeformationErasurePrinciple` plus theorems (the principle forces `D = 3`;
off `D = 3` the dual-pair distinction is provably erasable) plus the proved
obstruction recorded here (`linking_interpretation_obstruction`): the
spatial-realization layer alone does not force the principle, so it is a
genuine named input, exactly parallel to the other three rows.
-/

namespace IndisputableMonolith
namespace Foundation
namespace ChainObstructions

open ForcingStatus

/-! ## T6 hierarchy obstruction -/

/-- Existing obstruction: a closed observable framework alone does not force the
two realized-hierarchy fields needed by the T5-to-T6 bridge. -/
theorem hierarchy_fields_obstruction :
    ∃ (F : ClosedFramework.ClosedObservableFramework) (base : F.S),
      (¬ (∀ k,
        F.r (F.T^[k + 2] base) / F.r (F.T^[k + 1] base) =
          F.r (F.T^[k + 1] base) / F.r (F.T^[k] base))) ∧
      (¬ (F.r (F.T^[2] base) = F.r (F.T^[1] base) + F.r base)) :=
  HierarchyRealizationObstruction.closedFramework_does_not_force_realizedHierarchy_fields

/-! ## Positive-ratio bridge obstruction -/

/-- Existing obstruction: the Boolean floor generated by one distinction cannot
carry injective log-coordinate positive-ratio coordinates.  The analytic
positive-ratio layer is therefore not already present inside the finite
two-class quotient. -/
theorem positiveRatio_coordinates_obstruction :
    ¬ Nonempty (PositiveRatioBridgeStrict.LogPositiveRatioCoordinates
      (K := Bool) ⟨false, true, Bool.noConfusion⟩) :=
  PositiveRatioBridgeStrict.bool_floor_no_log_positive_ratio_coordinates

/-! ## RCL gate obstruction -/

/-- A symmetric combiner satisfying the zero-boundary and unit-diagonal
conditions, but deliberately nonlinear in the second argument. -/
def nonRightAffineCombiner (u v : ℝ) : ℝ :=
  3 * u * v + 2 * u + 2 * v - u^2 * v^2

theorem nonRightAffineCombiner_symmetric :
    ∀ u v, nonRightAffineCombiner u v = nonRightAffineCombiner v u := by
  intro u v
  unfold nonRightAffineCombiner
  ring

theorem nonRightAffineCombiner_zeroBoundary :
    ∀ u, nonRightAffineCombiner u 0 = 2 * u := by
  intro u
  unfold nonRightAffineCombiner
  ring

theorem nonRightAffineCombiner_unitDiagonal :
    nonRightAffineCombiner 1 1 = 6 := by
  unfold nonRightAffineCombiner
  norm_num

/-- Boundary, symmetry, and unit normalization do not force the affine-response
field used by `FactorizationAssociativityGate`.  The missing `rightAffine`
field is therefore a real structural input, not a consequence of the other gate
fields. -/
theorem boundary_symmetry_unit_do_not_force_rightAffine :
    ∃ P : ℝ → ℝ → ℝ,
      (∀ u v, P u v = P v u) ∧
      (∀ u, P u 0 = 2 * u) ∧
      P 1 1 = 6 ∧
      ¬ (∀ u, ∃ α β, ∀ v, P u v = α * v + β) := by
  refine ⟨nonRightAffineCombiner, nonRightAffineCombiner_symmetric,
    nonRightAffineCombiner_zeroBoundary, nonRightAffineCombiner_unitDiagonal, ?_⟩
  intro hAffine
  obtain ⟨α, β, hline⟩ := hAffine 1
  have h0 : β = 2 := by
    have h := hline 0
    unfold nonRightAffineCombiner at h
    linarith
  have h1 : α + β = 6 := by
    have h := hline 1
    unfold nonRightAffineCombiner at h
    linarith
  have hα : α = 4 := by
    linarith
  have h2 : 8 = 2 * α + β := by
    have h := hline 2
    unfold nonRightAffineCombiner at h
    norm_num at h
    linarith
  linarith

/-! ## T8 linking-interpretation obstruction and forcing -/

/-- **Linking-interpretation obstruction (proved).**  The spatial-realization
layer alone does not force the deformation-erasure principle: a complete
spatial dual-pair realization exists (in `D = 4`, on the everything-deforms
kinematics) in which every pairing observable vanishes and the principle
fails.  The principle is therefore a genuine named input of the T8 bridge,
independence-checked exactly like the other three rows. -/
theorem linking_interpretation_obstruction :
    ∃ (D : DimensionForcing.Dimension)
      (R : LinkingNecessity.SpatialDualPairRealization D),
      ¬ LinkingNecessity.DeformationErasurePrinciple R.kin :=
  LinkingNecessity.dep_not_forced_by_realization_layer

/-- **Linking-interpretation forcing.**  The named principle is sufficient: in
every spatial dual-pair realization satisfying the deformation-erasure
principle, the ambient dimension is forced to `3`.  Together with the
obstruction above, the former bare "linking is required" definition is replaced
by named-input-plus-theorem. -/
theorem linking_interpretation_forcing :
    ∀ (D : DimensionForcing.Dimension)
      (R : LinkingNecessity.SpatialDualPairRealization D),
      LinkingNecessity.DeformationErasurePrinciple R.kin → D = 3 :=
  LinkingNecessity.dep_forces_D3

/-! ## Status audit -/

/-- Checked obstruction-status table for the bridges that remain visible in the
strict T-1-to-T8 capstone.  All four rows now carry proved obstructions; the
linking row was upgraded from `documentedBridgeDefinition` by the
`LinkingNecessity` closure (named principle + forcing theorem + independence
obstruction). -/
def bridgeObstructionStatusTable : List BridgeStatusEntry :=
  [
    {
      name := "T6 realized-hierarchy fields"
      status := BridgeObstructionStatus.proved
    },
    {
      name := "T5 positive-ratio coordinates"
      status := BridgeObstructionStatus.proved
    },
    {
      name := "T5 right-affine response"
      status := BridgeObstructionStatus.proved
    },
    {
      name := "T8 linking interpretation"
      status := BridgeObstructionStatus.proved
    }
  ]

/-- Exact checked obstruction-status table. -/
theorem bridgeObstructionStatusTable_exact :
    bridgeObstructionStatusTable =
      [
        {
          name := "T6 realized-hierarchy fields"
          status := BridgeObstructionStatus.proved
        },
        {
          name := "T5 positive-ratio coordinates"
          status := BridgeObstructionStatus.proved
        },
        {
          name := "T5 right-affine response"
          status := BridgeObstructionStatus.proved
        },
        {
          name := "T8 linking interpretation"
          status := BridgeObstructionStatus.proved
        }
      ] :=
  rfl

/-- The bridge-obstruction status table has no duplicate row names. -/
theorem bridgeObstructionStatusTable_names_nodup :
    (bridgeObstructionStatusTable.map (fun e => e.name)).Nodup := by
  native_decide

/-- The bridge-obstruction status-table row-name sequence is pinned explicitly. -/
theorem bridgeObstructionStatusTable_name_order :
    bridgeObstructionStatusTable.map (fun e => e.name) =
      [
        "T6 realized-hierarchy fields",
        "T5 positive-ratio coordinates",
        "T5 right-affine response",
        "T8 linking interpretation"
      ] :=
  rfl

/-- The bridge-obstruction status sequence is pinned explicitly. -/
theorem bridgeObstructionStatusTable_status_order :
    bridgeObstructionStatusTable.map (fun e => e.status) =
      [
        BridgeObstructionStatus.proved,
        BridgeObstructionStatus.proved,
        BridgeObstructionStatus.proved,
        BridgeObstructionStatus.proved
      ] :=
  rfl

/-- The bridge-obstruction name/status pairs are pinned explicitly. -/
theorem bridgeObstructionStatusTable_name_status_order :
    bridgeObstructionStatusTable.map (fun e => (e.name, e.status)) =
      [
        ("T6 realized-hierarchy fields", BridgeObstructionStatus.proved),
        ("T5 positive-ratio coordinates", BridgeObstructionStatus.proved),
        ("T5 right-affine response", BridgeObstructionStatus.proved),
        ("T8 linking interpretation", BridgeObstructionStatus.proved)
      ] :=
  rfl

/-- All four bridge-obstruction rows are proved obstruction results. -/
theorem bridgeObstructionStatusTable_proved_count :
    (bridgeObstructionStatusTable.filter
      fun e => e.status == BridgeObstructionStatus.proved).length = 4 :=
  rfl

/-- No bridge-obstruction row remains a bare documented bridge definition. -/
theorem bridgeObstructionStatusTable_documented_count :
    (bridgeObstructionStatusTable.filter
      fun e => e.status == BridgeObstructionStatus.documentedBridgeDefinition).length = 0 :=
  rfl

/-- Every non-linking bridge row has a proved obstruction. -/
theorem non_linking_bridge_obstructions_proved :
    ∀ e ∈ bridgeObstructionStatusTable,
      e.name ≠ "T8 linking interpretation" →
        e.status = BridgeObstructionStatus.proved := by
  intro e he _hname
  simp [bridgeObstructionStatusTable] at he
  rcases he with he | he | he | he <;> (subst e; rfl)

/-- The linking bridge row now carries a proved obstruction. -/
theorem linking_bridge_status_proved :
    ∃ e ∈ bridgeObstructionStatusTable,
      e.name = "T8 linking interpretation" ∧
        e.status = BridgeObstructionStatus.proved := by
  refine ⟨{
    name := "T8 linking interpretation"
    status := BridgeObstructionStatus.proved
  }, ?_, rfl, rfl⟩
  simp [bridgeObstructionStatusTable]

/-- Every bridge row has a proved obstruction. -/
theorem all_bridge_obstructions_proved :
    ∀ e ∈ bridgeObstructionStatusTable,
      e.status = BridgeObstructionStatus.proved := by
  intro e he
  simp [bridgeObstructionStatusTable] at he
  rcases he with he | he | he | he <;> (subst e; rfl)

/-- Compact audit certificate for the bridge-obstruction status table. -/
structure BridgeObstructionStatusTableAudit : Prop where
  table_exact :
    bridgeObstructionStatusTable =
      [
        {
          name := "T6 realized-hierarchy fields"
          status := BridgeObstructionStatus.proved
        },
        {
          name := "T5 positive-ratio coordinates"
          status := BridgeObstructionStatus.proved
        },
        {
          name := "T5 right-affine response"
          status := BridgeObstructionStatus.proved
        },
        {
          name := "T8 linking interpretation"
          status := BridgeObstructionStatus.proved
        }
      ]
  names_nodup : (bridgeObstructionStatusTable.map (fun e => e.name)).Nodup
  name_order :
    bridgeObstructionStatusTable.map (fun e => e.name) =
      [
        "T6 realized-hierarchy fields",
        "T5 positive-ratio coordinates",
        "T5 right-affine response",
        "T8 linking interpretation"
      ]
  status_order :
    bridgeObstructionStatusTable.map (fun e => e.status) =
      [
        BridgeObstructionStatus.proved,
        BridgeObstructionStatus.proved,
        BridgeObstructionStatus.proved,
        BridgeObstructionStatus.proved
      ]
  name_status_order :
    bridgeObstructionStatusTable.map (fun e => (e.name, e.status)) =
      [
        ("T6 realized-hierarchy fields", BridgeObstructionStatus.proved),
        ("T5 positive-ratio coordinates", BridgeObstructionStatus.proved),
        ("T5 right-affine response", BridgeObstructionStatus.proved),
        ("T8 linking interpretation", BridgeObstructionStatus.proved)
      ]
  proved_count :
    (bridgeObstructionStatusTable.filter
      fun e => e.status == BridgeObstructionStatus.proved).length = 4
  documented_count :
    (bridgeObstructionStatusTable.filter
      fun e => e.status == BridgeObstructionStatus.documentedBridgeDefinition).length = 0
  non_linking_obstructions_proved :
    ∀ e ∈ bridgeObstructionStatusTable,
      e.name ≠ "T8 linking interpretation" →
        e.status = BridgeObstructionStatus.proved
  linking_proved :
    ∃ e ∈ bridgeObstructionStatusTable,
      e.name = "T8 linking interpretation" ∧
        e.status = BridgeObstructionStatus.proved
  all_proved :
    ∀ e ∈ bridgeObstructionStatusTable,
      e.status = BridgeObstructionStatus.proved

/-- Checked compact audit certificate for the bridge-obstruction status table. -/
theorem bridgeObstructionStatusTable_audit :
    BridgeObstructionStatusTableAudit where
  table_exact := bridgeObstructionStatusTable_exact
  names_nodup := bridgeObstructionStatusTable_names_nodup
  name_order := bridgeObstructionStatusTable_name_order
  status_order := bridgeObstructionStatusTable_status_order
  name_status_order := bridgeObstructionStatusTable_name_status_order
  proved_count := bridgeObstructionStatusTable_proved_count
  documented_count := bridgeObstructionStatusTable_documented_count
  non_linking_obstructions_proved := non_linking_bridge_obstructions_proved
  linking_proved := linking_bridge_status_proved
  all_proved := all_bridge_obstructions_proved

/-- Status summary of bridge obstructions. -/
structure BridgeIndependenceAudit : Prop where
  hierarchy_obstruction :
    ∃ (F : ClosedFramework.ClosedObservableFramework) (base : F.S),
      (¬ (∀ k,
        F.r (F.T^[k + 2] base) / F.r (F.T^[k + 1] base) =
          F.r (F.T^[k + 1] base) / F.r (F.T^[k] base))) ∧
      (¬ (F.r (F.T^[2] base) = F.r (F.T^[1] base) + F.r base))
  rightAffine_obstruction :
    ∃ P : ℝ → ℝ → ℝ,
      (∀ u v, P u v = P v u) ∧
      (∀ u, P u 0 = 2 * u) ∧
      P 1 1 = 6 ∧
      ¬ (∀ u, ∃ α β, ∀ v, P u v = α * v + β)
  positiveRatio_obstruction :
    ¬ Nonempty (PositiveRatioBridgeStrict.LogPositiveRatioCoordinates
      (K := Bool) ⟨false, true, Bool.noConfusion⟩)
  linking_obstruction :
    ∃ (D : DimensionForcing.Dimension)
      (R : LinkingNecessity.SpatialDualPairRealization D),
      ¬ LinkingNecessity.DeformationErasurePrinciple R.kin
  linking_forcing :
    ∀ (D : DimensionForcing.Dimension)
      (R : LinkingNecessity.SpatialDualPairRealization D),
      LinkingNecessity.DeformationErasurePrinciple R.kin → D = 3
  hierarchy_status :
    BridgeObstructionStatus.proved = BridgeObstructionStatus.proved
  rightAffine_status :
    BridgeObstructionStatus.proved = BridgeObstructionStatus.proved
  positiveRatio_status :
    BridgeObstructionStatus.proved = BridgeObstructionStatus.proved
  linking_status :
    BridgeObstructionStatus.proved = BridgeObstructionStatus.proved
  status_table_exact :
    bridgeObstructionStatusTable =
      [
        {
          name := "T6 realized-hierarchy fields"
          status := BridgeObstructionStatus.proved
        },
        {
          name := "T5 positive-ratio coordinates"
          status := BridgeObstructionStatus.proved
        },
        {
          name := "T5 right-affine response"
          status := BridgeObstructionStatus.proved
        },
        {
          name := "T8 linking interpretation"
          status := BridgeObstructionStatus.proved
        }
      ]
  status_table_names_nodup :
    (bridgeObstructionStatusTable.map (fun e => e.name)).Nodup
  status_table_name_order :
    bridgeObstructionStatusTable.map (fun e => e.name) =
      [
        "T6 realized-hierarchy fields",
        "T5 positive-ratio coordinates",
        "T5 right-affine response",
        "T8 linking interpretation"
      ]
  status_table_status_order :
    bridgeObstructionStatusTable.map (fun e => e.status) =
      [
        BridgeObstructionStatus.proved,
        BridgeObstructionStatus.proved,
        BridgeObstructionStatus.proved,
        BridgeObstructionStatus.proved
      ]
  status_table_name_status_order :
    bridgeObstructionStatusTable.map (fun e => (e.name, e.status)) =
      [
        ("T6 realized-hierarchy fields", BridgeObstructionStatus.proved),
        ("T5 positive-ratio coordinates", BridgeObstructionStatus.proved),
        ("T5 right-affine response", BridgeObstructionStatus.proved),
        ("T8 linking interpretation", BridgeObstructionStatus.proved)
      ]
  status_table_proved_count :
    (bridgeObstructionStatusTable.filter
      fun e => e.status == BridgeObstructionStatus.proved).length = 4
  status_table_documented_count :
    (bridgeObstructionStatusTable.filter
      fun e => e.status == BridgeObstructionStatus.documentedBridgeDefinition).length = 0
  non_linking_obstructions_proved :
    ∀ e ∈ bridgeObstructionStatusTable,
      e.name ≠ "T8 linking interpretation" →
        e.status = BridgeObstructionStatus.proved
  linking_proved :
    ∃ e ∈ bridgeObstructionStatusTable,
      e.name = "T8 linking interpretation" ∧
        e.status = BridgeObstructionStatus.proved
  status_table_audit : BridgeObstructionStatusTableAudit

/-- The current bridge-independence audit. -/
theorem bridge_independence_audit : BridgeIndependenceAudit where
  hierarchy_obstruction := hierarchy_fields_obstruction
  rightAffine_obstruction := boundary_symmetry_unit_do_not_force_rightAffine
  positiveRatio_obstruction := positiveRatio_coordinates_obstruction
  linking_obstruction := linking_interpretation_obstruction
  linking_forcing := linking_interpretation_forcing
  hierarchy_status := rfl
  rightAffine_status := rfl
  positiveRatio_status := rfl
  linking_status := rfl
  status_table_exact := bridgeObstructionStatusTable_exact
  status_table_names_nodup := bridgeObstructionStatusTable_names_nodup
  status_table_name_order := bridgeObstructionStatusTable_name_order
  status_table_status_order := bridgeObstructionStatusTable_status_order
  status_table_name_status_order := bridgeObstructionStatusTable_name_status_order
  status_table_proved_count := bridgeObstructionStatusTable_proved_count
  status_table_documented_count := bridgeObstructionStatusTable_documented_count
  non_linking_obstructions_proved := non_linking_bridge_obstructions_proved
  linking_proved := linking_bridge_status_proved
  status_table_audit := bridgeObstructionStatusTable_audit

end ChainObstructions
end Foundation
end IndisputableMonolith
