import Mathlib
import IndisputableMonolith.Foundation.DistinctionToT4
import IndisputableMonolith.CostUniqueness

/-!
# Distinction to J-Cost (T5)

This module continues the distinction-threaded closure path.

`DistinctionToT4` proves that a supplied distinction witness

```
h : ∃ x y : K, x ≠ y
```

forces the T−1 through T4 floor on the observable quotient generated by `h`.
Here we use that forced quotient to instantiate the Law-of-Logic realization
interface, relate that realization to the continuous positive-ratio realization,
and expose the T5 J-uniqueness theorem without using the global `t5_holds`
shortcut.

The remaining philosophical burden after this module is not J-uniqueness.  It
is the next bridge: deriving the self-similar closed hierarchy used by T6 from
the now-forced J-ledger.
-/

namespace IndisputableMonolith
namespace Foundation
namespace DistinctionToJCost

open Cost
open Cost.FunctionalEquation
open LogicAsFunctionalEquation
open DistinctionToT4
open TMinus1ForcedFromDistinction

/-! ## 1. The forced quotient as a Law-of-Logic realization -/

/-- The `false` representative in the quotient generated by the distinction. -/
noncomputable def forcedQuotientBase
    {K : Type} (h : ∃ x y : K, x ≠ y) : ForcedQuotient h :=
  (forcedQuotientBoolEquiv h).symm false

/-- The `true` representative in the quotient generated by the distinction. -/
noncomputable def forcedQuotientAlt
    {K : Type} (h : ∃ x y : K, x ≠ y) : ForcedQuotient h :=
  (forcedQuotientBoolEquiv h).symm true

/-- The two Boolean representatives of the forced quotient are distinct. -/
theorem forcedQuotientBase_ne_alt
    {K : Type} (h : ∃ x y : K, x ≠ y) :
    forcedQuotientBase h ≠ forcedQuotientAlt h := by
  intro heq
  have hbool := congrArg (forcedQuotientBoolEquiv h) heq
  simp [forcedQuotientBase, forcedQuotientAlt, forcedQuotientBoolEquiv] at hbool

/-- The Law-of-Logic realization carried by the quotient generated from a
distinction witness. -/
noncomputable def forcedQuotientLogicRealization
    {K : Type} (h : ∃ x y : K, x ≠ y) :
    LogicRealization.{0, 0} := by
  classical
  exact UniversalInstantiationFromDistinction.logicRealizationOfDistinction
    (ForcedQuotient h)
    (forcedQuotientBase h)
    (forcedQuotientAlt h)
    (forcedQuotientBase_ne_alt h)

/-- The forced quotient supplies a Law-of-Logic realization. -/
theorem forcedQuotient_logicRealization_nonempty
    {K : Type} (h : ∃ x y : K, x ≠ y) :
    Nonempty LogicRealization.{0, 0} :=
  ⟨forcedQuotientLogicRealization h⟩

/-! ## 2. Positive-ratio realization and arithmetic invariance -/

/-- The continuous positive-ratio realization associated to a comparison
operator satisfying the Law of Logic. -/
noncomputable def positiveRatioRealization
    (C : ComparisonOperator) (hC : SatisfiesLawsOfLogic C) :
    LogicRealization.{0, 0} :=
  LogicRealization.ofPositiveRatioComparison C hC

/-- The forced quotient and any continuous positive-ratio realization have
canonically equivalent recognition orbits.  This is the concrete content used
by `UniversalForcing.arithmeticOf`: both orbit objects are canonically
equivalent to `LogicNat`. -/
noncomputable def forcedQuotient_to_positiveRatio_orbit
    {K : Type} (h : ∃ x y : K, x ≠ y)
    (C : ComparisonOperator) (hC : SatisfiesLawsOfLogic C) :
    (forcedQuotientLogicRealization h).Orbit ≃
      (positiveRatioRealization C hC).Orbit :=
  (forcedQuotientLogicRealization h).orbitEquivLogicNat.trans
    (positiveRatioRealization C hC).orbitEquivLogicNat.symm

/-! ## 3. Canonical J comparison on positive ratios -/

/-- The canonical continuous positive-ratio comparison induced by J. -/
noncomputable def jcostComparison : ComparisonOperator :=
  fun x y => Cost.Jcost (x / y)

/-- The one-argument derived cost of the canonical comparison is J. -/
theorem derivedCost_jcostComparison :
    derivedCost jcostComparison = Cost.Jcost := by
  funext x
  simp [jcostComparison, derivedCost]

/-- The canonical J comparison satisfies the positive-ratio Law of Logic. -/
theorem jcostComparison_satisfies_laws :
    SatisfiesLawsOfLogic jcostComparison :=
  UnifiedForcingChain.T4ToT5.jcostComparison_satisfies_laws

/-- The positive-ratio Law of Logic forces an RCL-form combiner. -/
theorem positiveRatio_law_forces_RCL
    (C : ComparisonOperator) (hC : SatisfiesLawsOfLogic C) :
    ∃ (P : ℝ → ℝ → ℝ) (c : ℝ),
      DAlembert.Inevitability.HasMultiplicativeConsistency (derivedCost C) P ∧
      (∀ u v, P u v = 2*u + 2*v + c*u*v) :=
  LogicAsFunctionalEquation.RCL_is_unique_functional_form_of_logic C hC

/-! ## 4. T5 surface threaded through the distinction-generated floor -/

/-- T5, but threaded through the quotient generated by the supplied distinction.

The floor from `h` supplies the realization interface.  The continuous
positive-ratio Law-of-Logic surface supplies the analytic comparison setting.
The functional-equation theorem then proves uniqueness of J on positive reals.
-/
structure T5_FromDistinction
    {K : Type} (h : ∃ x y : K, x ≠ y) : Prop where
  /-- The T4 surface already forced on the quotient generated by `h`. -/
  t4 : T4_FromDistinction h
  /-- The forced quotient is a Law-of-Logic realization. -/
  floor_realization : Nonempty LogicRealization.{0, 0}
  /-- The canonical J positive-ratio comparison satisfies the Law of Logic. -/
  j_comparison_laws : SatisfiesLawsOfLogic jcostComparison
  /-- The forced quotient and the positive-ratio realization have equivalent
      recognition orbits, hence the same forced arithmetic carrier under
      `UniversalForcing.arithmeticOf`. -/
  orbit_invariant :
    Nonempty
      ((forcedQuotientLogicRealization h).Orbit ≃
        (positiveRatioRealization jcostComparison jcostComparison_satisfies_laws).Orbit)
  /-- The Law of Logic on positive ratios forces the RCL form. -/
  rcl_surface :
    ∃ (P : ℝ → ℝ → ℝ) (c : ℝ),
      DAlembert.Inevitability.HasMultiplicativeConsistency
        (derivedCost jcostComparison) P ∧
      (∀ u v, P u v = 2*u + 2*v + c*u*v)
  /-- J satisfies reciprocal symmetry. -/
  J_reciprocal : IsReciprocalCost Cost.Jcost
  /-- J is normalized at 1. -/
  J_normalized : IsNormalized Cost.Jcost
  /-- J satisfies the Recognition Composition Law. -/
  J_composition : SatisfiesCompositionLaw Cost.Jcost
  /-- J satisfies the canonical log-coordinate calibration. -/
  J_calibrated : IsCalibrated Cost.Jcost
  /-- J is continuous on positive reals. -/
  J_continuous : ContinuousOn Cost.Jcost (Set.Ioi 0)
  /-- Any cost satisfying the T5 hypotheses equals J on positive reals. -/
  uniqueness :
    ∀ (F : ℝ → ℝ),
      AczelSmoothnessPackage →
      IsReciprocalCost F →
      IsNormalized F →
      SatisfiesCompositionLaw F →
      IsCalibrated F →
      ContinuousOn F (Set.Ioi 0) →
      ∀ {x : ℝ}, 0 < x → F x = Cost.Jcost x

/-- The distinction-threaded T4 floor forces the T5 J-cost theorem surface. -/
theorem distinction_T4_to_T5
    {K : Type} {h : ∃ x y : K, x ≠ y}
    (h4 : T4_FromDistinction h) :
    T5_FromDistinction h where
  t4 := h4
  floor_realization := forcedQuotient_logicRealization_nonempty h
  j_comparison_laws := jcostComparison_satisfies_laws
  orbit_invariant :=
    ⟨forcedQuotient_to_positiveRatio_orbit h
      jcostComparison jcostComparison_satisfies_laws⟩
  rcl_surface :=
    positiveRatio_law_forces_RCL jcostComparison jcostComparison_satisfies_laws
  J_reciprocal := CostUniqueness.Jcost_is_reciprocal
  J_normalized := CostUniqueness.Jcost_is_normalized
  J_composition := CostUniqueness.Jcost_satisfies_composition_law
  J_calibrated := CostUniqueness.Jcost_is_calibrated
  J_continuous := CostUniqueness.Jcost_continuous_pos
  uniqueness := by
    intro F hAczel hRecip hNorm hComp hCalib hCont x hx
    let _ : AczelSmoothnessPackage := hAczel
    exact Cost.FunctionalEquation.law_of_logic_forces_jcost F
      hRecip hNorm hComp hCalib hCont x hx

/-- A supplied distinction forces T5 via the T4 surface already forced from
that same distinction. -/
theorem distinction_forces_T5
    {K : Type} (h : ∃ x y : K, x ≠ y) :
    T5_FromDistinction h :=
  distinction_T4_to_T5 (DistinctionToT4.distinction_forces_T4 h)

/-! ## Phase-2 bundle -/

/-- T−1 through T5 threaded through the supplied distinction. -/
structure DistinctionToT5_Spine
    (K : Type) (h : ∃ x y : K, x ≠ y) : Prop where
  /-- The already forced T0-T4 spine. -/
  early : DistinctionToT4.DistinctionToT0_Spine K h
  /-- The T5 J-cost theorem surface. -/
  t5 : T5_FromDistinction h

/-- A distinction witness forces T−1 through T5. -/
theorem distinction_forces_T0_to_T5
    (K : Type) (h : ∃ x y : K, x ≠ y) :
    DistinctionToT5_Spine K h where
  early := DistinctionToT4.distinction_forces_T0_to_T4 K h
  t5 := distinction_forces_T5 h

end DistinctionToJCost
end Foundation
end IndisputableMonolith
