import IndisputableMonolith.Foundation.DistinctionToDimension
import IndisputableMonolith.Foundation.RealityFromDistinction
import IndisputableMonolith.Foundation.DistinctionToArithmetic

/-!
# Distinction Forcing Audit

This module is a Lean-level analysis of what is, and is not, forced from a
bare object-level distinction.

The input under audit is always

```
h : exists x y : K, x ≠ y
```

The main result is the exact scope theorem:

* a distinction-threaded T-1-to-T8 spine exists for `K` iff `K` admits such a
  distinction;
* T7 is downstream of T8, not a parallel input;
* the legacy `CompleteForcingChain` is a global compatibility record, while
  the carrier-dependent content is the `DistinctionToT8_Spine K h`;
* the larger `RealityCertificate` splits into fields supplied by the chosen
  distinction and fields imported from upstream theorem certificates.
-/

namespace IndisputableMonolith
namespace Foundation
namespace DistinctionForcingAudit

open DistinctionToT4
open DistinctionToJCost
open DistinctionToPhi
open DistinctionToDimension
open RealityFromDistinction

/-! ## Audit taxonomy -/

/-- The named links in the T-1-to-T8 distinction audit. -/
inductive ChainLink where
  | tMinus1
  | t0
  | t1
  | t2
  | t3
  | t4
  | t5
  | t6
  | t8
  | t7
  deriving DecidableEq

/-- Where a link's proof surface is sourced in the distinction-threaded route. -/
inductive LinkSource where
  /-- The bare distinction witness supplies the floor interface. -/
  | distinctionWitness
  /-- The Boolean quotient generated by the distinction transports T0-T4. -/
  | forcedQuotientTransport
  /-- The analytic Law-of-Logic theorem supplies J uniqueness at T5. -/
  | analyticLawOfLogic
  /-- The uniform, growing, seed-closed hierarchy surface supplies T6. -/
  | hierarchyNormalForm
  /-- The Alexander-duality/linking route supplies T8. -/
  | topologicalLinking
  /-- T7 is a consequence once T8 has fixed `D = 3`. -/
  | downstreamOfDimension
  deriving DecidableEq

/-- The proof-source classification of each link in the current Lean route. -/
def linkSource : ChainLink -> LinkSource
  | ChainLink.tMinus1 => LinkSource.distinctionWitness
  | ChainLink.t0 => LinkSource.forcedQuotientTransport
  | ChainLink.t1 => LinkSource.forcedQuotientTransport
  | ChainLink.t2 => LinkSource.forcedQuotientTransport
  | ChainLink.t3 => LinkSource.forcedQuotientTransport
  | ChainLink.t4 => LinkSource.forcedQuotientTransport
  | ChainLink.t5 => LinkSource.analyticLawOfLogic
  | ChainLink.t6 => LinkSource.hierarchyNormalForm
  | ChainLink.t8 => LinkSource.topologicalLinking
  | ChainLink.t7 => LinkSource.downstreamOfDimension

/-- Machine-checkable summary of the source classification above. -/
structure LinkSourceAudit : Prop where
  tminus1_source :
    linkSource ChainLink.tMinus1 = LinkSource.distinctionWitness
  t0_source :
    linkSource ChainLink.t0 = LinkSource.forcedQuotientTransport
  t1_source :
    linkSource ChainLink.t1 = LinkSource.forcedQuotientTransport
  t2_source :
    linkSource ChainLink.t2 = LinkSource.forcedQuotientTransport
  t3_source :
    linkSource ChainLink.t3 = LinkSource.forcedQuotientTransport
  t4_source :
    linkSource ChainLink.t4 = LinkSource.forcedQuotientTransport
  t5_source :
    linkSource ChainLink.t5 = LinkSource.analyticLawOfLogic
  t6_source :
    linkSource ChainLink.t6 = LinkSource.hierarchyNormalForm
  t8_source :
    linkSource ChainLink.t8 = LinkSource.topologicalLinking
  t7_source :
    linkSource ChainLink.t7 = LinkSource.downstreamOfDimension

/-- The source classification is closed by reflexive computation. -/
theorem linkSourceAudit_holds : LinkSourceAudit where
  tminus1_source := rfl
  t0_source := rfl
  t1_source := rfl
  t2_source := rfl
  t3_source := rfl
  t4_source := rfl
  t5_source := rfl
  t6_source := rfl
  t8_source := rfl
  t7_source := rfl

/-! ## What the distinction actually forces -/

/-- A carrier-dependent, distinction-threaded T-1-through-T8 spine exists. -/
def ThreadedSpineExists (K : Type) : Prop :=
  exists h : (exists x y : K, x ≠ y), DistinctionToT8_Spine K h

/-- A full audited chain exists, with the local dependency equalities exposed. -/
structure ForcedChainFromDistinction
    (K : Type) (h : exists x y : K, x ≠ y) : Prop where
  /-- T-1 through T4 on the quotient generated by this distinction. -/
  tminus1_to_t4 : DistinctionToT0_Spine K h
  /-- T5 J uniqueness threaded through the T4 surface. -/
  t5 : T5_FromDistinction h
  /-- T6 phi forcing threaded through the T5 surface. -/
  t6 : T6_FromDistinction h
  /-- T8 dimension forcing threaded through the T6 surface. -/
  t8 : T8_FromDistinction h
  /-- T7 eight-tick forcing downstream of T8. -/
  t7 : T7_FromDistinction h
  /-- T5 consumes the same T4 surface produced by the forced quotient. -/
  t5_uses_t4 : t5.t4 = tminus1_to_t4.t4
  /-- T6 consumes the same T5 surface produced from the distinction. -/
  t6_uses_t5 : t6.hierarchy.t5 = t5
  /-- T8 consumes the same T6 surface produced from the distinction. -/
  t8_uses_t6 : t8.t6 = t6
  /-- T7 consumes the same T8 surface, so it is downstream of dimension. -/
  t7_uses_t8 : t7.t8 = t8

/-- Constructor for the audited T-1-to-T8 chain from one distinction. -/
theorem forcedChainFromDistinction_holds
    (K : Type) (h : exists x y : K, x ≠ y) :
    ForcedChainFromDistinction K h := by
  let spine := distinction_forces_T0_to_T8 K h
  exact {
    tminus1_to_t4 := spine.t0_to_t6.t0_to_t5.early
    t5 := spine.t0_to_t6.t0_to_t5.t5
    t6 := spine.t0_to_t6.t6
    t8 := spine.t8
    t7 := spine.t7
    t5_uses_t4 := Subsingleton.elim _ _
    t6_uses_t5 := Subsingleton.elim _ _
    t8_uses_t6 := Subsingleton.elim _ _
    t7_uses_t8 := Subsingleton.elim _ _
  }

/-- Existence of the carrier-dependent T-1-to-T8 spine is exactly
object-level distinguishability of the carrier. -/
theorem threaded_spine_exists_iff_distinction (K : Type) :
    ThreadedSpineExists K <-> exists x y : K, x ≠ y := by
  constructor
  · rintro ⟨h, _spine⟩
    exact h
  · intro h
    exact ⟨h, distinction_forces_T0_to_T8 K h⟩

/-- Without an object-level distinction, the carrier-dependent forcing spine
does not exist. -/
theorem no_distinction_no_threaded_spine
    (K : Type) (hnone : ¬ exists x y : K, x ≠ y) :
    ¬ ThreadedSpineExists K := by
  intro hspine
  exact hnone ((threaded_spine_exists_iff_distinction K).mp hspine)

/-- There exists an audited chain exactly when the carrier admits a distinction. -/
def AuditedChainExists (K : Type) : Prop :=
  exists h : (exists x y : K, x ≠ y), ForcedChainFromDistinction K h

/-- Exact "what if" theorem for the audited chain: if and only if a distinction
is available, the distinction-threaded audit exists. -/
theorem audited_chain_exists_iff_distinction (K : Type) :
    AuditedChainExists K <-> exists x y : K, x ≠ y := by
  constructor
  · rintro ⟨h, _audit⟩
    exact h
  · intro h
    exact ⟨h, forcedChainFromDistinction_holds K h⟩

/-! ## Compatibility boundary: global chain versus threaded chain -/

/-- The legacy complete-chain record attached to a threaded spine is the global
compatibility record, not additional carrier data. -/
theorem legacy_projection_is_global
    (K : Type) (h : exists x y : K, x ≠ y) :
    threaded_spine_to_legacy_complete_chain
        (distinction_forces_T0_to_T8 K h) =
      legacy_complete_chain_is_global :=
  rfl

/-! ## Forces versus instantiates: the honest split of the spine

The single most important honesty fix is not about T-1. It is the separation
between the part of the chain the carrier genuinely forces (T-1 through T4, on
the quotient generated by `h`) and the part it merely *instantiates* (T5 through
T8, which are carrier-independent theorems re-exposed beside the floor).

`law_of_logic_forces_jcost` is a theorem about `ℝ`; `φ`-forcing is about the
golden equation; `D = 3` is Alexander duality. None consume `K`. The structure
below records this split and proves the instantiated chain is the global record
independent of `K` and `h`. -/

/-- The carrier-dependent part of the spine: T-1 through T4 on the quotient
generated by the supplied distinction. -/
def CarrierForcedFloor (K : Type) (h : exists x y : K, x ≠ y) : Prop :=
  DistinctionToT4.DistinctionToT0_Spine K h

/-- Honest split: the carrier forces the floor; it only instantiates the
carrier-independent upper chain. -/
structure ForcesVsInstantiates
    (K : Type) (h : exists x y : K, x ≠ y) : Prop where
  /-- Carrier-dependent and genuinely threaded through `h`. -/
  carrier_forced_floor : CarrierForcedFloor K h
  /-- Carrier-independent global chain, instantiated beside the floor. -/
  instantiated_chain : Foundation.UnifiedForcingChain.CompleteForcingChain
  /-- The instantiated chain equals the global record, hence does not depend on
      `K` or `h`. This is the machine-checkable witness that T5 through T8 are
      not generated from the carrier. -/
  chain_is_global :
    instantiated_chain = legacy_complete_chain_is_global

/-- Every inhabited carrier with a distinction admits the honest split. The
floor is carrier-forced; the upper chain is instantiated, not generated. -/
theorem forcesVsInstantiates_holds
    (K : Type) (h : exists x y : K, x ≠ y) :
    ForcesVsInstantiates K h where
  carrier_forced_floor := DistinctionToT4.distinction_forces_T0_to_T4 K h
  instantiated_chain := legacy_complete_chain_is_global
  chain_is_global := rfl

/-- Scope record for the larger reality certificate. -/
structure RealityScopeAudit
    (K : Type) [Nonempty K] (h : exists x y : K, x ≠ y) : Prop where
  /-- The bundled reality certificate. -/
  reality : RealityCertificate K
  /-- Fields supplied by the chosen distinction itself. -/
  distinction_supplies : DistinctionSuppliedFields K
  /-- Fields imported from upstream theorem certificates. -/
  upstream_supplies : UpstreamSuppliedFields
  /-- The type-level equivalence between the bundle and the split. -/
  certificate_split :
    RealityCertificate K <->
      DistinctionSuppliedFields K ∧ UpstreamSuppliedFields

/-- Constructor for the reality-scope audit. -/
theorem realityScopeAudit_holds
    (K : Type) [Nonempty K] (h : exists x y : K, x ≠ y) :
    RealityScopeAudit K h := by
  have hsplit : DistinctionSuppliedFields K ∧ UpstreamSuppliedFields :=
    bundling_decomposition K h
  exact {
    reality := recognition_chain_certificate_from_distinction K h
    distinction_supplies := hsplit.1
    upstream_supplies := hsplit.2
    certificate_split := realityCertificate_eq_decomposition K
  }

/-- The larger `RealityCertificate` exists exactly when the inhabited carrier
admits an object-level distinction. -/
theorem reality_certificate_exists_iff_distinction
    (K : Type) [Nonempty K] :
    Nonempty (RealityCertificate K) <-> exists x y : K, x ≠ y := by
  constructor
  · rintro ⟨cert⟩
    exact cert.distinction
  · intro h
    exact ⟨recognition_chain_certificate_from_distinction K h⟩

/-! ## Single master audit -/

/-- One object that records the exact distinction-forcing analysis. -/
structure DistinctionForcingAnalysis
    (K : Type) [Nonempty K] (h : exists x y : K, x ≠ y) : Prop where
  /-- Link-source classification for T-1 through T8 and downstream T7. -/
  source_audit : LinkSourceAudit
  /-- The carrier-dependent audited chain. -/
  forced_chain : ForcedChainFromDistinction K h
  /-- The exact iff for threaded T-1-to-T8 spine existence. -/
  threaded_iff_distinction :
    ThreadedSpineExists K <-> exists x y : K, x ≠ y
  /-- The exact iff for audited chain existence. -/
  audited_iff_distinction :
    AuditedChainExists K <-> exists x y : K, x ≠ y
  /-- The larger reality-certificate scope split. -/
  reality_scope : RealityScopeAudit K h

/-- Master theorem: given one object-level distinction, the exact audit of
what follows from that distinction is itself forced. -/
theorem distinction_forcing_analysis_holds
    (K : Type) [Nonempty K] (h : exists x y : K, x ≠ y) :
    DistinctionForcingAnalysis K h where
  source_audit := linkSourceAudit_holds
  forced_chain := forcedChainFromDistinction_holds K h
  threaded_iff_distinction := threaded_spine_exists_iff_distinction K
  audited_iff_distinction := audited_chain_exists_iff_distinction K
  reality_scope := realityScopeAudit_holds K h

/-- Minimal Boolean instance of the audit. -/
theorem bool_distinction_forcing_analysis :
    DistinctionForcingAnalysis Bool ⟨false, true, Bool.noConfusion⟩ :=
  distinction_forcing_analysis_holds Bool
    ⟨false, true, Bool.noConfusion⟩

/-! ## Arithmetic side: the distinction also forces its `ArithmeticOf`

The spine above audits the physics chain (T-1 through T8). The companion fact is
that the same distinction forces its *arithmetic*: the initial Peano object
`LogicNat`, with the Peano surface, countable, and canonical between any two
distinctions. The continuum is not forced (ℝ is uncountable, hence not faithfully
certifiable from countable distinction data). See
`IndisputableMonolith.Foundation.DistinctionToArithmetic`. -/

/-- A distinction on `K` forces the initial Peano arithmetic object, whose carrier
is canonically `LogicNat`. This is the arithmetic-side companion to the
T-1-to-T8 spine. -/
theorem distinction_forces_arithmetic (K : Type) [DecidableEq K]
    (h : ∃ x y : K, x ≠ y) :
    ∃ (x y : K) (hxy : x ≠ y),
      Nonempty ((DistinctionToArithmetic.arithmeticOfDistinction x y hxy).peano.carrier
        ≃ ArithmeticFromLogic.LogicNat) :=
  DistinctionToArithmetic.distinction_forces_arithmeticOf h

/-- The full distinction-to-arithmetic certificate (forces an initial Peano
object, countable, with the Peano surface) holds for every carrier. -/
theorem distinction_arithmetic_cert (K : Type) [DecidableEq K] :
    DistinctionToArithmetic.DistinctionArithmeticCert K :=
  DistinctionToArithmetic.distinctionArithmeticCert K

end DistinctionForcingAudit
end Foundation
end IndisputableMonolith
