import Mathlib
import IndisputableMonolith.Foundation.TMinus1ForcedFromDistinction
import IndisputableMonolith.Foundation.UnifiedForcingChain

/-!
# Distinction to T4

This module starts the real closure path from a supplied distinction witness to
the early forcing spine.

The point is not to return the global `Bool` chain while ignoring the witness.
Given

```
h : ∃ x y : K, x ≠ y
```

`TMinus1ForcedFromDistinction` constructs the forced observable quotient

```
Quotient (forcedObservableSetoid h)
```

and proves it equivalent to `Bool`.  Here we transport the Boolean
configuration space and recognition-work cost across that equivalence, yielding
a T0 recognition-work surface on the quotient generated by the distinction
itself.

This is Phase 1 of the full T−1→T8 closure.  T1-T4 will be routed through this
transported floor rather than through unthreaded global `Bool` facts.
-/

namespace IndisputableMonolith
namespace Foundation
namespace DistinctionToT4

open CostFromDistinction
open TMinus1ForcedFromDistinction

universe u

/-! ## The quotient forced by a distinction -/

/-- The observable quotient generated by a distinction witness. -/
abbrev ForcedQuotient {K : Type*} (h : ∃ x y : K, x ≠ y) :=
  Quotient (forcedObservableSetoid h)

/-- The forced quotient-to-Bool coordinate equivalence. -/
noncomputable def forcedQuotientBoolEquiv
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    ForcedQuotient h ≃ Bool :=
  forcedQuotientEquivBool h

/-! ## Transported configuration space -/

/-- The configuration space on the quotient forced by the distinction.  It is
the Boolean configuration space transported across the forced quotient
equivalence. -/
noncomputable instance forcedQuotientConfigSpace
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    ConfigSpace (ForcedQuotient h) where
  emp := (forcedQuotientBoolEquiv h).symm false
  join Γ₁ Γ₂ :=
    (forcedQuotientBoolEquiv h).symm
      ((forcedQuotientBoolEquiv h Γ₁) || (forcedQuotientBoolEquiv h Γ₂))
  IsConsistent Γ := forcedQuotientBoolEquiv h Γ = false
  Independent Γ₁ Γ₂ :=
    forcedQuotientBoolEquiv h Γ₁ = false ∨ forcedQuotientBoolEquiv h Γ₂ = false
  emp_consistent := by
    simp [forcedQuotientBoolEquiv]
  independent_symm := by
    intro Γ₁ Γ₂ h_indep
    exact h_indep.elim (fun h₁ => Or.inr h₁) (fun h₂ => Or.inl h₂)
  emp_independent := by
    intro Γ
    left
    simp [forcedQuotientBoolEquiv]
  join_comm := by
    intro Γ₁ Γ₂
    apply (forcedQuotientBoolEquiv h).injective
    cases h₁ : forcedQuotientBoolEquiv h Γ₁ <;>
      cases h₂ : forcedQuotientBoolEquiv h Γ₂ <;>
      simp [forcedQuotientBoolEquiv]
  join_assoc := by
    intro Γ₁ Γ₂ Γ₃
    apply (forcedQuotientBoolEquiv h).injective
    cases h₁ : forcedQuotientBoolEquiv h Γ₁ <;>
      cases h₂ : forcedQuotientBoolEquiv h Γ₂ <;>
      cases h₃ : forcedQuotientBoolEquiv h Γ₃ <;>
      simp [forcedQuotientBoolEquiv]
  emp_join := by
    intro Γ
    apply (forcedQuotientBoolEquiv h).injective
    cases hΓ : forcedQuotientBoolEquiv h Γ <;>
      simp [forcedQuotientBoolEquiv]
  consistent_of_join_indep := by
    intro Γ₁ Γ₂ _h_indep h₁ h₂
    change
      forcedQuotientBoolEquiv h
        ((forcedQuotientBoolEquiv h).symm
          (forcedQuotientBoolEquiv h Γ₁ || forcedQuotientBoolEquiv h Γ₂)) = false
    rw [h₁, h₂]
    simp [forcedQuotientBoolEquiv]
  inconsistent_of_join_indep_left := by
    intro Γ₁ Γ₂ _h_indep h₁ hjoin
    apply h₁
    by_cases hΓ₁ : forcedQuotientBoolEquiv h Γ₁ = false
    · exact hΓ₁
    · exfalso
      change
        forcedQuotientBoolEquiv h
          ((forcedQuotientBoolEquiv h).symm
            (forcedQuotientBoolEquiv h Γ₁ || forcedQuotientBoolEquiv h Γ₂)) = false at hjoin
      have htrue : forcedQuotientBoolEquiv h Γ₁ = true := by
        cases hp : forcedQuotientBoolEquiv h Γ₁
        · exact False.elim (hΓ₁ hp)
        · rfl
      rw [htrue] at hjoin
      cases h₂v : forcedQuotientBoolEquiv h Γ₂ <;>
        simp [h₂v, forcedQuotientBoolEquiv] at hjoin

@[simp] theorem forcedQuotientBoolEquiv_emp
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    forcedQuotientBoolEquiv h (ConfigSpace.emp : ForcedQuotient h) = false :=
by
  change forcedQuotientBoolEquiv h ((forcedQuotientBoolEquiv h).symm false) = false
  simp [forcedQuotientBoolEquiv]

@[simp] theorem forcedQuotientBoolEquiv_join
    {K : Type*} (h : ∃ x y : K, x ≠ y)
    (Γ₁ Γ₂ : ForcedQuotient h) :
    forcedQuotientBoolEquiv h (ConfigSpace.join Γ₁ Γ₂) =
      (forcedQuotientBoolEquiv h Γ₁ || forcedQuotientBoolEquiv h Γ₂) :=
by
  change
    forcedQuotientBoolEquiv h
      ((forcedQuotientBoolEquiv h).symm
        (forcedQuotientBoolEquiv h Γ₁ || forcedQuotientBoolEquiv h Γ₂)) =
      (forcedQuotientBoolEquiv h Γ₁ || forcedQuotientBoolEquiv h Γ₂)
  simp [forcedQuotientBoolEquiv]

/-! ## Transported recognition-work cost -/

/-- Recognition-work cost on the quotient generated by the distinction. -/
noncomputable def forcedQuotientRecognitionCost
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    CostFunction (ForcedQuotient h) where
  C Γ := UnifiedForcingChain.TMinus1ToT0.boolRecognitionCost.C
    (forcedQuotientBoolEquiv h Γ)
  nonneg := by
    intro Γ
    exact UnifiedForcingChain.TMinus1ToT0.boolRecognitionCost.nonneg
      (forcedQuotientBoolEquiv h Γ)
  dichotomy := by
    intro Γ
    change
      UnifiedForcingChain.TMinus1ToT0.boolRecognitionCost.C
        (forcedQuotientBoolEquiv h Γ) = 0 ↔
      forcedQuotientBoolEquiv h Γ = false
    exact UnifiedForcingChain.TMinus1ToT0.boolRecognitionCost.dichotomy
      (forcedQuotientBoolEquiv h Γ)
  additivity := by
    intro Γ₁ Γ₂ h_indep
    rw [forcedQuotientBoolEquiv_join]
    exact UnifiedForcingChain.TMinus1ToT0.boolRecognitionCost.additivity
      (forcedQuotientBoolEquiv h Γ₁) (forcedQuotientBoolEquiv h Γ₂) h_indep

/-- The transported cost is literally the Boolean recognition cost under the
forced quotient coordinate. -/
theorem forcedQuotientRecognitionCost_transport
    {K : Type*} (h : ∃ x y : K, x ≠ y) (Γ : ForcedQuotient h) :
    (forcedQuotientRecognitionCost h).C Γ =
      UnifiedForcingChain.TMinus1ToT0.boolRecognitionCost.C
        (forcedQuotientBoolEquiv h Γ) :=
  rfl

/-- The forced quotient carries the recognition-work constraint theorem. -/
theorem forcedQuotient_recognition_work_constraint
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    Nonempty (CostFunction.RecognitionWorkConstraintCert (ForcedQuotient h)) :=
  CostFunction.recognition_work_constraint_theorem
    (forcedQuotientRecognitionCost h)

/-! ## T0 on the distinction-generated quotient -/

/-- T0, but on the quotient generated by the supplied distinction rather than
the global Boolean floor. -/
structure T0_FromDistinction
    {K : Type u} (h : ∃ x y : K, x ≠ y) : Prop where
  /-- The forced quotient is Boolean. -/
  quotient_bool : Nonempty (ForcedQuotient h ≃ Bool)
  /-- The quotient has the transported configuration space. -/
  recognition_work :
    Nonempty (CostFunction.RecognitionWorkConstraintCert (ForcedQuotient h))
  /-- The empty/consistent quotient state has zero cost. -/
  consistency_cheap :
    (forcedQuotientRecognitionCost h).C
      ((forcedQuotientBoolEquiv h).symm false) = 0
  /-- Every inconsistent quotient state has positive cost. -/
  contradiction_expensive :
    ∀ Γ : ForcedQuotient h,
      ¬ConfigSpace.IsConsistent Γ →
        0 < (forcedQuotientRecognitionCost h).C Γ
  /-- Zero cost is exactly consistency on the forced quotient. -/
  logic_emergent :
    ∀ Γ : ForcedQuotient h,
      (forcedQuotientRecognitionCost h).C Γ = 0 ↔
        ConfigSpace.IsConsistent Γ
  /-- Recognition work is additive over independent joins on the forced quotient. -/
  additive_indep :
    ∀ Γ₁ Γ₂ : ForcedQuotient h,
      ConfigSpace.Independent Γ₁ Γ₂ →
        (forcedQuotientRecognitionCost h).C
          (ConfigSpace.join Γ₁ Γ₂) =
        (forcedQuotientRecognitionCost h).C Γ₁ +
          (forcedQuotientRecognitionCost h).C Γ₂

/-- A supplied distinction forces T0 on its own observable quotient. -/
theorem distinction_forces_T0
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    T0_FromDistinction h where
  quotient_bool := ⟨forcedQuotientBoolEquiv h⟩
  recognition_work := forcedQuotient_recognition_work_constraint h
  consistency_cheap := by
    rw [forcedQuotientRecognitionCost_transport]
    simp [forcedQuotientBoolEquiv]
    rfl
  contradiction_expensive := by
    intro Γ hΓ
    exact (CostFunction.cost_pos_iff_inconsistent
      (forcedQuotientRecognitionCost h) Γ).mpr hΓ
  logic_emergent := by
    intro Γ
    exact (forcedQuotientRecognitionCost h).dichotomy Γ
  additive_indep := by
    intro Γ₁ Γ₂ h_indep
    exact (forcedQuotientRecognitionCost h).additivity Γ₁ Γ₂ h_indep

/-! ## T1 on the distinction-generated quotient -/

/-- T1, but on the quotient generated by the supplied distinction. -/
structure T1_FromDistinction
    {K : Type u} (h : ∃ x y : K, x ≠ y) : Prop where
  /-- Inconsistent quotient states have positive recognition-work cost. -/
  inconsistent_positive :
    ∀ Γ : ForcedQuotient h,
      ¬ConfigSpace.IsConsistent Γ →
        0 < (forcedQuotientRecognitionCost h).C Γ
  /-- Zero-cost quotient states are consistent. -/
  zero_cost_consistent :
    ∀ Γ : ForcedQuotient h,
      (forcedQuotientRecognitionCost h).C Γ = 0 →
        ConfigSpace.IsConsistent Γ
  /-- The marked inconsistent quotient state is positive-cost. -/
  marked_inconsistent_positive :
    0 < (forcedQuotientRecognitionCost h).C
      ((forcedQuotientBoolEquiv h).symm true)

/-- T0 on the forced quotient forces T1 on the forced quotient. -/
theorem distinction_T0_to_T1
    {K : Type*} {h : ∃ x y : K, x ≠ y}
    (h0 : T0_FromDistinction h) :
    T1_FromDistinction h where
  inconsistent_positive := h0.contradiction_expensive
  zero_cost_consistent := fun Γ hzero => (h0.logic_emergent Γ).mp hzero
  marked_inconsistent_positive := by
    exact h0.contradiction_expensive ((forcedQuotientBoolEquiv h).symm true) (by
      change forcedQuotientBoolEquiv h ((forcedQuotientBoolEquiv h).symm true) ≠ false
      simp [forcedQuotientBoolEquiv])

/-- A distinction witness forces T1 on its own observable quotient. -/
theorem distinction_forces_T1
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    T1_FromDistinction h :=
  distinction_T0_to_T1 (distinction_forces_T0 h)

/-! ## T2 on the distinction-generated quotient -/

/-- T2, but on the quotient generated by the supplied distinction. -/
structure T2_FromDistinction
    {K : Type u} (h : ∃ x y : K, x ≠ y) : Prop where
  /-- Every quotient state is one of the two forced Boolean-coordinate states. -/
  state_dichotomy :
    ∀ Γ : ForcedQuotient h,
      Γ = (forcedQuotientBoolEquiv h).symm false ∨
      Γ = (forcedQuotientBoolEquiv h).symm true
  /-- The two forced quotient states are distinct. -/
  states_distinct :
    (forcedQuotientBoolEquiv h).symm false ≠
      (forcedQuotientBoolEquiv h).symm true
  /-- Zero cost selects the consistent quotient state. -/
  zero_cost_selects_consistency :
    ∀ Γ : ForcedQuotient h,
      (forcedQuotientRecognitionCost h).C Γ = 0 →
        Γ = (forcedQuotientBoolEquiv h).symm false
  /-- Positive cost selects the marked quotient state. -/
  positive_cost_selects_marked :
    ∀ Γ : ForcedQuotient h,
      0 < (forcedQuotientRecognitionCost h).C Γ →
        Γ = (forcedQuotientBoolEquiv h).symm true

/-- T1 on the forced quotient forces T2 on the forced quotient. -/
theorem distinction_T1_to_T2
    {K : Type*} {h : ∃ x y : K, x ≠ y}
    (h1 : T1_FromDistinction h) :
    T2_FromDistinction h where
  state_dichotomy := by
    intro Γ
    cases hb : forcedQuotientBoolEquiv h Γ
    · left
      apply (forcedQuotientBoolEquiv h).injective
      simpa [hb, forcedQuotientBoolEquiv]
    · right
      apply (forcedQuotientBoolEquiv h).injective
      simpa [hb, forcedQuotientBoolEquiv]
  states_distinct := by
    intro heq
    have hbool := congrArg (forcedQuotientBoolEquiv h) heq
    simp [forcedQuotientBoolEquiv] at hbool
  zero_cost_selects_consistency := by
    intro Γ hzero
    have hcons := h1.zero_cost_consistent Γ hzero
    change forcedQuotientBoolEquiv h Γ = false at hcons
    apply (forcedQuotientBoolEquiv h).injective
    simpa [hcons, forcedQuotientBoolEquiv]
  positive_cost_selects_marked := by
    intro Γ hpos
    rcases (show
        Γ = (forcedQuotientBoolEquiv h).symm false ∨
        Γ = (forcedQuotientBoolEquiv h).symm true from
        (by
          cases hb : forcedQuotientBoolEquiv h Γ
          · left
            apply (forcedQuotientBoolEquiv h).injective
            simpa [hb, forcedQuotientBoolEquiv]
          · right
            apply (forcedQuotientBoolEquiv h).injective
            simpa [hb, forcedQuotientBoolEquiv])) with hfalse | htrue
    · exfalso
      rw [hfalse] at hpos
      have hzero :
          (forcedQuotientRecognitionCost h).C
            ((forcedQuotientBoolEquiv h).symm false) = 0 := by
        rw [forcedQuotientRecognitionCost_transport]
        simp [forcedQuotientBoolEquiv]
        rfl
      rw [hzero] at hpos
      linarith
    · exact htrue

/-- A distinction witness forces T2 on its own observable quotient. -/
theorem distinction_forces_T2
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    T2_FromDistinction h :=
  distinction_T1_to_T2 (distinction_forces_T1 h)

/-! ## T3 on the distinction-generated quotient -/

/-- T3, but on the quotient generated by the supplied distinction. -/
structure T3_FromDistinction
    {K : Type u} (h : ∃ x y : K, x ≠ y) : Prop where
  /-- The empty consistent quotient entry is zero-cost. -/
  empty_balanced :
    (forcedQuotientRecognitionCost h).C
      (ConfigSpace.emp : ForcedQuotient h) = 0
  /-- Empty join is neutral on quotient states. -/
  empty_join_left :
    ∀ Γ : ForcedQuotient h,
      ConfigSpace.join (ConfigSpace.emp : ForcedQuotient h) Γ = Γ
  /-- Empty join is cost-neutral. -/
  empty_join_cost_neutral :
    ∀ Γ : ForcedQuotient h,
      (forcedQuotientRecognitionCost h).C
        (ConfigSpace.join (ConfigSpace.emp : ForcedQuotient h) Γ) =
      (forcedQuotientRecognitionCost h).C Γ
  /-- Independent joins are ledger-additive. -/
  independent_join_additive :
    ∀ Γ₁ Γ₂ : ForcedQuotient h,
      ConfigSpace.Independent Γ₁ Γ₂ →
        (forcedQuotientRecognitionCost h).C
          (ConfigSpace.join Γ₁ Γ₂) =
        (forcedQuotientRecognitionCost h).C Γ₁ +
          (forcedQuotientRecognitionCost h).C Γ₂

/-- T0 plus T2 on the forced quotient forces T3 on the forced quotient. -/
theorem distinction_T0_T2_to_T3
    {K : Type*} {h : ∃ x y : K, x ≠ y}
    (h0 : T0_FromDistinction h) (_h2 : T2_FromDistinction h) :
    T3_FromDistinction h where
  empty_balanced := h0.consistency_cheap
  empty_join_left := by
    intro Γ
    exact ConfigSpace.emp_join Γ
  empty_join_cost_neutral := by
    intro Γ
    rw [ConfigSpace.emp_join]
  independent_join_additive := h0.additive_indep

/-- A distinction witness forces T3 on its own observable quotient. -/
theorem distinction_forces_T3
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    T3_FromDistinction h :=
  distinction_T0_T2_to_T3 (distinction_forces_T0 h) (distinction_forces_T2 h)

/-! ## T4 on the distinction-generated quotient

The `/reality` library continues here with `T4_FromDistinction`, which packages a
`Recognition.Recognize` witness and a `Recognition.RecognitionStructure` on the
forced quotient. Those live in the recognition-operator layer that the public
core slice does not ship, so the public `DistinctionToT4` stops at T3. The
ledger-floor T0 bridge below depends only on the T0/T1/T2/T3 surface and the
transported recognition cost. -/

/-! ## Session bundle: T−1 through T3 -/

/-- Completed early slice of the full closure: the supplied distinction forces
the T−1 floor and T0-T3 on its own observable quotient. (The `/reality` version
also carries T4 via the recognition-operator layer; see the note above.) -/
structure DistinctionToT0_Spine
    (K : Type) (h : ∃ x y : K, x ≠ y) : Prop where
  /-- The marked pair forced by the distinction. -/
  marked_pair : Nonempty (BooleanProjectionFromMark.MarkedPair K)
  /-- The observable floor generated by the distinction. -/
  observable_floor :
    ObservableFloor.ObservableFloorWitness K
      (TMinus1ForcedFromDistinction.forcedObservableSetoid h).r
  /-- The forced quotient is Boolean. -/
  quotient_bool :
    Nonempty (ForcedQuotient h ≃ Bool)
  /-- T0 holds on the forced quotient. -/
  t0 : T0_FromDistinction h
  /-- T1 holds on the forced quotient. -/
  t1 : T1_FromDistinction h
  /-- T2 holds on the forced quotient. -/
  t2 : T2_FromDistinction h
  /-- T3 holds on the forced quotient. -/
  t3 : T3_FromDistinction h

/-- A distinction witness forces the T−1-to-T4 spine. -/
theorem distinction_forces_T0_spine
    (K : Type) (h : ∃ x y : K, x ≠ y) :
    DistinctionToT0_Spine K h where
  marked_pair := ⟨TMinus1ForcedFromDistinction.markedPairOfDistinction h⟩
  observable_floor := TMinus1ForcedFromDistinction.forcedObservableFloor h
  quotient_bool := ⟨forcedQuotientBoolEquiv h⟩
  t0 := distinction_forces_T0 h
  t1 := distinction_forces_T1 h
  t2 := distinction_forces_T2 h
  t3 := distinction_forces_T3 h

/-- Preferred name for the completed early spine theorem (public core: T0-T3). -/
theorem distinction_forces_T0_to_T3
    (K : Type) (h : ∃ x y : K, x ≠ y) :
    DistinctionToT0_Spine K h :=
  distinction_forces_T0_spine K h

end DistinctionToT4
end Foundation
end IndisputableMonolith
