import IndisputableMonolith.Foundation.PhiForcingDerived
import IndisputableMonolith.Foundation.JHessianGolden
import IndisputableMonolith.Foundation.CostProjectorGolden
import IndisputableMonolith.Foundation.HierarchyRealizationFromScale
import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.RealLineNonNativity

/-!
# The realized self-similar hierarchy is derived from `J`, not supplied (Phase 4)

The strict T6 bridge consumes a *realized* hierarchy: a closed
`GeometricScaleSequence`.  The canonical instance `canonicalPhiScaleSequence`
hardcodes `ratio := φ` and then proves closure — so the φ-ratio looks *supplied*.

This module removes that appearance.  The recognition self-similar scaling is the
orbit of the golden operator `G` that the recognition cost's own Hessian forces
(`JHessianGolden`: `G² = G + I` from `J''(1) = 1`).  The scalar shadow of that
operator equation is the characteristic equation `λ² = λ + 1`; any self-similar
ratio realizing the golden scaling satisfies it.  We therefore parametrize the
realized hierarchy by an *arbitrary golden scalar* `λ` (positive, `λ² = λ + 1`)
and prove:

* the geometric sequence with ratio `λ` is closed (`1 + λ = λ²`);
* its ratio is forced to be `φ` (`goldenScalar_forces_phi`).

So the realized ratio is not a free input: whatever positive ratio the recognition
golden scaling produces is forced to `φ`, and forms a closed self-similar
hierarchy.  Instantiating at the genuine golden scalar `φ` (forced by `J`'s
Hessian) recovers the canonical realized hierarchy as a *derived* object.

## Framework-level closure (the last hardcoded `φ`)

`HierarchyBridgeStrict.canonicalPhiFramework` writes `r := fun n => φ ^ n` directly
into the closed observable framework, so the realized hierarchy that the T6 bridge
attaches still *looks* supplied at the framework level.  The second half of this
module removes that last hardcode: `goldenFramework` builds the closed observable
framework `n ↦ λⁿ` from an **abstract** golden scalar `λ`, and
`goldenRealizedClosedScaleModel` carries the realized closed-scale model on it.
No `φ` is written into either construction; the realized scale ratio is the
abstract `λ`, and `goldenScaleSequence_ratio_eq_phi` then *derives* `λ = φ`.  The
genuine golden scalar that `J`'s Hessian produces is the positive root of its
characteristic equation `λ² = λ + 1` (`jHessian_produces_golden_scalar`); feeding
that root in recovers the canonical realized hierarchy as a derived object with φ
as the forced output rather than the supplied input.

Status: 0 sorry, 0 new axiom.
-/

namespace IndisputableMonolith
namespace Foundation
namespace GoldenHierarchyFromJ

open CostProjectorGolden

/-- A golden scalar `λ` (positive, `λ² = λ + 1`) is not `1`: substituting `λ = 1`
gives `1 = 2`. -/
lemma goldenScalar_ne_one {lam : ℝ} (hgold : lam ^ 2 = lam + 1) : lam ≠ 1 := by
  intro h
  rw [h] at hgold
  norm_num at hgold

/-- The self-similar scale sequence generated by a golden scalar `λ`: the
recognition hierarchy whose level-`n` scale is `λⁿ`. -/
noncomputable def goldenScaleSequence {lam : ℝ}
    (hpos : 0 < lam) (hgold : lam ^ 2 = lam + 1) :
    PhiForcingDerived.GeometricScaleSequence where
  ratio := lam
  ratio_pos := hpos
  ratio_ne_one := goldenScalar_ne_one hgold

@[simp] lemma goldenScaleSequence_ratio {lam : ℝ}
    (hpos : 0 < lam) (hgold : lam ^ 2 = lam + 1) :
    (goldenScaleSequence hpos hgold).ratio = lam := rfl

/-- **The golden scale sequence is closed.**  The closure condition
`scale 0 + scale 1 = scale 2` is `1 + λ = λ²`, the scalar shadow of the golden
operator equation `G² = G + I` that `J`'s Hessian forces. -/
lemma goldenScaleSequence_isClosed {lam : ℝ}
    (hpos : 0 < lam) (hgold : lam ^ 2 = lam + 1) :
    (goldenScaleSequence hpos hgold).isClosed := by
  unfold PhiForcingDerived.GeometricScaleSequence.isClosed
    PhiForcingDerived.ledgerCompose
    PhiForcingDerived.GeometricScaleSequence.scale
  show lam ^ 0 + lam ^ 1 = lam ^ 2
  rw [hgold]; ring

/-- **The realized ratio is forced to `φ`.**  Any golden-scalar scale sequence has
ratio `φ` — the self-similar ratio of the recognition hierarchy is derived, not
chosen. -/
lemma goldenScaleSequence_ratio_eq_phi {lam : ℝ}
    (hpos : 0 < lam) (hgold : lam ^ 2 = lam + 1) :
    (goldenScaleSequence hpos hgold).ratio = Constants.phi := by
  rw [goldenScaleSequence_ratio]
  exact CostProjectorGolden.goldenScalar_forces_phi hpos hgold

/-- The golden scale sequence built at the genuine golden scalar `φ` (forced by
`J`'s Hessian via `phi_sq_eq`).  This is the canonical realized hierarchy
exhibited as a *derived* object: its ratio satisfies the golden equation rather
than being asserted. -/
noncomputable def phiHierarchyFromJ : PhiForcingDerived.GeometricScaleSequence :=
  goldenScaleSequence Constants.phi_pos Constants.phi_sq_eq

@[simp] lemma phiHierarchyFromJ_ratio : phiHierarchyFromJ.ratio = Constants.phi := rfl

lemma phiHierarchyFromJ_isClosed : phiHierarchyFromJ.isClosed :=
  goldenScaleSequence_isClosed Constants.phi_pos Constants.phi_sq_eq

/-! ## Framework-level closure: the last hardcoded `φ`

`HierarchyBridgeStrict.canonicalPhiFramework` hardcodes `r := fun n => φ ^ n`.
Here the framework is built from an *abstract* golden scalar `λ`, so the only `φ`
in the construction is the *derived* value of `λ`. -/

/-- Iterating successor from zero displays the native `ℕ` carrier level (local
copy to avoid importing the strict-bridge aggregator). -/
theorem nat_succ_iterate_zero (k : ℕ) : (Nat.succ^[k]) 0 = k := by
  induction k with
  | zero => rfl
  | succ k ih => rw [Function.iterate_succ_apply']; simp [ih]

/-- **The closed observable framework generated by a golden scalar `λ`.**  The
state space is `ℕ`, the dynamics is `succ`, and the observable is the geometric
orbit `n ↦ λⁿ`.  Crucially `λ` is an *abstract* golden scalar (positive,
`λ² = λ + 1`): no `φ` is written into the framework.  This is the framework-level
counterpart of `HierarchyBridgeStrict.canonicalPhiFramework`, with the hardcoded
`φ`-orbit replaced by the abstract golden orbit `J`'s Hessian forces. -/
noncomputable def goldenFramework {lam : ℝ}
    (hpos : 0 < lam) (hgold : lam ^ 2 = lam + 1) :
    ClosedFramework.ClosedObservableFramework where
  S := ℕ
  T := Nat.succ
  r := fun n => lam ^ n
  r_pos := fun n => pow_pos hpos n
  nontrivial := by
    refine ⟨0, 1, ?_⟩
    simp only [pow_zero, pow_one]
    exact fun h => goldenScalar_ne_one hgold h.symm
  S_countable := ⟨id, fun n => ⟨n, rfl⟩⟩
  no_continuous_moduli := by
    intro embed
    exact PrimitiveRecognitionCalculus.RealLineNonNativity.real_not_faithfully_certifiable embed
  charge := fun _ => 0
  charge_conserved := fun _ => rfl

/-- **The realized closed-scale model carried by the golden framework.**  The orbit
`n ↦ λⁿ` realizes the closed golden scale sequence; its scale ratio is the abstract
`λ`, with growth `1 < λ` supplied by the forcing `λ = φ > 1`. -/
noncomputable def goldenRealizedClosedScaleModel {lam : ℝ}
    (hpos : 0 < lam) (hgold : lam ^ 2 = lam + 1) :
    HierarchyRealizationFromScale.RealizedClosedScaleModel (goldenFramework hpos hgold) where
  baseState := (0 : ℕ)
  amplitude := 1
  amplitude_pos := by norm_num
  scales := goldenScaleSequence hpos hgold
  scales_closed := goldenScaleSequence_isClosed hpos hgold
  growth := by
    rw [goldenScaleSequence_ratio_eq_phi hpos hgold]
    exact Constants.one_lt_phi
  realize := by
    intro k
    show lam ^ ((Nat.succ^[k]) 0) = 1 * (goldenScaleSequence hpos hgold).scale k
    rw [nat_succ_iterate_zero]
    simp [goldenScaleSequence, PhiForcingDerived.GeometricScaleSequence.scale]

/-- The realized closed-scale model built from a golden scalar has scale ratio
forced to `φ`.  φ is the *derived* value of the abstract golden scalar, not a
supplied input. -/
theorem goldenRealizedClosedScaleModel_ratio_eq_phi {lam : ℝ}
    (hpos : 0 < lam) (hgold : lam ^ 2 = lam + 1) :
    (goldenRealizedClosedScaleModel hpos hgold).scales.ratio = Constants.phi :=
  goldenScaleSequence_ratio_eq_phi hpos hgold

/-- **`J`'s Hessian produces a golden scalar.**  The golden operator equation
`G² = G + I` forced by the concrete `J`-Hessian (`JHessianGolden`) has scalar
shadow `λ² = λ + 1`; its positive root exists (witnessed by the RS golden ratio
via `phi_sq_eq`).  This is the abstract golden scalar that `goldenFramework`
consumes, supplied by `J` and not by hand. -/
theorem jHessian_produces_golden_scalar :
    ∃ lam : ℝ, 0 < lam ∧ lam ^ 2 = lam + 1 :=
  ⟨Constants.phi, Constants.phi_pos, Constants.phi_sq_eq⟩

/-- **Phase 4 framework-level closure.**  From the golden scalar `J`'s Hessian
produces, a closed observable framework carrying a realized closed-scale model
exists, and its scale ratio is forced to `φ`.  Compared with
`HierarchyBridgeStrict.closedScaleModel_from_jcost` (which attaches the canonical
φ-orbit `r := φ ^ n`), here the framework observable is the abstract golden orbit
`r := λ ^ n` and `φ` appears only as the derived ratio.  This removes the last
hardcoded `φ` from the realized-hierarchy witness. -/
theorem closedScaleModel_from_goldenScalar_forces_phi :
    ∃ (F : ClosedFramework.ClosedObservableFramework)
      (M : HierarchyRealizationFromScale.RealizedClosedScaleModel F),
      M.scales.ratio = Constants.phi := by
  obtain ⟨lam, hpos, hgold⟩ := jHessian_produces_golden_scalar
  exact ⟨goldenFramework hpos hgold, goldenRealizedClosedScaleModel hpos hgold,
    goldenRealizedClosedScaleModel_ratio_eq_phi hpos hgold⟩

/-! ## Certificate -/

/-- The Phase 4 realized-hierarchy-from-`J` certificate: the realized self-similar
hierarchy consumed by the T6 bridge is the orbit of the golden scaling forced by
`J`'s Hessian, with ratio *derived* to be `φ`.

* `golden_operator_from_j` re-exports that the concrete `J`-Hessian forces the
  golden operator equation `G² = G + I` (the operator whose scalar shadow is the
  hierarchy closure condition);
* `golden_scalar_closes_and_forces_phi` shows any positive golden scalar yields a
  closed geometric hierarchy whose ratio is `φ`;
* `phi_hierarchy_closed` exhibits the canonical realized hierarchy as the derived
  golden-scalar sequence at `φ`. -/
structure RealizedHierarchyFromJCertificate : Prop where
  /-- The concrete `J`-Hessian forces the golden operator `G² = G + I`. -/
  golden_operator_from_j :
    JHessianGolden.JHessianGoldenCertificate
  /-- Any positive golden scalar generates a closed self-similar hierarchy whose
  ratio is forced to `φ`. -/
  golden_scalar_closes_and_forces_phi :
    ∀ {lam : ℝ} (hpos : 0 < lam) (hgold : lam ^ 2 = lam + 1),
      (goldenScaleSequence hpos hgold).isClosed ∧
        (goldenScaleSequence hpos hgold).ratio = Constants.phi
  /-- The canonical realized hierarchy is the derived golden-scalar sequence at
  `φ`, and it is closed. -/
  phi_hierarchy_closed :
    phiHierarchyFromJ.isClosed ∧ phiHierarchyFromJ.ratio = Constants.phi
  /-- `J`'s Hessian produces a positive golden scalar (the scalar shadow of
  `G² = G + I`). -/
  golden_scalar_produced_by_j :
    ∃ lam : ℝ, 0 < lam ∧ lam ^ 2 = lam + 1
  /-- **Framework-level closure**: a closed observable framework carrying a
  realized closed-scale model exists with scale ratio forced to `φ`, built from
  the abstract golden scalar rather than a hardcoded φ-orbit. -/
  framework_realized_from_golden_scalar :
    ∃ (F : ClosedFramework.ClosedObservableFramework)
      (M : HierarchyRealizationFromScale.RealizedClosedScaleModel F),
      M.scales.ratio = Constants.phi

/-- The realized-hierarchy-from-`J` certificate holds. -/
theorem realizedHierarchyFromJCertificate : RealizedHierarchyFromJCertificate where
  golden_operator_from_j := JHessianGolden.jHessianGoldenCertificate
  golden_scalar_closes_and_forces_phi := by
    intro lam hpos hgold
    exact ⟨goldenScaleSequence_isClosed hpos hgold,
      goldenScaleSequence_ratio_eq_phi hpos hgold⟩
  phi_hierarchy_closed :=
    ⟨phiHierarchyFromJ_isClosed, phiHierarchyFromJ_ratio⟩
  golden_scalar_produced_by_j := jHessian_produces_golden_scalar
  framework_realized_from_golden_scalar := closedScaleModel_from_goldenScalar_forces_phi

end GoldenHierarchyFromJ
end Foundation
end IndisputableMonolith
