import IndisputableMonolith.Foundation.HamiltonianEmergence

/-!
# Operator-level Hamiltonian emergence: the finite-dimensional Stone generator

Build-spine item HLG-2.1 of `simulation/Reality_Simulation_Master_Plan.html`.

`HamiltonianEmergence` proves the SCALAR foundation: the J-cost near equilibrium is a quadratic form,
`J(1 + eps) = eps^2/2 + O(eps^3)`, and the total cost approximates the quadratic energy. It then leaves
the operator-level claim `R-hat = exp(-i H-hat * 8 tau_0 / hbar)` as a HYPOTHESIS, citing "Stone's
theorem for discrete unitary groups not in Mathlib".

That citation mis-frames the problem. The recognition register is FINITE-dimensional (the 8-tick
register is `C^N`), so the operator-level statement needs no infinite-dimensional Stone theory at all.
On `C^N` everything is matrix exponentials, and Mathlib has the full API. This module proves the
finite-dimensional Stone generator outright:

* the complexified small-deviation Hamiltonian `Hc ev` (a real symmetric matrix viewed over `C`) is
  Hermitian, so it IS a self-adjoint generator;
* the generator `gen ev = -i * Hc ev` is skew-Hermitian;
* the evolution family `U ev t = exp(t * gen ev)` is a one-parameter group: `U 0 = 1` and
  `U s * U t = U (s + t)`;
* every `U ev t` is unitary (`(U t)^H * U t = 1` and `U t * (U t)^H = 1`) and lies in the unitary
  group `Matrix.unitaryGroup (Fin N) C`;
* the discrete evolution step already defined in `HamiltonianEmergence`,
  `DiscreteEvolution.step ev psi = psi - i * (Hc ev *v psi)`, is EXACTLY the first-order truncation
  `(1 + gen ev) *v psi` of the exponential `U ev 1 = exp(gen ev) = 1 + gen ev + gen ev^2/2 + ...`.

So `R-hat`'s small-deviation linearization is a genuine unitary one-parameter group generated by a
self-adjoint `H-hat`. This is the operator-level content of "quantum mechanics is the high-frequency
limit of recognition dynamics", as a finite-dimensional THEOREM rather than a placeholder.

Honest status: CONDITIONAL THEOREM. The Stone-generator structure (Hermitian generator, unitary group,
first-order truncation) is a kernel THEOREM. What stays conditional is the identification that the FULL
nonlinear `R-hat` action equals this linear `step` to `O(eps^3)`: that rests on the proved scalar bound
`totalJcost_approx_quadratic` plus the modeling choice that `R-hat` linearizes to `step`, and the exact
operator `O(Delta^2)` exponential Taylor bound and the `Delta = 8 tau_0 / hbar` calibration remain named
residuals (the same units bridge as HLG-1.2).

Lean status: 0 sorry, 0 new axiom.
-/

namespace IndisputableMonolith.Foundation.HamiltonianEmergence

open NormedSpace
open scoped Matrix

noncomputable section

variable {N : ℕ}

/-! ## The complexified Hamiltonian and the skew-Hermitian generator -/

/-- The complexification of a discrete-evolution Hamiltonian: the real symmetric matrix
`ev.hamiltonian` viewed as a complex matrix. -/
def Hc (ev : DiscreteEvolution N) : Matrix (Fin N) (Fin N) ℂ :=
  Matrix.of (fun i j => (ev.hamiltonian i j : ℂ))

/-- The complexified Hamiltonian is Hermitian: a real symmetric matrix is self-adjoint over `C`. -/
theorem Hc_isHermitian (ev : DiscreteEvolution N) : (Hc ev).IsHermitian := by
  show (Hc ev)ᴴ = Hc ev
  ext i j
  simp only [Matrix.conjTranspose_apply, Hc, Matrix.of_apply, Complex.star_def,
    Complex.conj_ofReal]
  norm_cast
  exact ev.symmetric j i

/-- The infinitesimal generator `gen ev = -i * Hc ev`. This is the `-i H-hat` of
`R-hat = exp(-i H-hat * Delta)`. -/
def gen (ev : DiscreteEvolution N) : Matrix (Fin N) (Fin N) ℂ :=
  (-Complex.I) • Hc ev

/-- The generator is skew-Hermitian: `(gen)^H = -gen`. This is the defining property of the generator
of a unitary one-parameter group. -/
theorem gen_skewHermitian (ev : DiscreteEvolution N) :
    (gen ev)ᴴ = -(gen ev) := by
  have hH : (Hc ev)ᴴ = Hc ev := (Hc_isHermitian ev).eq
  unfold gen
  rw [Matrix.conjTranspose_smul, hH]
  have hstar : star (-Complex.I) = Complex.I := by
    rw [star_neg, Complex.star_def, Complex.conj_I, neg_neg]
  rw [hstar, neg_smul, neg_neg]

/-! ## The unitary one-parameter group -/

/-- The recognition evolution family `U ev t = exp(t * gen ev)`. For the calibrated tick
`t = 8 tau_0 / hbar` this is the operator-level recognition step. -/
def U (ev : DiscreteEvolution N) (t : ℝ) : Matrix (Fin N) (Fin N) ℂ :=
  exp ℂ ((t : ℂ) • gen ev)

/-- Identity at `t = 0`: `U ev 0 = 1`. -/
theorem U_zero (ev : DiscreteEvolution N) : U ev 0 = 1 := by
  unfold U
  rw [Complex.ofReal_zero, zero_smul, exp_zero]

/-- One-parameter group law: `U ev s * U ev t = U ev (s + t)`. -/
theorem U_add (ev : DiscreteEvolution N) (s t : ℝ) :
    U ev s * U ev t = U ev (s + t) := by
  have hcomm : Commute ((s : ℂ) • gen ev) ((t : ℂ) • gen ev) :=
    ((Commute.refl (gen ev)).smul_left (s : ℂ)).smul_right (t : ℂ)
  unfold U
  rw [← Matrix.exp_add_of_commute ℂ _ _ hcomm]
  congr 1
  rw [← add_smul, ← Complex.ofReal_add]

/-- The adjoint of the evolution is the time-reversed evolution: `(U ev t)^H = U ev (-t)`. -/
theorem U_conjTranspose (ev : DiscreteEvolution N) (t : ℝ) :
    (U ev t)ᴴ = U ev (-t) := by
  have hexp : ((t : ℂ) • gen ev)ᴴ = ((-t : ℝ) : ℂ) • gen ev := by
    rw [Matrix.conjTranspose_smul, gen_skewHermitian]
    simp [Complex.star_def, Complex.conj_ofReal, smul_neg, neg_smul, Complex.ofReal_neg]
  unfold U
  rw [← Matrix.exp_conjTranspose, hexp]

/-- Unitarity: `(U ev t)^H * U ev t = 1` and `U ev t * (U ev t)^H = 1`. -/
theorem U_unitary (ev : DiscreteEvolution N) (t : ℝ) :
    (U ev t)ᴴ * U ev t = 1 ∧ U ev t * (U ev t)ᴴ = 1 := by
  refine ⟨?_, ?_⟩
  · rw [U_conjTranspose, U_add, neg_add_cancel, U_zero]
  · rw [U_conjTranspose, U_add, add_neg_cancel, U_zero]

/-- The evolution lies in the unitary group of `C^N`. -/
theorem U_mem_unitaryGroup (ev : DiscreteEvolution N) (t : ℝ) :
    U ev t ∈ Matrix.unitaryGroup (Fin N) ℂ := by
  rw [Matrix.mem_unitaryGroup_iff, Matrix.star_eq_conjTranspose]
  exact (U_unitary ev t).2

/-! ## The discrete step is the first-order truncation of the exponential -/

/-- The discrete evolution step of `HamiltonianEmergence` is exactly the first-order truncation
`(1 + gen ev) *v psi` of the exact unitary evolution `U ev 1 = exp(gen ev)`. This ties the existing
linear step to the operator exponential: `step` is the Euler / first-order approximation of the genuine
unitary recognition tick. -/
theorem step_eq_firstOrder (ev : DiscreteEvolution N) (ψ : DeviationHilbert N) :
    ev.step ψ = (1 + gen ev) *ᵥ ψ := by
  funext i
  rw [Matrix.add_mulVec, Matrix.one_mulVec, Pi.add_apply]
  have hg : (gen ev *ᵥ ψ) i
      = ∑ j, (-Complex.I) * ((ev.hamiltonian i j : ℂ) * ψ j) := by
    simp only [Matrix.mulVec, dotProduct, gen, Matrix.smul_apply, Hc, Matrix.of_apply,
      smul_eq_mul]
    exact Finset.sum_congr rfl (fun j _ => by ring)
  rw [hg, ← Finset.mul_sum]
  show ψ i - Complex.I * (∑ j, (ev.hamiltonian i j : ℂ) * ψ j)
      = ψ i + (-Complex.I) * ∑ j, (ev.hamiltonian i j : ℂ) * ψ j
  ring

/-! ## Master certificate -/

/-- **Finite-dimensional Stone generator certificate.** For any small-deviation Hamiltonian `ev` on
`C^N`, the recognition evolution is a genuine unitary one-parameter group generated by a self-adjoint
operator, and the existing discrete step is its first-order truncation:

* `hamiltonian_hermitian`: the complexified Hamiltonian is self-adjoint;
* `generator_skewHermitian`: `gen = -i H-hat` is skew-Hermitian;
* `evolution_id` / `one_parameter_group`: `U` is a one-parameter group;
* `evolution_unitary` / `evolution_mem_unitary`: every `U t` is unitary;
* `discrete_step_is_first_order`: the `HamiltonianEmergence` step is `(1 + gen) *v psi`.

Honest tag: CONDITIONAL THEOREM. The operator-level Stone structure is a kernel theorem; the
identification of the full nonlinear `R-hat` with this linearization to `O(eps^3)`, and the `8 tau_0 /
hbar` calibration of the tick, remain the named residuals. -/
structure StoneGeneratorCert (N : ℕ) (ev : DiscreteEvolution N) : Prop where
  hamiltonian_hermitian : (Hc ev).IsHermitian
  generator_skewHermitian : (gen ev)ᴴ = -(gen ev)
  evolution_id : U ev 0 = 1
  one_parameter_group : ∀ s t : ℝ, U ev s * U ev t = U ev (s + t)
  evolution_unitary : ∀ t : ℝ, (U ev t)ᴴ * U ev t = 1 ∧ U ev t * (U ev t)ᴴ = 1
  evolution_mem_unitary : ∀ t : ℝ, U ev t ∈ Matrix.unitaryGroup (Fin N) ℂ
  discrete_step_is_first_order :
    ∀ ψ : DeviationHilbert N, ev.step ψ = (1 + gen ev) *ᵥ ψ

/-- The Stone generator certificate holds for every discrete-evolution Hamiltonian. -/
theorem stoneGeneratorCert (ev : DiscreteEvolution N) :
    StoneGeneratorCert N ev where
  hamiltonian_hermitian := Hc_isHermitian ev
  generator_skewHermitian := gen_skewHermitian ev
  evolution_id := U_zero ev
  one_parameter_group := U_add ev
  evolution_unitary := U_unitary ev
  evolution_mem_unitary := U_mem_unitaryGroup ev
  discrete_step_is_first_order := step_eq_firstOrder ev

/-- **ONE-STATEMENT SUMMARY.** On the finite-dimensional recognition register `C^N`, the small-deviation
recognition evolution `U ev t = exp(t * (-i H-hat))` is a unitary one-parameter group generated by the
self-adjoint `H-hat`, and the discrete recognition step is its first-order truncation. -/
theorem operator_level_hamiltonian_emergence (ev : DiscreteEvolution N) :
    (Hc ev).IsHermitian ∧
      (gen ev)ᴴ = -(gen ev) ∧
      U ev 0 = 1 ∧
      (∀ s t : ℝ, U ev s * U ev t = U ev (s + t)) ∧
      (∀ t : ℝ, U ev t ∈ Matrix.unitaryGroup (Fin N) ℂ) ∧
      (∀ ψ : DeviationHilbert N, ev.step ψ = (1 + gen ev) *ᵥ ψ) :=
  ⟨Hc_isHermitian ev, gen_skewHermitian ev, U_zero ev, U_add ev, U_mem_unitaryGroup ev,
    step_eq_firstOrder ev⟩

end

end IndisputableMonolith.Foundation.HamiltonianEmergence
