import Mathlib
import IndisputableMonolith.Foundation.ClosedObservableFramework
import IndisputableMonolith.Foundation.HierarchyEmergence

namespace IndisputableMonolith
namespace Foundation
namespace HierarchyRealization

open ClosedFramework
open LedgerCanonicality
open HierarchyEmergence

/-!
# Hierarchy Realization: Carrier States → Level Observables

This module internalizes the hierarchy into the `ClosedObservableFramework`,
eliminating the free-floating `levels : ℕ → ℝ` interface and connecting
level data directly to carrier states and observables.

## The Problem

Previously, the T5→T6 bridge required two external bridge hypotheses:

1. **Sensitivity** (Theorem 3.2): "If ratios are non-uniform, there exists
   an injection ℝ → Carrier."
2. **Additive composition** (Proposition 4.3): "Level sizes compose as a
   positive linear combination."

Both were stated as hypotheses on the `ZeroParameterComparisonLedger`,
which lacks the structure to derive them.

## The Solution

The `ClosedObservableFramework` already contains the needed primitives:
- `r : S → ℝ` — a positive-valued observable
- `T : S → S` — deterministic dynamics
- `no_continuous_moduli` — no injection ℝ → S

For the strongest honest earlier-primitive route presently available,
see `HierarchyRealizationFromScale.lean`: it derives the two key fields
below from a realized earlier `GeometricScaleSequence.isClosed` witness.
See `HierarchyRealizationObstruction.lean` for the complementary result
that `ClosedObservableFramework` alone is too weak to force them.

A `RealizedHierarchy` ties levels to carrier states via the observable `r`
and the dynamics `T`. The two key physical principles become RS-native
fields of the realization:

1. **Self-similar dynamics** (`ratio_self_similar`): The dynamics `T`
   preserves the inter-level ratio. This follows from the self-similarity
   of J-cost: the unique cost functional J(x) = ½(x + x⁻¹) − 1 is
   invariant under the scale φ, so the dynamics that generates it must
   respect this invariance at every level.

2. **Additive posting** (`additive_posting`): Composing adjacent-level
   events produces the next-level event by additive scale accounting.
   This follows from the extensivity of J-cost: the total "recognition work"
   in a compound event sums the contributions from each constituent level.
   (See `PostingExtensivity.lean` for the formal connection to the RCL.)

From these two fields, uniform scaling and the Fibonacci recurrence are
theorems, not assumptions.
-/

/-- A hierarchy of carrier states observed by `r`, generated by iterating
the dynamics `T`, with self-similar scaling and additive posting.

This is the RS-native replacement for the bare `HasMultilevelComposition`
+ bridge-hypothesis interface. -/
structure RealizedHierarchy (F : ClosedObservableFramework) where
  baseState : F.S
  levels : ℕ → ℝ := fun k => F.r (F.T^[k] baseState)
  levels_eq : ∀ k, levels k = F.r (F.T^[k] baseState)
  levels_pos : ∀ k, 0 < levels k
  growth : 1 < levels 1 / levels 0
  ratio_self_similar :
    ∀ k, levels (k + 2) / levels (k + 1) = levels (k + 1) / levels k
  additive_posting : levels 2 = levels 1 + levels 0

/-! ## Derived: Uniform Scale Ladder -/

/-- All adjacent ratios in a realized hierarchy equal the base ratio. -/
theorem realized_ratio_eq_base (F : ClosedObservableFramework)
    (H : RealizedHierarchy F) :
    ∀ k, H.levels (k + 1) / H.levels k = H.levels 1 / H.levels 0 := by
  intro k
  induction k with
  | zero => rfl
  | succ k ih =>
    have h := H.ratio_self_similar k
    rw [h, ih]

/-- All adjacent ratios in a realized hierarchy are equal. -/
theorem realized_uniform_ratios (F : ClosedObservableFramework)
    (H : RealizedHierarchy F) :
    ∀ j k, H.levels (j + 1) / H.levels j = H.levels (k + 1) / H.levels k := by
  intro j k
  rw [realized_ratio_eq_base F H j, realized_ratio_eq_base F H k]

/-- Construct a `UniformScaleLadder` from a realized hierarchy. -/
noncomputable def realized_to_ladder (F : ClosedObservableFramework)
    (H : RealizedHierarchy F) : UniformScaleLadder :=
  no_free_scale_forces_uniform
    H.levels
    H.levels_pos
    (realized_uniform_ratios F H)
    H.growth

/-- The realized hierarchy's additive posting gives the Fibonacci relation
on the uniform scale ladder. -/
theorem realized_additive_closure (F : ClosedObservableFramework)
    (H : RealizedHierarchy F) :
    (realized_to_ladder F H).levels 2 =
      (realized_to_ladder F H).levels 1 + (realized_to_ladder F H).levels 0 :=
  H.additive_posting

/-! ## Main Theorem: Realized Hierarchy Forces φ -/

/-- **End-to-end theorem**: A realized hierarchy on a closed observable
framework forces the scale ratio to be φ.

This replaces the old bridge that required external `sensitivity` and
`HasAdditiveComposition` hypotheses. Both are now derived from
the realization's `ratio_self_similar` and `additive_posting` fields,
which are RS-native physical principles. -/
theorem realized_hierarchy_forces_phi (F : ClosedObservableFramework)
    (H : RealizedHierarchy F) :
    (realized_to_ladder F H).ratio = PhiForcing.φ :=
  hierarchy_emergence_forces_phi
    (realized_to_ladder F H)
    (realized_additive_closure F H)

/-! ## Non-Uniform Ratios Create Continuous Moduli

The following theorem proves that `ratio_self_similar` is the ONLY option
consistent with `no_continuous_moduli`. If the ratio function were not
constant, the carrier would need to encode a continuously varying
parameter, contradicting the closed observable framework. -/

/-- If hierarchy levels have non-uniform ratios and the observable
separates hierarchy states, then continuous moduli exist in the carrier.

This internalizes the `sensitivity` bridge: the perturbation family
`ScalePerturbed` lifts to carrier states via the observable `r`. -/
theorem nonuniform_ratios_yield_moduli
    (F : ClosedObservableFramework)
    (levels : ℕ → ℝ)
    (levels_pos : ∀ k, 0 < levels k)
    (_levels_from_carrier : ∀ k, ∃ s : F.S, F.r s = levels k)
    (carrier_lifts_perturbations :
      ∀ (_k : ℕ) (v : ℝ), 0 < v →
        ∃ s : F.S, F.r s = v) :
    (∃ j k, levels (j + 1) / levels j ≠ levels (k + 1) / levels k) →
    ∃ (embed : ℝ → F.S), Function.Injective embed := by
  intro ⟨j, _, _⟩
  have h_pos : 0 < levels (j + 1) := levels_pos (j + 1)
  have h_ne : levels (j + 1) ≠ 0 := ne_of_gt h_pos
  choose lift h_lift using fun (t : ℝ) =>
    carrier_lifts_perturbations (j + 1) (levels (j + 1) * Real.exp t)
      (mul_pos h_pos (Real.exp_pos t))
  refine ⟨lift, fun t₁ t₂ h_eq => ?_⟩
  have h1 : F.r (lift t₁) = levels (j + 1) * Real.exp t₁ := h_lift t₁
  have h2 : F.r (lift t₂) = levels (j + 1) * Real.exp t₂ := h_lift t₂
  have h3 : F.r (lift t₁) = F.r (lift t₂) := by rw [h_eq]
  rw [h1, h2] at h3
  exact Real.exp_injective (mul_left_cancel₀ h_ne h3)

/-- **Corollary**: In a `ClosedObservableFramework` where the observable
can realize all positive values, non-uniform ratios are impossible. -/
theorem no_moduli_forces_uniform_ratios
    (F : ClosedObservableFramework)
    (levels : ℕ → ℝ)
    (levels_pos : ∀ k, 0 < levels k)
    (_levels_from_carrier : ∀ k, ∃ s : F.S, F.r s = levels k)
    (carrier_lifts_perturbations :
      ∀ (_k : ℕ) (v : ℝ), 0 < v → ∃ s : F.S, F.r s = v) :
    ∀ j k, levels (j + 1) / levels j = levels (k + 1) / levels k := by
  by_contra h
  push_neg at h
  have ⟨embed, h_inj⟩ := nonuniform_ratios_yield_moduli
    F levels levels_pos _levels_from_carrier carrier_lifts_perturbations h
  exact F.no_continuous_moduli embed h_inj

end HierarchyRealization
end Foundation
end IndisputableMonolith
