import IndisputableMonolith.Foundation.ForcingStatus

/-!
# Object Distinction Floor

The object-level floor is exactly non-singletonness of the carrier.  This module
gives the capstone a stable import path for the exact scope theorem, without
rephrasing it through the legacy global `CompleteForcingChain`.
-/

namespace IndisputableMonolith
namespace Foundation
namespace ObjectDistinctionFloor

open DistinctionForcingAudit

/-- A carrier admits the distinction-threaded T-1-through-T8 spine exactly when
it admits an object-level distinction. -/
theorem object_floor_iff_nontrivial (K : Type) :
    ThreadedSpineExists K ↔ ∃ x y : K, x ≠ y :=
  threaded_spine_exists_iff_distinction K

/-- No object-level distinction, no carrier-dependent threaded spine. -/
theorem no_object_distinction_no_threaded_spine
    (K : Type) (hnone : ¬ ∃ x y : K, x ≠ y) :
    ¬ ThreadedSpineExists K :=
  no_distinction_no_threaded_spine K hnone

/-- The carrier-dependent floor is T-1 through T4 on the quotient generated by
the supplied distinction. -/
abbrev CarrierForcedFloor (K : Type) (h : ∃ x y : K, x ≠ y) : Prop :=
  DistinctionForcingAudit.CarrierForcedFloor K h

/-- The existing machine-checkable split: carrier-forced floor (T-1–T4), global
upper chain (T5–T8 instantiated beside the floor, not generated from `K`).

The T4 → T5 continuum obstruction is sharpened in
`FloorToT5Obstruction`: the Boolean forced quotient supplies recognition-work /
`LogicNat` orbit material toward T5, and cannot carry injective
log-positive-ratio coordinates. -/
theorem forces_vs_instantiates
    (K : Type) (h : ∃ x y : K, x ≠ y) :
    ForcesVsInstantiates K h :=
  forcesVsInstantiates_holds K h

/-- The instantiated upper chain is literally the global record. -/
theorem instantiated_chain_is_global
    (K : Type) (h : ∃ x y : K, x ≠ y) :
    (forces_vs_instantiates K h).instantiated_chain =
      DistinctionToDimension.legacy_complete_chain_is_global :=
  (forces_vs_instantiates K h).chain_is_global

end ObjectDistinctionFloor
end Foundation
end IndisputableMonolith
