import IndisputableMonolith.Foundation.DistinctionToJCost
import IndisputableMonolith.Foundation.HierarchyRealizationObstruction

/-!
# Strict Positive-Ratio Bridge

The forced Boolean quotient supplies the finite object-level floor.  The
analytic T5 theorem lives on positive ratios, equivalently on log-coordinates
`ℝ`.  This module records both sides:

* forward: once a positive-ratio comparison satisfying the Law of Logic is
  supplied, the RCL surface follows;
* obstruction: the two-class forced quotient cannot itself carry injective
  log-coordinate positive-ratio coordinates.

The obstruction is deliberately modest and precise.  It does not say no
positive-ratio comparison can be placed next to the floor.  It says that the
finite floor does not already contain the continuum coordinate surface required
by the analytic bridge.
-/

namespace IndisputableMonolith
namespace Foundation
namespace PositiveRatioBridgeStrict

open DistinctionToT4
open DistinctionToJCost

/-- Log-coordinate positive-ratio coordinates on the quotient generated by a
distinction.  Since positive ratios are equivalent to `ℝ` by logarithm, an
analytic positive-ratio surface carries at least an injective real coordinate
family. -/
structure LogPositiveRatioCoordinates
    {K : Type} (h : ∃ x y : K, x ≠ y) where
  coord : ℝ → ForcedQuotient h
  coord_injective : Function.Injective coord

/-- The forced two-class quotient cannot carry injective log-coordinate
positive-ratio coordinates. -/
theorem forced_quotient_no_log_positive_ratio_coordinates
    {K : Type} (h : ∃ x y : K, x ≠ y) :
    ¬ Nonempty (LogPositiveRatioCoordinates h) := by
  rintro ⟨H⟩
  have hInjectBool :
      Function.Injective (fun t : ℝ => forcedQuotientBoolEquiv h (H.coord t)) := by
    intro a b hab
    apply H.coord_injective
    exact (forcedQuotientBoolEquiv h).injective hab
  exact HierarchyRealizationObstruction.no_injective_real_to_bool
    (fun t : ℝ => forcedQuotientBoolEquiv h (H.coord t)) hInjectBool

/-- Concrete obstruction instance: the Boolean distinction floor does not carry
log-coordinate continuum positive-ratio coordinates. -/
theorem bool_floor_no_log_positive_ratio_coordinates :
    ¬ Nonempty (LogPositiveRatioCoordinates
      (K := Bool) ⟨false, true, Bool.noConfusion⟩) :=
  forced_quotient_no_log_positive_ratio_coordinates
    (K := Bool) ⟨false, true, Bool.noConfusion⟩

/-- Forward bridge: once a positive-ratio comparison operator satisfying the
Law of Logic is supplied, the RCL surface follows by the existing
`DistinctionToJCost` theorem. -/
theorem positive_ratio_bridge_forces_rcl_surface
    (C : LogicAsFunctionalEquation.ComparisonOperator)
    (hC : LogicAsFunctionalEquation.SatisfiesLawsOfLogic C) :
    ∃ (P : ℝ → ℝ → ℝ) (c : ℝ),
      DAlembert.Inevitability.HasMultiplicativeConsistency
        (LogicAsFunctionalEquation.derivedCost C) P ∧
      (∀ u v, P u v = 2 * u + 2 * v + c * u * v) :=
  DistinctionToJCost.positiveRatio_law_forces_RCL C hC

/-- Proof-bearing bridge package for a supplied positive-ratio comparison. -/
structure PositiveRatioBridge
    (C : LogicAsFunctionalEquation.ComparisonOperator)
    (hC : LogicAsFunctionalEquation.SatisfiesLawsOfLogic C) : Prop where
  rcl_surface :
    ∃ (P : ℝ → ℝ → ℝ) (c : ℝ),
      DAlembert.Inevitability.HasMultiplicativeConsistency
        (LogicAsFunctionalEquation.derivedCost C) P ∧
      (∀ u v, P u v = 2 * u + 2 * v + c * u * v)

/-- Constructor for the strict positive-ratio bridge. -/
theorem positiveRatioBridge_holds
    (C : LogicAsFunctionalEquation.ComparisonOperator)
    (hC : LogicAsFunctionalEquation.SatisfiesLawsOfLogic C) :
    PositiveRatioBridge C hC where
  rcl_surface := positive_ratio_bridge_forces_rcl_surface C hC

end PositiveRatioBridgeStrict
end Foundation
end IndisputableMonolith
