import Mathlib
import IndisputableMonolith.Foundation.ObserverFromRecognition
import IndisputableMonolith.Foundation.ArithmeticFromLogic

/-!
# Recognition Lattice from a Recognizer

This module turns the structural claim of Recognition Geometry into a Lean
theorem:

> a recognizer's kernel-equivalence classes are the first recognition lattice.

The lattice here is pre-spatial. It is the quotient of the carrier by the
primitive observer's indistinguishability kernel. The cells are equivalence
classes of configurations that the recognizer cannot tell apart. Finite
resolution is inherited from the finite event codomain `Fin n`.

## Honest scope

The lattice produced here is the **recognition quotient lattice**, not yet a
metric/topological manifold. It proves:

* existence of the lattice for any primitive interface;
* existence of such a lattice from any non-trivial recognition event;
* finite-resolution neighborhoods from event labels;
* uniqueness up to canonical equivalence for interfaces with the same kernel;
* interpretation of the universal iteration object `LogicNat` into the lattice.

Since the lattice can be finite (e.g. a two-outcome recognizer), the
`LogicNat` map is an interpretation, not an embedding/injection. This is the
same distinction as the Boolean parity collapse in Universal Forcing: the
iteration object remains free, while its image in a finite carrier may
collapse.
-/

namespace IndisputableMonolith
namespace Foundation
namespace RecognitionLatticeFromRecognizer

open Classical
open ObserverFromRecognition
open ArithmeticFromLogic

/-! ## Kernel quotient -/

/-- The setoid induced by a primitive interface. Two configurations are
equivalent iff the interface sends them to the same event. -/
def interfaceSetoid {K : Type*} (I : PrimitiveInterface K) : Setoid K where
  r := I.kernel
  iseqv := kernel_is_equivalence I

/-- The **recognition lattice** generated by an interface: the quotient by
the interface kernel. -/
def RecognitionLattice {K : Type*} (I : PrimitiveInterface K) : Type _ :=
  Quotient (interfaceSetoid I)

/-- The lattice cell containing a configuration. -/
def cellOf {K : Type*} (I : PrimitiveInterface K) (x : K) :
    RecognitionLattice I :=
  Quotient.mk (interfaceSetoid I) x

/-- Two configurations determine the same cell iff the recognizer cannot
distinguish them. -/
theorem cell_eq_iff_kernel {K : Type*} (I : PrimitiveInterface K) (x y : K) :
    cellOf I x = cellOf I y ↔ I.kernel x y := by
  exact Quotient.eq

/-! ## Finite-resolution labels and neighborhoods -/

/-- The finite event label of a recognition cell. This is well-defined because
the quotient identifies exactly configurations with equal observed labels. -/
def cellLabel {K : Type*} (I : PrimitiveInterface K) :
    RecognitionLattice I → Fin I.n :=
  Quotient.lift (fun x => I.observe x) (by
    intro x y h
    exact h)

@[simp] theorem cellLabel_cellOf {K : Type*} (I : PrimitiveInterface K) (x : K) :
    cellLabel I (cellOf I x) = I.observe x := rfl

/-- A finite-resolution neighborhood: all cells with a given observed label. -/
def neighborhood {K : Type*} (I : PrimitiveInterface K) (label : Fin I.n) :
    Set (RecognitionLattice I) :=
  { c | cellLabel I c = label }

/-- The cell of a configuration lies in the neighborhood of its observed label. -/
theorem cell_mem_own_neighborhood {K : Type*} (I : PrimitiveInterface K) (x : K) :
    cellOf I x ∈ neighborhood I (I.observe x) := by
  simp [neighborhood]

/-- Every lattice cell has a finite-resolution label. -/
theorem every_cell_has_label {K : Type*} (I : PrimitiveInterface K)
    (c : RecognitionLattice I) :
    ∃ label : Fin I.n, c ∈ neighborhood I label := by
  refine ⟨cellLabel I c, ?_⟩
  simp [neighborhood]

/-! ## Existence from non-trivial recognition -/

/-- A non-trivial recognition event forces a recognition lattice. -/
theorem nontrivial_recognition_forces_lattice (K : Type*) :
    NontrivialRecognition K →
    ∃ (I : PrimitiveInterface K), Nonempty (RecognitionLattice I) := by
  intro h
  obtain ⟨I, x, _y, _hdist, _hsep⟩ := nontrivial_recognition_forces_interface K h
  exact ⟨I, ⟨cellOf I x⟩⟩

/-- The minimal two-outcome lattice forced by a distinguished point. -/
noncomputable def pointLattice {K : Type*} (x₀ : K) : Type _ :=
  RecognitionLattice (pointInterface x₀)

/-! ## Uniqueness up to canonical equivalence -/

/-- Two primitive interfaces have the same kernel if they make the same
distinctions invisible. -/
def SameKernel {K : Type*} (I J : PrimitiveInterface K) : Prop :=
  ∀ x y : K, I.kernel x y ↔ J.kernel x y

/-- If two interfaces have the same kernel, then their recognition lattices
are canonically equivalent. -/
noncomputable def latticeEquivOfSameKernel {K : Type*}
    (I J : PrimitiveInterface K) (h : SameKernel I J) :
    RecognitionLattice I ≃ RecognitionLattice J where
  toFun := Quotient.map (fun x => x) (by
    intro x y hxy
    exact (h x y).mp hxy)
  invFun := Quotient.map (fun x => x) (by
    intro x y hxy
    exact (h x y).mpr hxy)
  left_inv := by
    intro c
    refine Quotient.inductionOn c ?_
    intro x
    rfl
  right_inv := by
    intro c
    refine Quotient.inductionOn c ?_
    intro x
    rfl

/-- The canonical equivalence sends each cell to the cell of the same
configuration. -/
theorem latticeEquivOfSameKernel_cell {K : Type*}
    (I J : PrimitiveInterface K) (h : SameKernel I J) (x : K) :
    latticeEquivOfSameKernel I J h (cellOf I x) = cellOf J x := rfl

/-! ## LogicNat interpretation into the lattice -/

/-- The carrier representative of an iterated recognition step. -/
def iteratedCarrier {K : Type*} (base : K) (step : K → K) : LogicNat → K
  | LogicNat.identity => base
  | LogicNat.step n => step (iteratedCarrier base step n)

/-- The canonical interpretation of `LogicNat` into a recognition lattice. -/
def logicNatToLattice {K : Type*} (I : PrimitiveInterface K)
    (base : K) (step : K → K) : LogicNat → RecognitionLattice I :=
  fun n => cellOf I (iteratedCarrier base step n)

@[simp] theorem logicNatToLattice_zero {K : Type*}
    (I : PrimitiveInterface K) (base : K) (step : K → K) :
    logicNatToLattice I base step LogicNat.identity = cellOf I base := rfl

@[simp] theorem logicNatToLattice_step {K : Type*}
    (I : PrimitiveInterface K) (base : K) (step : K → K) (n : LogicNat) :
    logicNatToLattice I base step (LogicNat.step n) =
      cellOf I (step (iteratedCarrier base step n)) := rfl

/-- Every primitive interface admits a `LogicNat` interpretation into its
recognition lattice as soon as a base point and a step function are chosen. -/
theorem logicNat_interprets_into_lattice {K : Type*}
    (I : PrimitiveInterface K) (base : K) (step : K → K) :
    ∃ interp : LogicNat → RecognitionLattice I,
      interp LogicNat.identity = cellOf I base ∧
      ∀ n, interp (LogicNat.step n) =
        cellOf I (step (iteratedCarrier base step n)) := by
  exact ⟨logicNatToLattice I base step, rfl, fun _ => rfl⟩

/-! ## Certificate -/

structure RecognitionLatticeCert (K : Type*) where
  from_nontrivial :
    NontrivialRecognition K → ∃ I : PrimitiveInterface K, Nonempty (RecognitionLattice I)
  kernel_equiv :
    ∀ I : PrimitiveInterface K, Equivalence I.kernel
  every_cell_labeled :
    ∀ (I : PrimitiveInterface K) (c : RecognitionLattice I),
      ∃ label : Fin I.n, c ∈ neighborhood I label
  same_kernel_unique :
    ∀ (I J : PrimitiveInterface K), SameKernel I J →
      RecognitionLattice I ≃ RecognitionLattice J
  logicNat_interpretation :
    ∀ (I : PrimitiveInterface K) (base : K) (step : K → K),
      ∃ interp : LogicNat → RecognitionLattice I,
        interp LogicNat.identity = cellOf I base ∧
        ∀ n, interp (LogicNat.step n) =
          cellOf I (step (iteratedCarrier base step n))

noncomputable def recognitionLatticeCert (K : Type*) : RecognitionLatticeCert K where
  from_nontrivial := nontrivial_recognition_forces_lattice K
  kernel_equiv := kernel_is_equivalence
  every_cell_labeled := every_cell_has_label
  same_kernel_unique := latticeEquivOfSameKernel
  logicNat_interpretation := logicNat_interprets_into_lattice

theorem recognitionLatticeCert_inhabited (K : Type*) :
    Nonempty (RecognitionLatticeCert K) :=
  ⟨recognitionLatticeCert K⟩

/-!
## Summary

The lattice is no longer a prose object:

```
non-trivial recognition
  → primitive interface
  → kernel equivalence relation
  → quotient cells
  → finite-resolution neighborhoods
  → recognition lattice
  → LogicNat interpretation
```

This module is the Lean bridge from primitive observer/interface to the
recognition lattice used in Recognition Geometry.
-/

end RecognitionLatticeFromRecognizer
end Foundation
end IndisputableMonolith
