import Mathlib
import IndisputableMonolith.Foundation.CostFromDistinction

/-!
# Recognition Ledger Floor: the free additive cost floor

This module closes the two genuine mathematical gaps identified in the
T-1 / T0 audit (the "Anil" critique, May 2026), as opposed to the many
"loopholes" that merely restate that a two-state floor is minimal.

The two real gaps are dual:

* the **kernel gap** (audit Loophole 2): the observable equivalence should be
  *derived* from the cost functional (its kernel), not imposed as an external
  setoid or a gauge group;
* the **cokernel gap** (audit Loophole 9): independent defects should
  *accumulate additively with multiplicity*, instead of being excluded from the
  independence relation to dodge `1 = 2` (audit Loophole 8).

Both are answered by one object: the free commutative monoid on a type `I` of
primitive distinctions,

```
DefectLedger I := I →₀ ℕ,
```

with cost `ledgerCost w` for a strictly positive weight `w`. On this carrier:

* additivity is **unconditional** (`ledgerCost_add`); no restricted independence
  relation is needed, so the `(true, true)` evasion of the Boolean floor
  disappears;
* the observable equivalence is the **kernel** of the cost (`observableSetoid`),
  and the floor is non-vacuous exactly when some weight is positive
  (`observable_floor_iff_pos_weight`);
* two independent copies of the same defect genuinely cost `2 w i`
  (`two_independent_same_defects`), i.e. multiplicity is represented;
* the data assembles into the existing `CostFromDistinction.CostFunction`
  abstraction with the **universal** independence relation
  (`ledgerConfigSpace`, `ledgerCostFunction`).

The two-state Boolean floor of T0 is the `n ∈ {0,1}` truncation of this object
under unit weight (`boolean_floor_is_truncation`).

Status: 0 sorry, 0 new axiom.
-/

namespace IndisputableMonolith
namespace Foundation
namespace RecognitionLedgerFloor

open CostFromDistinction

universe u
variable {I : Type u}

/-- A defect ledger: finitely supported multiplicities of primitive
distinctions. This is the free commutative monoid on `I`. -/
abbrev DefectLedger (I : Type u) := I →₀ ℕ

/-- Recognition cost of a ledger under a per-distinction weight `w`: the total
weighted multiplicity of performed distinctions. -/
noncomputable def ledgerCost (w : I → ℝ) (Γ : DefectLedger I) : ℝ :=
  Γ.sum (fun i n => (n : ℝ) * w i)

@[simp] theorem ledgerCost_zero (w : I → ℝ) :
    ledgerCost w (0 : DefectLedger I) = 0 := by
  simp [ledgerCost]

/-- **Unconditional additivity.** The free ledger needs no restriction of the
independence relation: the cost of a sum is always the sum of the costs. -/
theorem ledgerCost_add (w : I → ℝ) (Γ Δ : DefectLedger I) :
    ledgerCost w (Γ + Δ) = ledgerCost w Γ + ledgerCost w Δ := by
  unfold ledgerCost
  refine Finsupp.sum_add_index' ?_ ?_
  · intro i; simp
  · intro i a b; push_cast; ring

/-- The cost of a single defect of multiplicity `n` is `n · w i`. -/
theorem ledgerCost_single (w : I → ℝ) (i : I) (n : ℕ) :
    ledgerCost w (Finsupp.single i n) = (n : ℝ) * w i := by
  unfold ledgerCost
  rw [Finsupp.sum_single_index (by simp)]

theorem ledgerCost_nonneg (w : I → ℝ) (hw : ∀ i, 0 ≤ w i) (Γ : DefectLedger I) :
    0 ≤ ledgerCost w Γ := by
  unfold ledgerCost
  refine Finset.sum_nonneg ?_
  intro i _
  exact mul_nonneg (Nat.cast_nonneg _) (hw i)

/-! ## The observable quotient is the kernel of the cost (closes Loophole 2) -/

/-- Two ledgers are observationally the same when no weighted recognition cost
separates them. This is the *kernel* of the cost functional: the equivalence is
derived from cost, not imposed externally. -/
def ObservablySame (w : I → ℝ) (Γ Δ : DefectLedger I) : Prop :=
  ledgerCost w Γ = ledgerCost w Δ

/-- The observable equivalence relation generated by the cost functional. -/
def observableSetoid (w : I → ℝ) : Setoid (DefectLedger I) where
  r := ObservablySame w
  iseqv := ⟨fun _ => rfl, fun h => h.symm, fun h₁ h₂ => h₁.trans h₂⟩

/-- Cost is, by construction, constant on observable classes. Gauge invariance
is therefore automatic rather than assumed. -/
theorem ledgerCost_constant_on_classes (w : I → ℝ) {Γ Δ : DefectLedger I}
    (h : (observableSetoid w).r Γ Δ) : ledgerCost w Γ = ledgerCost w Δ := h

/-- **Non-vacuity of the observable floor.** The cost kernel is proper (there
exist observably distinct ledgers) exactly when some distinction carries
positive weight. With a constant-zero weight the kernel is everything, which is
the correct RS reading of the indiscrete gauge counterexample. -/
theorem observable_floor_iff_pos_weight (w : I → ℝ) (hw : ∀ i, 0 ≤ w i) :
    (∃ Γ Δ : DefectLedger I, ¬ ObservablySame w Γ Δ) ↔ (∃ i, 0 < w i) := by
  constructor
  · rintro ⟨Γ, Δ, hne⟩
    by_contra hno
    push_neg at hno
    have hzero : ∀ i, w i = 0 := fun i => le_antisymm (hno i) (hw i)
    apply hne
    show ledgerCost w Γ = ledgerCost w Δ
    have hall : ∀ Θ : DefectLedger I, ledgerCost w Θ = 0 := by
      intro Θ
      unfold ledgerCost
      refine Finset.sum_eq_zero ?_
      intro i _
      simp [hzero i]
    rw [hall Γ, hall Δ]
  · rintro ⟨i, hi⟩
    refine ⟨Finsupp.single i 1, 0, ?_⟩
    intro hsame
    have h : ledgerCost w (Finsupp.single i 1) = ledgerCost w (0 : DefectLedger I) := hsame
    rw [ledgerCost_single, ledgerCost_zero] at h
    push_cast at h
    simp only [one_mul] at h
    exact hi.ne' h

/-! ## Strict positivity gives the dichotomy (consistency = zero cost) -/

/-- With strictly positive weights, a ledger is costless exactly when it is the
empty ledger. This is the recognition-work dichotomy on the free floor. -/
theorem ledgerCost_eq_zero_iff (w : I → ℝ) (hw : ∀ i, 0 < w i)
    (Γ : DefectLedger I) :
    ledgerCost w Γ = 0 ↔ Γ = 0 := by
  constructor
  · intro h
    by_contra hΓ
    have hne : Γ.support.Nonempty := Finsupp.support_nonempty_iff.mpr hΓ
    obtain ⟨i, hi_supp⟩ := hne
    have hi : Γ i ≠ 0 := Finsupp.mem_support_iff.mp hi_supp
    have hpos : 0 < (Γ i : ℝ) * w i :=
      mul_pos (by exact_mod_cast Nat.pos_of_ne_zero hi) (hw i)
    have hnonneg : ∀ j ∈ Γ.support, 0 ≤ (Γ j : ℝ) * w j :=
      fun j _ => mul_nonneg (Nat.cast_nonneg _) (le_of_lt (hw j))
    have hle : (Γ i : ℝ) * w i ≤ ledgerCost w Γ :=
      Finset.single_le_sum hnonneg hi_supp
    linarith
  · intro h; subst h; simp

/-! ## Multiplicity is represented (closes Loopholes 8 and 9) -/

/-- **The cokernel fix.** Two independent copies of the same defect cost `2 w i`,
not `w i`. Multiplicity is genuinely represented, so the free ledger needs no
restriction of independence to avoid `1 = 2`: on this carrier, `1 + 1 = 2`. -/
theorem two_independent_same_defects (w : I → ℝ) (i : I) :
    ledgerCost w (Finsupp.single i 1 + Finsupp.single i 1) = 2 * w i := by
  rw [ledgerCost_add, ledgerCost_single]
  push_cast
  ring

/-- The Boolean two-state floor of T0 is the unit-weight truncation of the
ledger: cost equals multiplicity, and the Boolean floor is the clamp to
`{0, 1}`. -/
theorem boolean_floor_is_truncation (i : I) (n : ℕ) :
    ledgerCost (fun _ => (1 : ℝ)) (Finsupp.single i n) = (n : ℝ) := by
  rw [ledgerCost_single]; ring

/-- Boolean shadow of a natural-number generator count: zero is `false`, any
positive multiplicity is `true`. -/
def booleanTruncation (n : ℕ) : Bool :=
  decide (n ≠ 0)

@[simp] theorem booleanTruncation_zero :
    booleanTruncation 0 = false := by
  simp [booleanTruncation]

@[simp] theorem booleanTruncation_pos {n : ℕ} (hn : n ≠ 0) :
    booleanTruncation n = true := by
  simp [booleanTruncation, hn]

/-- OR on the Boolean T0 floor is induced by adding generator counts and then
truncating back to `{0, 1}`. -/
theorem booleanTruncation_add_eq_or (m n : ℕ) :
    booleanTruncation (m + n) =
      (booleanTruncation m || booleanTruncation n) := by
  unfold booleanTruncation
  by_cases hm : m = 0
  · subst m
    simp
  · by_cases hn : n = 0
    · subst n
      simp [hm]
    · have hsum : m + n ≠ 0 := by omega
      simp [hm, hn]

/-- Under unit weight, the ledger cost of `n` copies of one primitive
distinction is exactly the natural-number generator count. -/
theorem unit_cost_is_generator_count (i : I) (n : ℕ) :
    ledgerCost (fun _ => (1 : ℝ)) (Finsupp.single i n) = (n : ℝ) :=
  boolean_floor_is_truncation i n

/-! ## Assembly into the existing `CostFunction` abstraction

The free ledger instantiates `CostFromDistinction.ConfigSpace` with the
**universal** independence relation (every pair independent), and yet supports a
genuine `CostFunction`. This is the concrete refutation of audit Loophole 8: the
independence relation is not gerrymandered to avoid `1 = 2`; multiplicity makes
universal independence consistent with additivity. -/

/-- The free ledger as a configuration space, with universal independence. -/
noncomputable instance ledgerConfigSpace : ConfigSpace (DefectLedger I) where
  emp := 0
  join := (· + ·)
  IsConsistent := fun Γ => Γ = 0
  Independent := fun _ _ => True
  emp_consistent := rfl
  independent_symm := fun _ _ _ => trivial
  emp_independent := fun _ => trivial
  join_comm := add_comm
  join_assoc := fun a b c => add_assoc a b c
  emp_join := zero_add
  consistent_of_join_indep := by
    intro Γ₁ Γ₂ _ h₁ h₂
    subst h₁; subst h₂; simp
  inconsistent_of_join_indep_left := by
    intro Γ₁ Γ₂ _ h₁ hsum
    have hsum' : Γ₁ + Γ₂ = 0 := hsum
    apply h₁
    ext i
    have hi : Γ₁ i + Γ₂ i = 0 := by
      have h := congrArg (fun f : DefectLedger I => f i) hsum'
      simpa [Finsupp.add_apply] using h
    have h0 : Γ₁ i = 0 := by omega
    simpa using h0

/-- The free ledger carries a genuine recognition-work `CostFunction` for any
strictly positive weight, with universal independence. -/
noncomputable def ledgerCostFunction (w : I → ℝ) (hw : ∀ i, 0 < w i) :
    CostFunction (DefectLedger I) where
  C := ledgerCost w
  nonneg := ledgerCost_nonneg w (fun i => le_of_lt (hw i))
  dichotomy := by
    intro Γ
    exact ledgerCost_eq_zero_iff w hw Γ
  additivity := by
    intro Γ₁ Γ₂ _
    exact ledgerCost_add w Γ₁ Γ₂

/-- The free ledger satisfies the recognition-work constraint theorem of
`CostFromDistinction`, with multiplicity represented and independence universal. -/
theorem ledger_recognition_work_constraint (w : I → ℝ) (hw : ∀ i, 0 < w i) :
    Nonempty (CostFunction.RecognitionWorkConstraintCert (DefectLedger I)) :=
  CostFunction.recognition_work_constraint_theorem (ledgerCostFunction w hw)

end RecognitionLedgerFloor
end Foundation
end IndisputableMonolith
