import Mathlib
import IndisputableMonolith.Foundation.ObservableFloorWitness
import IndisputableMonolith.Foundation.BooleanProjectionFromMark

/-!
# T−1 Forced from a Distinction

This is the non-half-measure version of the T−1 repair.

The primitive is not an external admissibility package.  The primitive is a
distinction witness:

```
h : ∃ x y : K, x ≠ y
```

From that witness we construct, rather than assume:

* a marked pair;
* the Boolean projection generated by the distinction;
* the observable equivalence relation generated by that projection;
* the two-class quotient;
* uniqueness of Boolean coordinates up to Boolean automorphism;
* the legacy raw floor required by the existing `RealityCertificate`.

This module therefore preserves the strong thesis at the correct formal level:
everything in the T−1 floor interface is forced by the supplied distinction
witness.  If there is no object-level distinction, there is no object-level
forcing.  But once the distinction is given, the Boolean/observable floor is not
an extra measure.
-/

namespace IndisputableMonolith
namespace Foundation
namespace TMinus1ForcedFromDistinction

open ObservableFloor
open BooleanProjectionFromMark

/-! ## 1. From raw witness to marked pair -/

/-- Extract the marked pair carried by a distinction witness. -/
noncomputable def markedPairOfDistinction
    {K : Type*} (h : ∃ x y : K, x ≠ y) : MarkedPair K where
  base := Classical.choose h
  alt := Classical.choose (Classical.choose_spec h)
  distinct := Classical.choose_spec (Classical.choose_spec h)

/-- The Boolean projection forced by a chosen distinction witness. -/
noncomputable def forcedBoolProjection
    {K : Type*} (h : ∃ x y : K, x ≠ y) : K → Bool :=
  boolProjection (markedPairOfDistinction h)

@[simp] theorem forcedBoolProjection_base
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    forcedBoolProjection h (markedPairOfDistinction h).base = false :=
  (boolProjection_canonical_given_mark (markedPairOfDistinction h)).1

@[simp] theorem forcedBoolProjection_alt
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    forcedBoolProjection h (markedPairOfDistinction h).alt = true :=
  (boolProjection_canonical_given_mark (markedPairOfDistinction h)).2

/-! ## 2. The observable relation generated by the distinction -/

/-- The observable equivalence relation forced by a distinction: two
representatives are equivalent exactly when the forced Boolean projection gives
the same value on them. -/
noncomputable def forcedObservableSetoid
    {K : Type*} (h : ∃ x y : K, x ≠ y) : Setoid K where
  r x y := forcedBoolProjection h x = forcedBoolProjection h y
  iseqv := by
    constructor
    · intro x
      rfl
    · intro x y hxy
      exact hxy.symm
    · intro x y z hxy hyz
      exact hxy.trans hyz

/-- The distinction witness gives two representatives not identified by the
observable relation it generates. -/
theorem forcedObservableFloor
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    ObservableFloorWitness K (forcedObservableSetoid h).r := by
  refine ⟨(markedPairOfDistinction h).base, (markedPairOfDistinction h).alt, ?_⟩
  intro hrel
  simp [forcedObservableSetoid] at hrel

/-- The forced observable quotient is nontrivial. -/
theorem forcedQuotientNontrivial
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    ∃ a b : Quotient (forcedObservableSetoid h), a ≠ b :=
  (ObservableFloor.quotient_nontrivial_iff_observableFloor
    (forcedObservableSetoid h)).mpr (forcedObservableFloor h)

/-! ## 3. The forced quotient is Boolean -/

/-- The quotient-to-Bool map induced by the forced projection. -/
noncomputable def forcedQuotientToBool
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    Quotient (forcedObservableSetoid h) → Bool :=
  Quotient.lift (forcedBoolProjection h) (by
    intro x y hxy
    exact hxy)

/-- A Boolean representative for a Boolean value in the forced quotient. -/
noncomputable def forcedBoolRepresentative
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    Bool → Quotient (forcedObservableSetoid h)
  | false => Quotient.mk (forcedObservableSetoid h) (markedPairOfDistinction h).base
  | true => Quotient.mk (forcedObservableSetoid h) (markedPairOfDistinction h).alt

/-- The forced quotient map sends the distinguished representatives to their
Boolean names. -/
@[simp] theorem forcedQuotientToBool_representative
    {K : Type*} (h : ∃ x y : K, x ≠ y) (b : Bool) :
    forcedQuotientToBool h (forcedBoolRepresentative h b) = b := by
  cases b <;> simp [forcedQuotientToBool, forcedBoolRepresentative]

/-- Every quotient class is equal to the representative of its Boolean value. -/
theorem forcedBoolRepresentative_left_inv
    {K : Type*} (h : ∃ x y : K, x ≠ y)
    (q : Quotient (forcedObservableSetoid h)) :
    forcedBoolRepresentative h (forcedQuotientToBool h q) = q := by
  refine Quotient.inductionOn q ?_
  intro z
  by_cases hz : forcedBoolProjection h z = false
  · simp [forcedQuotientToBool, forcedBoolRepresentative, hz]
    exact Quotient.sound (by
      change forcedBoolProjection h (markedPairOfDistinction h).base =
        forcedBoolProjection h z
      simp [hz])
  · have hztrue : forcedBoolProjection h z = true := by
      cases hp : forcedBoolProjection h z
      · exact False.elim (hz hp)
      · rfl
    simp [forcedQuotientToBool, forcedBoolRepresentative, hztrue]
    exact Quotient.sound (by
      change forcedBoolProjection h (markedPairOfDistinction h).alt =
        forcedBoolProjection h z
      simp [hztrue])

/-- The observable quotient generated by a distinction is equivalent to Bool. -/
noncomputable def forcedQuotientEquivBool
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    Quotient (forcedObservableSetoid h) ≃ Bool where
  toFun := forcedQuotientToBool h
  invFun := forcedBoolRepresentative h
  left_inv := forcedBoolRepresentative_left_inv h
  right_inv := forcedQuotientToBool_representative h

/-! ## 4. Boolean coordinates are forced up to automorphism -/

/-- Boolean coordinates on the forced quotient. -/
structure ForcedBooleanCoordinates {K : Type*} (h : ∃ x y : K, x ≠ y) where
  coord : Quotient (forcedObservableSetoid h) ≃ Bool

/-- The canonical coordinates generated by the distinction witness. -/
noncomputable def canonicalForcedBooleanCoordinates
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    ForcedBooleanCoordinates h where
  coord := forcedQuotientEquivBool h

/-- Coordinate change between two Boolean coordinate systems on the quotient
generated by the same distinction. -/
def forcedBooleanCoordinateChange
    {K : Type*} {h : ∃ x y : K, x ≠ y}
    (c₁ c₂ : ForcedBooleanCoordinates h) : Bool ≃ Bool :=
  c₁.coord.symm.trans c₂.coord

/-- Boolean coordinates forced by the same distinction are unique up to Boolean
automorphism. -/
theorem forcedBooleanCoordinates_unique_up_to_bool_aut
    {K : Type*} {h : ∃ x y : K, x ≠ y}
    (c₁ c₂ : ForcedBooleanCoordinates h) :
    c₂.coord = c₁.coord.trans (forcedBooleanCoordinateChange c₁ c₂) := by
  ext q
  simp [forcedBooleanCoordinateChange]

/-! ## 5. The distinction forces a two-class observable Boolean floor

The `/reality` library continues here into the legacy `RealityCertificate`
interface (`recognition_certificate_forced_from_distinction` and the
`bundling_decomposition` audit), which depend on the full forcing-chain stack.
The public core slice keeps only the self-contained floor statements that the
ledger-floor T0 bridge consumes. -/

/-- The supplied distinction forces the raw floor expected by the legacy
certificate interface. -/
theorem rawFloor_forced_from_distinction
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    ∃ x y : K, x ≠ y :=
  h

/-- The supplied distinction forces a two-class observable Boolean floor. -/
theorem booleanObservableFloor_forced_from_distinction
    {K : Type*} (h : ∃ x y : K, x ≠ y) :
    Nonempty (Quotient (forcedObservableSetoid h) ≃ Bool) :=
  ⟨forcedQuotientEquivBool h⟩

/-- The canonical Boolean distinction witness. -/
theorem bool_distinction : ∃ x y : Bool, x ≠ y :=
  ⟨false, true, Bool.noConfusion⟩

end TMinus1ForcedFromDistinction
end Foundation
end IndisputableMonolith
