import IndisputableMonolith.LedgerPostingAdjacency
import IndisputableMonolith.Foundation.PublicSpine.ContextualReciprocityComplete

/-!
# PostingPhase3Wall: existing posting dynamics do not force the Boolean clock

The phase-2 reciprocal six-cycle is not merely an abstract cube walk. It is the
parity trace of six legal, minimum-cost ledger posts: debit accounts 0, 1, 2,
then credit accounts 0, 1, 2. The Recognition skew returns to its initial value,
every step is atomic, the parity pass is contextually reciprocal, and two cube
vertices are still missed.

This yields an impossibility result for the existing premise class. No predicate
that follows from every closed reciprocal minimum-cost posting pass can also
force Boolean surjection. A successful semantic clock therefore needs a new
global Recognition law beyond the current posting dynamics.
-/

namespace IndisputableMonolith
namespace Foundation
namespace PublicSpine
namespace PostingPhase3Wall

open Patterns
open LedgerPostingAdjacency
open ContextualReciprocityComplete

noncomputable section

/-- The zero three-account ledger. -/
def zeroLedger3 : LedgerState 3 :=
  { debit := fun _ => 0
    credit := fun _ => 0 }

/-- Debit accounts 0, 1, 2, then credit accounts 0, 1, 2. -/
def balancedSixPostingSchedule : ℕ → PostInstr 3
  | 0 => (⟨0, by decide⟩, Side.debit)
  | 1 => (⟨1, by decide⟩, Side.debit)
  | 2 => (⟨2, by decide⟩, Side.debit)
  | 3 => (⟨0, by decide⟩, Side.credit)
  | 4 => (⟨1, by decide⟩, Side.credit)
  | 5 => (⟨2, by decide⟩, Side.credit)
  | _ => (⟨0, by decide⟩, Side.debit)

/-- The ledger generated by the six-post schedule. -/
def balancedSixPostingLedger : ℕ → LedgerState 3 :=
  run zeroLedger3 balancedSixPostingSchedule

/-- The first six parity states of the generated ledger. -/
def balancedSixPostingPass : Fin 6 → Pattern 3 :=
  fun t => parity 3 (balancedSixPostingLedger t.val)

theorem balancedSixPostingLedger_zero :
    balancedSixPostingLedger 0 = zeroLedger3 := rfl

/-- The generated parity pass is exactly the phase-2 reciprocal six-cycle. -/
theorem balancedSixPostingPass_eq_balancedSixPass :
    balancedSixPostingPass = balancedSixPass := by
  have h01 : (0 : Fin 3) ≠ 1 := by decide
  have h02 : (0 : Fin 3) ≠ 2 := by decide
  have h10 : (1 : Fin 3) ≠ 0 := by decide
  have h12 : (1 : Fin 3) ≠ 2 := by decide
  have h20 : (2 : Fin 3) ≠ 0 := by decide
  have h21 : (2 : Fin 3) ≠ 1 := by decide
  funext t i
  fin_cases t <;> fin_cases i <;>
    simp [balancedSixPostingPass, balancedSixPostingLedger, zeroLedger3,
      balancedSixPostingSchedule, run, parity, phiVec, Recognition.phi,
      LedgerParityAdjacency.parityPattern, post, balancedSixPass, pattern3,
      h01, h02, h10, h12, h20, h21]

/-- After all six posts, the Recognition skew returns to its initial value. -/
theorem balancedSixPosting_phi_return :
    phiVec (balancedSixPostingLedger 6) =
      phiVec (balancedSixPostingLedger 0) := by
  have h01 : (0 : Fin 3) ≠ 1 := by decide
  have h02 : (0 : Fin 3) ≠ 2 := by decide
  have h10 : (1 : Fin 3) ≠ 0 := by decide
  have h12 : (1 : Fin 3) ≠ 2 := by decide
  have h20 : (2 : Fin 3) ≠ 0 := by decide
  have h21 : (2 : Fin 3) ≠ 1 := by decide
  funext i
  fin_cases i <;>
    simp [balancedSixPostingLedger, zeroLedger3, balancedSixPostingSchedule,
      run, phiVec, Recognition.phi, post, h01, h02, h10, h12, h20, h21]

/-- Each of the six transitions is an actual posting step. -/
theorem balancedSixPosting_step_isPostingStep (t : Fin 6) :
    PostingStep (balancedSixPostingLedger t.val)
      (balancedSixPostingLedger (t.val + 1)) := by
  refine ⟨(balancedSixPostingSchedule t.val).1,
    (balancedSixPostingSchedule t.val).2, ?_⟩
  simp [balancedSixPostingLedger, run]

/-- Every transition is legal, has unit `Jlog` cost, and is least-cost among
nontrivial monotone transitions from the same state. -/
theorem balancedSixPosting_step_certificate (t : Fin 6) :
    PostingStep (balancedSixPostingLedger t.val)
        (balancedSixPostingLedger (t.val + 1)) ∧
      LegalAtomicTick (balancedSixPostingLedger t.val)
        (balancedSixPostingLedger (t.val + 1)) ∧
      ledgerJlogCost (balancedSixPostingLedger t.val)
          (balancedSixPostingLedger (t.val + 1)) =
        Cost.Jlog (1 : ℝ) ∧
      ∀ L' : LedgerState 3,
        MonotoneLedger (balancedSixPostingLedger t.val) L' →
        balancedSixPostingLedger t.val ≠ L' →
        ledgerJlogCost (balancedSixPostingLedger t.val)
            (balancedSixPostingLedger (t.val + 1)) ≤
          ledgerJlogCost (balancedSixPostingLedger t.val) L' := by
  have hp := balancedSixPosting_step_isPostingStep t
  have hl := postingStep_implies_legalAtomicTick hp
  have hu := ledgerJlogCost_eq_Jlog1_of_postingStep hp
  refine ⟨hp, hl, hu, ?_⟩
  intro L' hmono hne
  rw [hu]
  exact Jlog1_le_ledgerJlogCost_of_monotone_nontrivial hmono hne

theorem balancedSixPostingPass_contextualReciprocity :
    PassContextualReciprocity balancedSixPostingPass := by
  rw [balancedSixPostingPass_eq_balancedSixPass]
  exact balancedSixPass_contextualReciprocity

theorem balancedSixPostingPass_oneBit :
    ∀ t : Fin 6,
      OneBitDiff (balancedSixPostingPass t)
        (balancedSixPostingPass (t + 1)) := by
  rw [balancedSixPostingPass_eq_balancedSixPass]
  exact balancedSixPass_oneBit

theorem balancedSixPostingPass_not_surjective :
    ¬ Function.Surjective balancedSixPostingPass := by
  rw [balancedSixPostingPass_eq_balancedSixPass]
  exact balancedSixPass_not_surjective

/-- The current Recognition premise class for a closed parity pass generated by
legal, minimum-cost posting. The states include the terminal return state. -/
structure ClosedReciprocalMinimalPostingPass {T : ℕ}
    (pass : Fin T → Pattern 3) where
  states : Fin (T + 1) → LedgerState 3
  initial_zero : states 0 = zeroLedger3
  parity_states :
    ∀ t : Fin T, pass t = parity 3 (states t.castSucc)
  posting :
    ∀ t : Fin T, PostingStep (states t.castSucc) (states t.succ)
  legal :
    ∀ t : Fin T, LegalAtomicTick (states t.castSucc) (states t.succ)
  unit_l1 :
    ∀ t : Fin T,
      ledgerL1Cost (states t.castSucc) (states t.succ) = 1
  unit_jlog :
    ∀ t : Fin T,
      ledgerJlogCost (states t.castSucc) (states t.succ) =
        Cost.Jlog (1 : ℝ)
  minimal_jlog :
    ∀ (t : Fin T) (L' : LedgerState 3),
      MonotoneLedger (states t.castSucc) L' →
      states t.castSucc ≠ L' →
      ledgerJlogCost (states t.castSucc) (states t.succ) ≤
        ledgerJlogCost (states t.castSucc) L'
  phi_return :
    phiVec (states (Fin.last T)) = phiVec (states 0)
  reciprocal : PassContextualReciprocity pass

/-- The reciprocal six-cycle inhabits the current posting premise class. -/
def balancedSixPostingCertificate :
    ClosedReciprocalMinimalPostingPass balancedSixPostingPass where
  states := fun t : Fin 7 => balancedSixPostingLedger t.val
  initial_zero := balancedSixPostingLedger_zero
  parity_states := by
    intro t
    rfl
  posting := by
    intro t
    simpa using balancedSixPosting_step_isPostingStep t
  legal := by
    intro t
    simpa using (balancedSixPosting_step_certificate t).2.1
  unit_l1 := by
    intro t
    simpa using (balancedSixPosting_step_certificate t).2.1.2
  unit_jlog := by
    intro t
    simpa using (balancedSixPosting_step_certificate t).2.2.1
  minimal_jlog := by
    intro t L' hmono hne
    simpa using
      (balancedSixPosting_step_certificate t).2.2.2 L' hmono hne
  phi_return := by
    simpa using balancedSixPosting_phi_return
  reciprocal := balancedSixPostingPass_contextualReciprocity

/-- A pass predicate is posting-derived when it follows for every pass in the
current closed reciprocal minimum-cost posting class. -/
def PostingDerivedPredicate
    (P : ∀ {d T : ℕ}, (Fin T → Pattern d) → Prop) : Prop :=
  ∀ {T : ℕ} (pass : Fin T → Pattern 3),
    ClosedReciprocalMinimalPostingPass pass → P pass

/-- Phase-3 impossibility. No predicate derived from the current posting premise
class can force Boolean surjection for every dimension and period. -/
theorem no_posting_derived_predicate_forces_surjection
    (P : ∀ {d T : ℕ}, (Fin T → Pattern d) → Prop)
    (hderived : PostingDerivedPredicate P) :
    ¬ ∀ {d T : ℕ} (pass : Fin T → Pattern d),
      P pass → Function.Surjective pass := by
  intro hforces
  exact balancedSixPostingPass_not_surjective
    (hforces balancedSixPostingPass
      (hderived balancedSixPostingPass balancedSixPostingCertificate))

end
end PostingPhase3Wall
end PublicSpine
end Foundation
end IndisputableMonolith
