import IndisputableMonolith.Geometry.TetrahedronRealization
import IndisputableMonolith.Geometry.CayleyMengerMatrix

/-!
# Gram and Cayley-Menger Bridge

This module isolates the theorem connecting the Euclidean Gram determinant
of a realized tetrahedron to its Cayley-Menger determinant.
-/

namespace IndisputableMonolith
namespace Geometry
namespace GramCayleyMenger

open TetrahedronRealization
open CayleyMengerPolynomial
open CayleyMengerMatrix

noncomputable section

/-- Squared-edge data generated by a symmetric `3×3` Gram matrix for the
edge vectors `(u, v, w)` from vertex `0`. -/
def sqEdgesFromGram (G : Matrix (Fin 3) (Fin 3) ℝ) : SqEdges :=
  fun e =>
    match e with
    | 0 => G 0 0
    | 1 => G 1 1
    | 2 => G 2 2
    | 3 => G 0 0 + G 1 1 - 2 * G 0 1
    | 4 => G 0 0 + G 2 2 - 2 * G 0 2
    | 5 => G 1 1 + G 2 2 - 2 * G 1 2

/-- Pure algebra: the tetrahedral Cayley-Menger polynomial generated by a
symmetric Gram matrix equals `8 * det G`. -/
theorem cm3_sqEdgesFromGram_eq_8_det (G : Matrix (Fin 3) (Fin 3) ℝ)
    (hsymm : ∀ i j, G i j = G j i) :
    cm3 (sqEdgesFromGram G) = 8 * Matrix.det G := by
  unfold sqEdgesFromGram cm3
  rw [Matrix.det_fin_three]
  have h10 : G 1 0 = G 0 1 := hsymm 1 0
  have h20 : G 2 0 = G 0 2 := hsymm 2 0
  have h21 : G 2 1 = G 1 2 := hsymm 2 1
  rw [h10, h20, h21]
  ring

/-- The Gram determinant version of Cayley-Menger volume equivalence. -/
def GramCayleyMengerTheorem : Prop :=
  ∀ T : RealizedTet,
    cm3 (sqEdgeOfPoints T) / 288 = Matrix.det (gram3 T) / 36

/-- Squared-distance identity induced by a basepoint Gram matrix. -/
private theorem sqDist_eq_baseGram
    (x y z : EuclideanSpace ℝ (Fin 3)) :
    ‖z - y‖ ^ 2 =
      ‖y - x‖ ^ 2 + ‖z - x‖ ^ 2 - 2 * inner ℝ (y - x) (z - x) := by
  rw [norm_sub_sq_real z y, norm_sub_sq_real y x, norm_sub_sq_real z x]
  simp [inner_sub_left, inner_sub_right, real_inner_comm]
  ring_nf

/-- The squared edges extracted from points agree with the squared edges
generated from the Gram matrix of the three basepoint edge vectors. -/
theorem sqEdgeOfPoints_eq_sqEdgesFromGram (T : RealizedTet) :
    sqEdgeOfPoints T = sqEdgesFromGram (gram3 T) := by
  funext e
  fin_cases e
  · simp [sqEdgeOfPoints, sqEdgesFromGram, vertexSqDist, edgeVertices3,
      ReggeRigorousFoundation.edgeVertices, gram3, basisEdgeVector, edgeVector]
  · simp [sqEdgeOfPoints, sqEdgesFromGram, vertexSqDist, edgeVertices3,
      ReggeRigorousFoundation.edgeVertices, gram3, basisEdgeVector, edgeVector]
  · simp [sqEdgeOfPoints, sqEdgesFromGram, vertexSqDist, edgeVertices3,
      ReggeRigorousFoundation.edgeVertices, gram3, basisEdgeVector, edgeVector]
  · simp [sqEdgeOfPoints, sqEdgesFromGram, vertexSqDist, edgeVertices3,
      ReggeRigorousFoundation.edgeVertices, gram3, basisEdgeVector, edgeVector]
    exact sqDist_eq_baseGram (T.p 0) (T.p 1) (T.p 2)
  · simp [sqEdgeOfPoints, sqEdgesFromGram, vertexSqDist, edgeVertices3,
      ReggeRigorousFoundation.edgeVertices, gram3, basisEdgeVector, edgeVector]
    exact sqDist_eq_baseGram (T.p 0) (T.p 1) (T.p 3)
  · simp [sqEdgeOfPoints, sqEdgesFromGram, vertexSqDist, edgeVertices3,
      ReggeRigorousFoundation.edgeVertices, gram3, basisEdgeVector, edgeVector]
    exact sqDist_eq_baseGram (T.p 0) (T.p 2) (T.p 3)

/-- For a realized tetrahedron, `cm3` of the extracted squared-edge data
equals `8 * det(Gram)`. -/
theorem cm3_sqEdgeOfPoints_eq_8_det_gram (T : RealizedTet) :
    cm3 (sqEdgeOfPoints T) = 8 * Matrix.det (gram3 T) := by
  rw [sqEdgeOfPoints_eq_sqEdgesFromGram]
  exact cm3_sqEdgesFromGram_eq_8_det (gram3 T) (gram3_symm T)

/-- The realized tetrahedron satisfies the Gram/Cayley-Menger volume theorem. -/
theorem gram_cayley_menger_realized (T : RealizedTet) :
    volumeSqFromCM T = volumeSqFromGram T := by
  unfold volumeSqFromCM volumeSqFromGram
  rw [cm3_sqEdgeOfPoints_eq_8_det_gram]
  ring

theorem gramCayleyMengerTheorem : GramCayleyMengerTheorem :=
  gram_cayley_menger_realized

/-- The same target expressed through the named volume-squared definitions. -/
theorem gram_cayley_menger_target_equiv :
    GramCayleyMengerTheorem ↔
      ∀ T : RealizedTet, volumeSqFromCM T = volumeSqFromGram T := by
  unfold GramCayleyMengerTheorem volumeSqFromCM volumeSqFromGram
  rfl

/-- The determinant-level target using `cmDet3`. -/
def GramCayleyMengerDetTheorem : Prop :=
  ∀ T : RealizedTet,
    cmDet3 (sqEdgeOfPoints T) / 288 = Matrix.det (gram3 T) / 36

/-- The determinant-level and polynomial-level targets are equivalent
because `cmDet3 = cm3`. -/
theorem gram_cayley_menger_det_target_equiv :
    GramCayleyMengerDetTheorem ↔ GramCayleyMengerTheorem := by
  constructor
  · intro h T
    have hT := h T
    rw [cmDet3_eq_cm3] at hT
    exact hT
  · intro h T
    have hT := h T
    rw [cmDet3_eq_cm3]
    exact hT

end

end GramCayleyMenger
end Geometry
end IndisputableMonolith
