import IndisputableMonolith.Gravity.SevenGaps.Gap2ExactClassCarrierAttack

namespace IndisputableMonolith
namespace Gravity
namespace SevenGaps
namespace Gap2ExactClassCarrierAttack

#check superseded_by_enriched_carrier
#print axioms superseded_by_enriched_carrier

end Gap2ExactClassCarrierAttack
end SevenGaps
end Gravity
end IndisputableMonolith
