import IndisputableMonolith.Gravity.SevenGaps.Gap5NetImbalanceDerivation

/-!
# Physical momentum from posting structure (MODEL)

**Verdict, stated first.** Route **(c) LANDED**. A library-wide search of the
A1/Gap5 posting-dynamics modules, the ledger chart carrier, and the B1
siblings finds **no** existing posting-grounded definition of physical
momentum: every prior module treats `p : LedgerState → ℝ` as an abstract
observable with properties. The honest move is therefore to **define** the
physical momentum from posting data and prove the two remaining obligations
for that definition.

## The definition (MODEL, posting-grounded)

A double-entry posting contributes a debit column and a credit column. The
ledger state is the pair `(d, c)`. The net charge of that state is the signed
difference of the two columns:

    physicalMomentum z := z.1 - z.2

This is definitionally the library `imbalance`. The definition mentions only
posting/ledger column data. It does **not** mention additivity, Cauchy,
`EnergyEqualsCost`, or the kinetic condition. Those are theorems about the
definition, not inputs to it.

## Obligations discharged

* **(O1)** `PostingIncidence physicalMomentum`:
  `p(d,c) = p(d,0) + p(0,c)` holds by the arithmetic of net charge
  (`d - c = (d - 0) + (0 - c)`).
* **(O2)** `AdditiveOnDebitAxis physicalMomentum`:
  `f(m) := p(m,0)` is the identity on the debit axis, so
  `f(m+n) = f(m) + f(n)` holds because consolidation of pure-debit net charges
  adds the counts.

With the already-proved consumer
`energyEqualsCost_of_posting_incidence_additive_unit`, continuity and unit
normalization of `physicalMomentum` (both theorems, no hypotheses) discharge
`EnergyEqualsCost physicalMomentum`. The chain from posting net charge to
`EnergyEqualsCost` therefore composes end-to-end for this defined `p`.

## What is NOT claimed

* No derivation of O1/O2 for an *arbitrary* abstract observable. The prior
  module's `cubeDiff` witness already shows that column incidence alone does
  not force the debit-axis Cauchy property
  (`N-route-qg-p1-p2-from-incidence-alone`). Defining the physical momentum as
  the net charge *selects* among column-separable observables.
* No flag flip. Flags 6 and 12 now rest on acceptance of this MODEL
  identification (physical momentum is the net charge of the double-entry
  ledger state), not on an undischarged quantified property of an abstract `p`.
* No use of `KineticCondition`, B1 kinetic-conditional additivity, or
  `EnergyEqualsCost` as a hypothesis. Those appear only as conclusions.
-/

namespace IndisputableMonolith
namespace Gravity
namespace SevenGaps
namespace PhysicalMomentum

open ChartFromLedgerMomentum MomentumAdditivity MomentumAdditivityComposition
open MomentumMagnitudeBridge EnergyEqualsCostDerivation NetImbalanceDerivation

noncomputable section

/-! ## §0. Inventory: no prior posting-grounded definition

The Gap5 chain modules (`Gap5ChartFromLedgerMomentum`,
`Gap5MomentumAdditivity`, `Gap5MomentumMagnitudeBridge`,
`Gap5EnergyEqualsCostDerivation`, `Gap5MomentumAdditivityComposition`,
`Gap5NetImbalanceDerivation`) all quantify over an abstract
`p : LedgerState → ℝ`. The chart carrier supplies `imbalance` as a *candidate*
linear functional, not as a declared physical-momentum definition. The Gap2
posting-dynamics modules define incidence/counts on posting alphabets, not a
chart-level momentum observable. This module supplies the missing definition.
-/

/-! ## §1. MODEL definition: physical momentum is net charge -/

/-- **Physical momentum (FOUNDATIONAL MODEL, adopted by Jon 2026-07-31,
`D-qg-eec-adopted-as-model-20260731`).** The signed net charge of a
double-entry ledger state: debit column minus credit column. Posting-grounded:
every posting contributes to exactly these two columns, and the momentum
generated by the posting layer is their signed difference. Equal by definition
to the library `imbalance`.

Adopted as a foundational MODEL, not derived: the wall theorem
`MomentumBridge.bridge_not_forced_by_scale_free_package` shows that no
conjunction of scale-free selection properties forces the momentum scale, so
the identification is an adoption, and the conversion-theorem lane (deriving
the scale from posting dynamics) stays OPEN frontier. The conditional-chain
assembly that discharges the bridge hypotheses against this identification
lives in `Gap5MomentumModelAssembly`. -/
def physicalMomentum : LedgerState → ℝ := imbalance

theorem physicalMomentum_eq_imbalance :
    physicalMomentum = imbalance := rfl

theorem physicalMomentum_def (z : LedgerState) :
    physicalMomentum z = z.1 - z.2 := rfl

/-! ## §2. (O1) Posting incidence from the net-charge definition -/

/-- **(O1).** Column posting incidence holds for the physical momentum because
net charge splits over the two axes: `d - c = (d - 0) + (0 - c)`. No abstract
incidence hypothesis: the property is a theorem about the definition. -/
theorem physicalMomentum_posting_incidence :
    PostingIncidence physicalMomentum := by
  intro d c
  change d - c = (d - 0) + (0 - c)
  ring

/-! ## §3. (O2) Debit-axis Cauchy from consolidation of net charges -/

/-- On the pure-debit axis the physical momentum is the identity: a pure-debit
state of charge `m` has net charge `m`. -/
theorem physicalMomentum_on_debit_axis (m : ℝ) :
    physicalMomentum (m, 0) = m := by
  change m - 0 = m
  ring

/-- **(O2).** Debit-axis additivity: consolidating two pure-debit net charges
adds the counts. Immediate from the identity reading on the debit axis. -/
theorem physicalMomentum_additiveOnDebitAxis :
    AdditiveOnDebitAxis physicalMomentum := by
  intro m n
  rw [physicalMomentum_on_debit_axis m, physicalMomentum_on_debit_axis n,
    physicalMomentum_on_debit_axis (m + n)]

/-- Net-imbalance reading is immediate: the momentum *is* the net charge. -/
theorem physicalMomentum_readsNetImbalance :
    ReadsNetImbalance physicalMomentum := by
  intro z
  change z.1 - z.2 = (z.1 - z.2) - 0
  ring

theorem physicalMomentum_swap_odd : SwapOdd physicalMomentum := by
  intro z
  change z.2 - z.1 = -(z.1 - z.2)
  ring

theorem physicalMomentum_continuous : Continuous physicalMomentum :=
  continuous_imbalance

theorem physicalMomentum_unit :
    physicalMomentum (1, 0) ^ 2 = 1 := by
  change ((1 : ℝ) - 0) ^ 2 = 1
  norm_num

theorem physicalMomentum_balance_vanishing :
    ∀ z : LedgerState, Balanced z → physicalMomentum z = 0 := by
  intro z hz
  change z.1 - z.2 = 0
  exact sub_eq_zero.mpr hz

theorem physicalMomentum_additive :
    ∀ z w : LedgerState,
      physicalMomentum (z + w) = physicalMomentum z + physicalMomentum w := by
  intro z w
  change (z.1 + w.1) - (z.2 + w.2) = (z.1 - z.2) + (w.1 - w.2)
  ring

/-! ## §4. End-to-end composition: EnergyEqualsCost for the defined p -/

/-- **End-to-end discharge.** For the posting-grounded physical momentum, O1,
O2, continuity, and unit are all theorems (no remaining hypotheses). The
upstream consumer therefore yields full consolidation additivity,
balance-vanishing, and `EnergyEqualsCost`. -/
theorem energyEqualsCost_of_physicalMomentum :
    (∀ z w : LedgerState,
      physicalMomentum (z + w) =
        physicalMomentum z + physicalMomentum w) ∧
      (∀ z : LedgerState, Balanced z → physicalMomentum z = 0) ∧
      EnergyEqualsCost physicalMomentum :=
  energyEqualsCost_of_posting_incidence_additive_unit
    physicalMomentum
    physicalMomentum_posting_incidence
    physicalMomentum_swap_odd
    physicalMomentum_additiveOnDebitAxis
    physicalMomentum_continuous
    physicalMomentum_unit

/-- Direct inhabitation of the full posting package (no hypotheses). -/
theorem physicalMomentum_inhabits_posting_package :
    PostingIncidence physicalMomentum ∧
      SwapOdd physicalMomentum ∧
      ReadsNetImbalance physicalMomentum ∧
      AdditiveOnDebitAxis physicalMomentum ∧
      Continuous physicalMomentum ∧
      physicalMomentum ((1, 0) : LedgerState) ^ 2 = 1 ∧
      EnergyEqualsCost physicalMomentum :=
  ⟨physicalMomentum_posting_incidence, physicalMomentum_swap_odd,
    physicalMomentum_readsNetImbalance, physicalMomentum_additiveOnDebitAxis,
    physicalMomentum_continuous, physicalMomentum_unit,
    (energyEqualsCost_of_physicalMomentum).2.2⟩

/-! ## §5. Selection among column-separable observables (scoped witness)

`cubeDiff` from the prior module is continuous, swap-odd, balance-vanishing,
unit-normalized, and column-incident, yet fails O2. It is a function of the
ledger columns but is **not** the net-charge reading. Quantifier first: this
is a concrete package witness on the stated `LedgerState` carrier, not a class
theorem over posting systems (`L-qg-witness-is-not-a-class-20260729`). The
MODEL definition selects the net-charge reading among column-separable
candidates; without that selection, O2 is not forced.
-/

theorem cubeDiff_is_not_physicalMomentum :
    cubeDiff ≠ physicalMomentum := by
  intro h
  have h1 := congrFun h ((2, 1) : LedgerState)
  -- cubeDiff (2,1) = 8 - 1 = 7; physicalMomentum (2,1) = 1
  change (2 : ℝ) ^ 3 - (1 : ℝ) ^ 3 = (2 : ℝ) - 1 at h1
  norm_num at h1

theorem net_charge_selected_among_incident :
    PostingIncidence physicalMomentum ∧
      AdditiveOnDebitAxis physicalMomentum ∧
      PostingIncidence cubeDiff ∧
      ¬ AdditiveOnDebitAxis cubeDiff ∧
      cubeDiff ≠ physicalMomentum :=
  ⟨physicalMomentum_posting_incidence, physicalMomentum_additiveOnDebitAxis,
    cubeDiff_posting_incidence, cubeDiff_not_additiveOnDebitAxis,
    cubeDiff_is_not_physicalMomentum⟩

/-! ## §6. Certificate -/

/-- **Physical-momentum MODEL verdict.** (c): `physicalMomentum` is defined as
the net charge of the double-entry ledger state; O1 and O2 are theorems about
that definition; the EnergyEqualsCost consumer fires with no remaining
hypotheses. Supporting selection witness: `cubeDiff` shares column incidence
and fails O2, so the net-charge identification is load-bearing. -/
structure PhysicalMomentumVerdict : Prop where
  definition_eq_imbalance : physicalMomentum = imbalance
  o1_posting_incidence : PostingIncidence physicalMomentum
  o2_debit_axis_cauchy : AdditiveOnDebitAxis physicalMomentum
  reads_net : ReadsNetImbalance physicalMomentum
  swap_odd : SwapOdd physicalMomentum
  continuous : Continuous physicalMomentum
  unit : physicalMomentum ((1, 0) : LedgerState) ^ 2 = 1
  end_to_end_energy_equals_cost :
    (∀ z w : LedgerState,
      physicalMomentum (z + w) =
        physicalMomentum z + physicalMomentum w) ∧
      (∀ z : LedgerState, Balanced z → physicalMomentum z = 0) ∧
      EnergyEqualsCost physicalMomentum
  selection_among_incident :
    PostingIncidence physicalMomentum ∧
      AdditiveOnDebitAxis physicalMomentum ∧
      PostingIncidence cubeDiff ∧
      ¬ AdditiveOnDebitAxis cubeDiff ∧
      cubeDiff ≠ physicalMomentum

theorem physicalMomentumVerdict : PhysicalMomentumVerdict where
  definition_eq_imbalance := physicalMomentum_eq_imbalance
  o1_posting_incidence := physicalMomentum_posting_incidence
  o2_debit_axis_cauchy := physicalMomentum_additiveOnDebitAxis
  reads_net := physicalMomentum_readsNetImbalance
  swap_odd := physicalMomentum_swap_odd
  continuous := physicalMomentum_continuous
  unit := physicalMomentum_unit
  end_to_end_energy_equals_cost := energyEqualsCost_of_physicalMomentum
  selection_among_incident := net_charge_selected_among_incident

/-! ## Axiom audit -/

#print axioms physicalMomentum_eq_imbalance
#print axioms physicalMomentum_posting_incidence
#print axioms physicalMomentum_additiveOnDebitAxis
#print axioms physicalMomentum_readsNetImbalance
#print axioms physicalMomentum_swap_odd
#print axioms physicalMomentum_continuous
#print axioms physicalMomentum_unit
#print axioms physicalMomentum_additive
#print axioms energyEqualsCost_of_physicalMomentum
#print axioms physicalMomentum_inhabits_posting_package
#print axioms cubeDiff_is_not_physicalMomentum
#print axioms net_charge_selected_among_incident
#print axioms physicalMomentumVerdict

end
end PhysicalMomentum
end SevenGaps
end Gravity
end IndisputableMonolith
